### ISSUE TITLE
Clone git repo as airflow user instead of root

### ISSUE THREAD

**Issue by DavidChenLondon** [airflow-helm/charts#10]
**What is your feature request?**

By default, current airflow helm chart will clone source code git repo using root user, which cause permission problem if some tasks require to create some files or directory under the git repo.

**What alternatives have you considered?**

Not yet.

**Comment by DavidChenLondon** [comment]
changed all code to use /tmp directory.

**Comment by thesuperzapper** [comment]
@DavidChenLondon can you provide a basic example of something which fails?

**Comment by DavidChenLondon** [comment]
Hi @thesuperzapper According to https://github.com/airflow-helm/charts/tree/main/charts/airflow#option-1---git-sidecar-recommended , our ML repo will be cloned as "root" user, but the worker will be running as "airflow" user, thus, this would cause file permission issue if we try to write some files under our ML repo source code directory, so we have to write to other writable directory instead (e.g. /tmp). A possible solution is `securityContext.runAsUser`, I'm still new to kubernetes, it would be helpful if other experienced people solve this issue. Thanks

**Comment by thesuperzapper** [comment]
@DavidChenLondon this is intended behaviour, you shouldn't be writing to the dag folder

There are a few reasons for this:
1. if we let you write, you would make the folder out of sync with the other workers/scheduler pods
2. the sync script will remove your files at the next sync anyway, [see the script here](https://github.com/airflow-helm/charts/blob/main/charts/airflow/templates/config/configmap-scripts-git.yaml#L74)

**Comment by DavidChenLondon** [comment]
@thesuperzapper thanks, the logic behind makes sense. We moved to all our temporary ML/ETL data into /tmp.
