### ISSUE TITLE
Add annotations block for airflow-env ConfigMap

### ISSUE THREAD

**Issue by kencieszykowski** [airflow-helm/charts#11]
**What is your feature request?**

Please add a way for us to add annotations directly to the airflow.cfg ConfigMap.  We deploy with Spinnaker, which naturally versions Secrets and ConfigMaps when they change.  As a result, worker pods search the ConfigMap to see what the name of the ConfigMap for the Env is; the problem is that it's a static value ( airflow-env ).  

To get around this, Spinnaker allows the annotation on Secrets / ConfigMaps:

`strategy.spinnaker.io/versioned: "false"`

This would allow a working configuration for anyone else that deploys via Spinnaker.

**What alternatives have you considered?**

We had previously created a subchart or additional Manifests that mirror the env configmap, but this would be the easiest way to get an official implementation with an alternative block for the configuration.

Happy to contribute or make the change.  

Thank you!

**Comment by thesuperzapper** [comment]
@kencieszykowski we always welcome contributions!

If you are going to contribute, please also take a look at Issue #8, but if you simply want to add annotation support to the ConfigMap, that shouldn't be too hard.
