### ISSUE TITLE
BUG: readiness / livliness probe of webserver do not respect AIRFLOW__WEBSERVER__BASE_URL

### ISSUE THREAD

**Issue by c-thiel** [airflow-helm/charts#112]
Version 8.0.2 of this chart.

**What is the bug?**
When setting the AIRFLOW__WEBSERVER__BASE_URL url to host airflow under a different path, the readiness and livliness probes of the webserver till poll on /health which then is not available. In the values.yaml there is no way to set the httpGet-path manually either:
https://github.com/airflow-helm/charts/blob/main/charts/airflow/templates/webserver/webserver-deployment.yaml#L114

**Comment by jrdunne** [comment]
Second this. The path setup from 7.16.0 would fix this error

https://github.com/airflow-helm/charts/blob/airflow-7.16.0/charts/airflow/templates/webserver/webserver-deployment.yaml#L227

**Comment by thesuperzapper** [comment]
This is an easy fix, I will just extract the value of `AIRFLOW__WEBSERVER__BASE_URL` into the liveness http path.

**Comment by thesuperzapper** [comment]
@c-thiel or @jrdunne can you confirm if this has been resolved after version `8.0.5` of the chart?

**Comment by jrdunne** [comment]
Thanks for the quick fix! 
The web server probes worked right away! I do not use flower so I have not tested the flower probe changes.
