### ISSUE TITLE
Redirect URI for Airflow to authenticate using Azure AD

### ISSUE THREAD

**Issue by Silpa-Suresh** [airflow-helm/charts#12]
Helm chart is deployed in Azure Kubernetes Service. And using Nginx Ingress Controller accessing the webserver UI in a URL: https://xyz.com/admin/

Configmap (airflow-webserver-config) is created as how mentioned [here](https://github.com/helm/charts/issues/23594#issuecomment-694763470).

Mounting through airflow.extraConfigmapMounts authentication could be established.

Provided the URL "https://xyz.com" as Redirect URI in Azure App registration getting the following error:
AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application: <clientID>

**Question:**

- [ ] What is the Redirect URI to be provided in the Azure AD App registration?
- [ ] Do we need any API permissions to be added in Azure AD?

**Comment by thesuperzapper** [comment]
@Silpa-Suresh that sounds like a OAUTH config error

Have you specified the correct `base_url`, `authorize_url` and `access_token_url`? You also might need to fix something on your Azure AD settings.

Regardless, this is not caused by the chart, and is a question for the airflow community.
