### ISSUE TITLE
Airflow 1.10.14 with statsd-exporter

### ISSUE THREAD

**Issue by ngreen-ny** [airflow-helm/charts#132]
I am using the helm chart for airflow version 1.10.14 in k8s.

**I have the following metrics defined:**

    AIRFLOW__METRICS__STATSD_ON: "True"
    AIRFLOW__METRICS__STATSD_HOST: "test-svc.airflow" (This is a service in k8s in the same airflow namespace where airflow is deployed)
    AIRFLOW__METRICS__STATSD_PORT: "9125" (9125 is correct)
    AIRFLOW__METRICS__STATSD_PREFIX: "testing-airflow"
    
**I have statsd-exporter setup as an extracontainer in the values.yaml:**
    
      - name: statsd-exporter
      image: prom/statsd-exporter
      imagePullPolicy: IfNotPresent
      ports:
      - containerPort: 9102
        protocol: TCP
      - containerPort: 8125
        protocol: TCP
      args:
        - --log.level=debug
    
**The web and scheduler pod is split and I am using the LocalExecutor:**

airflow-test-scheduler-779bcf686-4xjpp        4/4     Running   0          58m
airflow-test-web-598fbc9f87-hr26r             4/4     Running   0          58m

I am scraping test-svc.airflow:9102 as a target on prometheus side. 

**I can send a test from the scheduler and web pod by doing the following:**

echo "testnew09042021.test.myservice:1|c" | nc -w 1 -u test-svc.airflow 9125

**The following shows up in promtheus:**

testnew09042021_test_myservice{instance="test-svc.airflow:9102",job="statsd-exporter"}

I have version of statsd 3.3.0 installed by default with the chart. 

However there are no other metrics from airflow showing up from the instance. This works on v2.0.0 which I have setup previously.

There is no statsd errors in the airflow logs. Any idea what else I can check here? Thanks.

**Comment by thesuperzapper** [comment]
@ngreen-ny what is the issue>

**Comment by ngreen-ny** [comment]
I don't see metrics getting exported on the instance or via Prometheus, however I have multiple dags running and working as expected in airflow.

**Comment by ngreen-ny** [comment]
Please note I am using chart version 7.16.0

**Comment by thesuperzapper** [comment]
@ngreen-ny when using the `8.X.X` versions of the chart (preferably with airflow `2.0.0`) do you still have this issue?
