### ISSUE TITLE
Support specifying CPU/Memory Resources for Job container

### ISSUE THREAD

**Issue by luozhaoyu** [airflow-helm/charts#141]
**What is your feature request?**

Currently a Job does not have field for specifying CPU/Memory resources. e.g., https://github.com/airflow-helm/charts/blob/8611c766992a9f7156aad450f17beb2213cf667c/charts/airflow/templates/jobs/job-create-users.yaml

It would be nice to allow people to restrain the resource usage for Job containers 

**What alternatives have you considered?**

Otherwise, users have to patch the created k8s objects later

**Comment by thesuperzapper** [comment]
This is still an issue, reopening.

**Comment by thesuperzapper** [comment]
Closing this because PR https://github.com/airflow-helm/charts/pull/281 added the ability to set CPU/Memory requests for user/connections/pools/variables jobs.

The only job left is the `airflow db upgrade`, which will be replaced after https://github.com/airflow-helm/charts/issues/317 is resolved.
