### ISSUE TITLE
allow constraints file to be set for `pip install ...` with extraPipPackages

### ISSUE THREAD

**Issue by griseau** [airflow-helm/charts#143]
Hey guys, 
Do you have any way to provide a [constraint file](https://airflow.apache.org/docs/apache-airflow/stable/installation.html#constraints-files) when installing extra pip packages ? 

Airflow has some clear requirements and for example adding `apache-airflow-providers-databricks` as a requirement without fixing the `SQLAlchemy` package breaks everything. 

Thanks for your help ! 
Thomas

**Comment by thesuperzapper** [comment]
@griseau can you give an example of using a constraints file (outside kubernetes is fine)?

**Comment by griseau** [comment]
Hey @thesuperzapper,

For example you would do : 
```bash
pip install apache-airflow-providers-databricks==1.0.1 \
    -c https://raw.githubusercontent.com/apache/airflow/constraints-2.0.1/constraints-3.8.txt
```

**Comment by bensta** [comment]
Hi all, I second this request, it is something that should be quite easy to solve and that we need as well.

**Comment by thesuperzapper** [comment]
I will add this in the next minor release (as it will need a new value) but I hope to do minor release VERY soon with other stuff.

**Comment by griseau** [comment]
Alright, thanks !
