### ISSUE TITLE
Helm install fails when ingress path contains wildcard 

### ISSUE THREAD

**Issue by bensta** [airflow-helm/charts#144]
**What is the bug?**

Helm ingress path validity check not flexible for wildcard configs needed with istio ingress controller

The helm chart checks compatibility of AIRFLOW__WEBSERVER__BASE_URL and ingress.web.path (similar to flower paths). 
Some ingress controllers (isto/envoy) require a wildcard at the end of the ingress path config (/path/to/af/*)
Currently, the validation script checks for hard equality which leads to a failed install since AIRFLOW__WEBSERVER__BASE_URL typically  does not contain the wildcard. 

**What are your Helm values?**
```YAML
airflow:
  config:
    AIRFLOW__WEBSERVER__BASE_URL: http://localhost/airflow/test
    AIRFLOW__CELERY__FLOWER_URL_PREFIX: /airflow/test
ingress:
  enabled: true
  flower:
    annotations:
      kubernetes.io/ingress.class: istio
    path: /airflow/test/flower/*
  web:
    annotations:
      kubernetes.io/ingress.class: istio
    path: /airflow/test/*
```
I already implemented a solution, will open a pull request and link this issue 

**What is your Kubernetes Version?**:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:10:43Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**What is your Helm version?**:

```console
$ helm version
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}
```

**Comment by thesuperzapper** [comment]
@bensta can you confirm if this has been fixed in `8.0.7`?

**Comment by bensta** [comment]
@thesuperzapper  yep, works. Thanks for the fix. 
I split the removal of the trailing * and trailing / on purpose to also a trailing slash in the ingress.path config. I now noticed that you explicitly disallow this in you value checking script anyways. Why is that? For me it doesn´ t matter, I just don't understand the reason behind not allowing a trailing /

**Comment by thesuperzapper** [comment]
There is [a validation which prevents trailing slashes](https://github.com/airflow-helm/charts/blob/airflow-8.0.7/charts/airflow/templates/_helpers/validate-values.tpl#L87-L89), so not much point in supporting it in this validation.

But if I remember correctly, you cant have a trailing slash

**Comment by bensta** [comment]
Yep, I was referring to that validation telling the user not to use a trailing slash. I noticed it (after looking creating my pull request).  I just don't understand why it is there. 
With Nginx ingress, the trailing slash is not needed, but it is valid. I just tested it with minikube and it works. 

But again: Minor detail that should not block anyone. We can move on to more important stuff.
