### ISSUE TITLE
python-ldap gcc dependency issue

### ISSUE THREAD

**Issue by talnicolas** [airflow-helm/charts#149]
Hello,

This is a follow up question to the issue #66. When trying to use LDAP in the 8.0.6 release the installation of python-ldap fails due to gcc not being available (`unable to execute 'gcc': No such file or directory`) in the container. Building my own container with the following dependencies installed works:

`apt-get update && apt-get install -y build-essential libsasl2-dev python-dev libldap2-dev libssl-dev`

but obviously I don't want to have to maintain my own container and would rather have a solution to have this already available in the apache/airflow container or get installed through a chart configuration.

Does anyone have a suggestion (or an existing better way) to handle this?

**Comment by thesuperzapper** [comment]
@talnicolas do you know if there is a way to `pip install ...` without requiring a complication step?

Because I cant really see any other options (except adding an apt-get value like `extraAptGet`, lol!)

**Comment by bensta** [comment]
Google a documentation about that in their cloud composer doc.: https://cloud.google.com/composer/docs/how-to/using/installing-python-dependencies
Basically: Manually put the required binary in a subfolder and set LD_LIBRARY_PATH. 

But I think if you are using the helm chart to install your own Airflow, it is easier to just provide a custom Docker image that installs the dependencies. Depends on the use case though.

**Comment by thesuperzapper** [comment]
@bensta my main concern is that [these docs for LDAP auth](https://github.com/airflow-helm/charts/tree/main/charts/airflow#how-to-authenticate-airflow-users-with-ldapoauth) are incorrect as users will run into the `gcc` missing error if they add `python-ldap` to `web.extraPipPackages` 

I will add a quick warning for now.

**Comment by thesuperzapper** [comment]
Thinking about it, we could also let users pick a different container image to use for the `extraPipPackages` install, so they could use a container with `python` and `gcc`, rather than just using the `airflow.image` one.
(This will also let me update those LDAP docs with a one-line fix)

The pod template is [here](https://github.com/airflow-helm/charts/blob/airflow-8.0.6/charts/airflow/templates/_helpers/pods.tpl#L63-L80) for the pip-install container.

**Comment by thesuperzapper** [comment]
@talnicolas I just checked, and the `apache/airflow:2.0.1-python3.8` image already has `python-ldap` installed (but the `apache/airflow:1.10.15-python3.8` one does not), so I wont worry about a warning for now, as we are only partially supporting the `1.10.X` line.

**Comment by talnicolas** [comment]
You are right @thesuperzapper, I just followed the example in the readme that was adding this line:
```  
## the following configs require python-ldap
    - "python-ldap~=3.3.1"
```
but when removed it is indeed working fine.
Thanks a lot for the really quick help!

**Comment by thesuperzapper** [comment]
@talnicolas so wait, are you saying that the example actually breaks the `apache/airflow:2.0.1-python3.8` image?

**Comment by talnicolas** [comment]
Yes indeed, if you try to pip install python-ldap it will fail with the gcc error. Not sure how python-ldap is available in the container,  they probably don't install it through pip...
