### ISSUE TITLE
disable git-sync for webserver in airflow 2.0

### ISSUE THREAD

**Issue by thesuperzapper** [airflow-helm/charts#152]
I believe Dag Serialisation removes the need for the webserver to have access to the raw DAG files.

https://airflow.apache.org/docs/apache-airflow/stable/dag-serialization.html

Therefore, we can disable the git-sync sidecar in the webserver deployment if `airflow.legacyCommands` is `false`.

**Comment by davido912** [comment]
That's true. Once you enabled DAG serialisation there's no need for a gitsync on the webserver side. This isn't only Airflow specific but also in the more recent 1.10.x, so it would be nice to also have it included for previous Airflow versions

**Comment by davido912** [comment]
@thesuperzapper I opened a pull request, it should sort this out. Hope it's fine
