### ISSUE TITLE
airflow-upgrade-db job hangs

### ISSUE THREAD

**Issue by davido912** [airflow-helm/charts#153]
![image](https://user-images.githubusercontent.com/48397009/115041303-a4321b00-9ed2-11eb-9bf0-13aff2a94444.png)

Often times when the metadatabase is not ready yet, the initial db check up job hangs and fails to initialize. This results in deployments taking longer due to the fact that it takes time until the pod times out. I find from my experience that using the official Airflow CLI command often time hangs instead of a proper while loop that pokes the database for readiness. It would be beneficial to swap this one out with a normal bash "until" to poke the postgres db. 

It's pretty frustrating having all those crash loopbacks.

**Comment by thesuperzapper** [comment]
@davido912 is it specifically the `airflow db check` part which hangs, as we could just remove that `init-container` from the upgrade-db job.

It was always something I was thinking about, as clearly the `airflow db upgrade` part effectively checks if the external DB is up.

**Comment by thesuperzapper** [comment]
@davido912 I think a simple solution is using the linux `timeout` command in front of the `airflow db check`

**Comment by thesuperzapper** [comment]
@davido912 this should be fixed after version version `8.0.8` of the chart, as the `airflow db check` will now timeout after 16 seconds.

Can you confirm?
