### ISSUE TITLE
web-pod can't connect to postgres (password authentication failed)

### ISSUE THREAD

**Issue by Kyrremann** [airflow-helm/charts#16]
**Describe the bug**
When using the stable chart, my web-pod can't connect to the postgres-pod. I've also tried to exec into the postgres-pod, but the same result there.

**Version of Helm and Kubernetes**:
kubernetes: v1.16.7
helm: v3.2.3

**Which chart**:
stable/airflow

**What happened**:
airflow-web logs:
```
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  password authentication failed for user "postgres"
```
airflow-postgres logs:
```
2020-07-03 11:43:19.358 GMT [196] FATAL:  password authentication failed for user "postgres"
2020-07-03 11:43:19.358 GMT [196] DETAIL:  Password does not match for user "postgres".
	Connection matched pg_hba.conf line 1: "host     all             all             0.0.0.0/0               md5"
```

**What you expected to happen**:
Expected it to get up and running

**How to reproduce it** (as minimally and precisely as possible):
`helm install airflow stable/airflow`

**Anything else we need to know**:
This is a copy of https://github.com/helm/charts/issues/23061

**Comment by Kyrremann** [comment]
Ended up with this problem again, and I found out what the issue was! When you run helm uninstall it doesn't remove the PVC that the postgres-database uses. So the old database and password is still there when you run helm install again! So remember to delete the PVC!

**Comment by thesuperzapper** [comment]
If we migrate away from `stable/postgres` as described in https://github.com/airflow-helm/charts/issues/20, this problem should go away.
