### ISSUE TITLE
Remote bucker for remote logging to Azure blob storage not working

### ISSUE THREAD

**Issue by akshay654** [airflow-helm/charts#164]
Hi Team,

I am facing a issue while trying to achieve remote logging to Azure Blob storage container using wasb.

Following is the custom values.yaml file section that i have changed as per documentation-
values.yaml - 

  config:
    AIRFLOW__LOGGING__REMOTE_LOGGING: "True"
    AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER: "wasb-cmu_logs_kubernetes"
    AIRFLOW__LOGGING__REMOTE_LOG_CONN_ID: "wasb_default"

I have created the connection using wasb and conn type azure blob storage beforehand from ui.

Find below the airflow.cfg file section from weserver and scheduler pods where the remote logging related settings do not change after helm upgrade 

airflow.cfg from webserver and scheduler pods - 

remote_logging = False
remote_log_conn_id =
remote_base_log_folder =

Please let me know if i need to change something else to get it working.
Thanks,

**Comment by thesuperzapper** [comment]
@akshay654 what version of the chart & airflow are you using?

Can you share pod logs?

**Comment by akshay654** [comment]
> @akshay654 what version of the chart & airflow are you using?
> 
> Can you share pod logs?

Hi,

Chart Version - -8.0.7
airflow image - apache/airflow 2.0.1-python3.7

Attaching logs as well
[scheduler_logs_pod.zip](https://github.com/airflow-helm/charts/files/6341738/scheduler_logs_pod.zip)

**Comment by thesuperzapper** [comment]
Also, how are you using an `airflow.cfg` file?

All configs should be set with the `airflow.config` value, please see the docs:
https://github.com/airflow-helm/charts/tree/main/charts/airflow#how-to-set-airflow-configs

**Comment by akshay654** [comment]
Hi,

Yes, I am using the values.yaml file for passing the values, Inside values.yaml under section airflow.config, I have placed my values in that section only.

The airflow.cfg file section i shared is basically from inside the pod when i was just checking whether my values are reflecting in the file or not and they were blank as shown above.

doc referred - https://github.com/airflow-helm/charts/tree/main/charts/airflow 
in the above urls section i referred was how to persist airflow logs option 2.

Thanks,

**Comment by thesuperzapper** [comment]
@akshay654 are you still having this issue?

**Comment by deepankumaresan** [comment]
@akshay654  Was is issue Resolved for you I am facing the same issue . Can you please share what you have done

**Comment by thesuperzapper** [comment]
@deepankumaresan you can raise another issue/discussion-question if you have a problem.

**Comment by thesuperzapper** [comment]
@deepankumaresan and others, I know its been a while, but we have a discussion that explains how to use Azure Blob Store that can be found at: https://github.com/airflow-helm/charts/discussions/749#discussioncomment-6064909

There is a big problem with how airflow itself has implemented this, but it is possible to work around.
