### ISSUE TITLE
pip install fails with airflow 2.0.2 docker image 

### ISSUE THREAD

**Issue by thesuperzapper** [airflow-helm/charts#168]
Right now, if you use the `apache/airflow:2.0.2-python3.8` image with `airflow.extraPipPackages` set to anything, it will fail with the error: `ERROR: Can not combine '--user' and '--target'`

**Comment by ZeWaren** [comment]
In the meantime, I've created a custom docker image that just pulls the official image (`apache/airflow`) and issues `pip install` commands on top.

    FROM apache/airflow:2.0.2-python3.8
    RUN pip install "jambon==1.3.23" "poulet==0.1.3" "truite==0.13.0"

Using that image (with `airflow.image.repository`) allowed me to get rid of the `airflow.extraPipPackages` directive in the chart and deploy my cluster again.

**Comment by thesuperzapper** [comment]
I know the cause for this issue, its due to the addition of `PIP_USER=true` to the [apache/airflow Dockerfile](https://github.com/apache/airflow/blob/2.0.2/Dockerfile#L531-L533).

I will fix this in the next patch release, which I will push out once I solve https://github.com/airflow-helm/charts/issues/169

**Comment by thesuperzapper** [comment]
Hi all, this should be resolved after version `8.0.9` of the chart.
