### ISSUE TITLE
Airflow Plugin & Overriding files

### ISSUE THREAD

**Issue by zhaoyonglau** [airflow-helm/charts#172]
I need advice on how we can add airflow custom plugin and new files like a custom SecurityManager.py (to override the existing ones in Airflow). I began with installation of airflow in my local python environment and want to move to k8 deployment (which I am still learning) for my next step.

**Comment by hussainsaify** [comment]
@zhaoyonglau I mounted them as a configmap in webeserver section in values.yaml.

eg.

  extraVolumeMounts:
    - name: custom-security-config
      mountPath: /opt/python/site-packages/flask_appbuilder/security/manager.py
      subPath: "manager.py"
    - name: sqla-manager-config
      mountPath: /opt/python/site-packages/flask_appbuilder/security/sqla/manager.py
      subPath: "manager.py"
  extraVolumes:
    - name: custom-security-config
      configMap:
        name: my-custom-security-config
    - name: sqla-manager-config
      configMap:
        name: sqla-manager-config

**Comment by thesuperzapper** [comment]
@zhaoyonglau regarding plugins, once https://github.com/airflow-helm/charts/issues/251 is resolved, then you will also be able to store plugins in your git-sync DAGs repo, and set `AIRFLOW__CORE__PLUGINS_FOLDER = /opt/airflow/dags/repo/plugins`.

Note, you can already do this, but the plugins wont be visible in the webserver UI.

**Comment by thesuperzapper** [comment]
I have also made an issue to add documentation for using airflow plugins: https://github.com/airflow-helm/charts/issues/252
