### ISSUE TITLE
persist Airflow logs on Kubernetes PVC is status pending

### ISSUE THREAD

**Issue by superbeer** [airflow-helm/charts#179]
**What is the bug?**
persist Airflow logs on Kubernetes PVC is status pending
A clear description of the bug.

**What are your Helm values?**
logs:
  persistence:
    enabled: true
    # storageClass: "" ## WARNING: your StorageClass MUST SUPPORT `ReadWriteMany`
    accessMode: ReadWriteMany
    size: 1Gi
Any relevant parts of your `custom_values.yaml`

**What is your Kubernetes Version?**:

```console
$ kubectl version
please put the output here
```

**What is your Helm version?**:

```console
$ helm version
please put the output here
```
chart airflow-8.0.8

**Comment by bensta** [comment]
Does your storage class support ReadWriteMany?  It is required by this chart in order to enable log persistence. 
[Here](https://kubernetes.io/docs/concepts/storage/persistent-volumes/) is a table of which storage classes do and which ones don't.

**Comment by thesuperzapper** [comment]
@superbeer can you confirm if you are using a `StorageClass` which supports `ReadWriteMany`?

**Comment by Miskho** [comment]
I am experiencing the same problem, does anyone have any solutions

**Comment by thesuperzapper** [comment]
@Miskho I have recently updated the docs for using a PVC to store logs.

Please see ["How to persist airflow logs?" - Option 1 - Persistent Volume Claim](https://github.com/airflow-helm/charts/blob/main/charts/airflow/docs/faq/monitoring/log-persistence.md#option-1---persistent-volume-claim), and tell me if you still have problems.

**Comment by Miskho** [comment]
It was about my provisioner not supporting ReadWriteManyAccess
