### ISSUE TITLE
cant set environment variables in init-containers (ex: HTTP_PROXY)

### ISSUE THREAD

**Issue by yehlo** [airflow-helm/charts#180]
**What is the bug?**

Unable to set a proxy in initContainer: 
https://github.com/airflow-helm/charts/blob/6efcae8394055ec091980df7d1c1eec8e199a7e3/charts/airflow/templates/_helpers/pods.tpl#L63 

In pre 8.0 Chart i just added the env variable HTTP(S)_PROXY according to our environment. 

I'd propose to add an Option along the lines of ```pipProxy``` whichs adds an env variable within the corresponding initContainer. 

**What are your Helm values?**

**What is your Kubernetes Version?**:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:32:58Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```

**What is your Helm version?**:

```console
$ helm version
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}
```

**Comment by thesuperzapper** [comment]
This currently effects `dags-git-sync` and `install-pip-packages`.

**Comment by thesuperzapper** [comment]
@yehlo this was resolved by https://github.com/airflow-helm/charts/pull/365, and will be in the next release of the chart `8.5.0` (coming very soon).

**Comment by thesuperzapper** [comment]
@yehlo to be clear, PR https://github.com/airflow-helm/charts/pull/365 only resolved this for the `pip-install` container, I have raised issue: https://github.com/airflow-helm/charts/issues/376 to also address this for the `git-sync` container.
