### ISSUE TITLE
Helm 2.xx.0 install doesn't work despite the readme file indicating it should

### ISSUE THREAD

**Issue by Radu-Codrin** [airflow-helm/charts#184]
**What is the bug?**

Helm 2.x doesn't seem to be supported anymore, because the chart relies on some Helm 3 functions in the templates.

* On Helm 2.11.0:

```bash
[ERROR] templates/: parse error in "docker-airflow-2/templates/worker/worker-statefulset.yaml": template: docker-airflow-2/templates/worker/worker-statefulset.yaml:1: function "concat" not defined
```

* On Helm 2.17.0:
> I have upgraded to the latest Helm 2 version I could - 2.17.0 and the 'concat' function is now supported but there are definitely other functions that are specific for Helm 3:

```bash
[ERROR] templates/: parse error in "docker-airflow-2/templates/webserver/webserver-deployment.yaml": template: docker-airflow-2/templates/webserver/webserver-deployment.yaml:119: function "get" not defined
```

**What are your Helm values?**

> I used the default `values.yaml` file and tried a simple install.

**What is your Kubernetes Version?**:

```console
$ kubectl version

Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.10", GitCommit:"f3add640dbcd4f3c33a7749f38baaac0b3fe810d", GitTreeState:"clean", BuildDate:"2020-05-20T14:00:52Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.16", GitCommit:"d88fadbd65c5e8bde22630d251766a634c7613b0", GitTreeState:"clean", BuildDate:"2020-12-18T15:59:27Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**What is your Helm version?**:

```console
$ helm version

# Helm 2.11.0
Client: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}

# Helm 2.17.0
Client: &version.Version{SemVer:"v2.17.0", GitCommit:"a690bad98af45b015bd3da1a41f6218b1a451dbe", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.11.0", GitCommit:"2e55dbe1fdb5fdb96b75ff144a339489417b146b", GitTreeState:"clean"}
```

**Comment by thesuperzapper** [comment]
@Radu-Codrin realistically, we should be dropping support for Helm 2.

Would this significantly impact you?

**Comment by Radu-Codrin** [comment]
Right now I am limited to using Helm 2.11.0 due to project infrastructure and CI system limitations, but at some point, the migration will become inevitable :)
But first, I need to be able to deploy Airflow 2.0.x in our clusters, so I'll have to find another solution.
I was looking at the chart here: https://github.com/apache/airflow/tree/master/chart
It looks like it has only one template depending on Helm 3 functions and that can be easily changed to work in Helm 2 (already tested it).
Do you know how big are the differences between the two charts?

**Comment by kalkov** [comment]
I'm also experienced the same issue with helm `v2.15.2` - "function "get" not defined", would love to see support for helm 2.

**Comment by thesuperzapper** [comment]
I have decided to remove the docs for helm 2, if you want to continue using the chart, please consider upgrading to helm 3.

(Or contribute a fix if your really game)

**Comment by Radu-Codrin** [comment]
Fair enough. We will consider upgrading. Thanks!
