### ISSUE TITLE
failed to install

### ISSUE THREAD

**Issue by uxth** [airflow-helm/charts#187]
I am using latest version, also latest version of k8s.

got this error
helm install   $RELEASE_NAME   airflow-stable/airflow   --namespace $NAMESPACE   --version $CHART_VERSION   --values $VALUES_FILE
Error: failed post-install: timed out waiting for the condition

kubectl get pod -n airflow
NAME                                            READY   STATUS                  RESTARTS   AGE
my-airflow-cluster-flower-76bcc89656-b4xtj      0/1     Init:Error              6          7m23s
my-airflow-cluster-postgresql-0                 0/1     Pending                 0          7m23s
my-airflow-cluster-redis-master-0               1/1     Running                 0          7m23s
my-airflow-cluster-scheduler-5f899966d7-cdsqk   0/1     Init:0/2                6          7m23s
my-airflow-cluster-web-58fd56fbb-gn6x4          0/1     Init:CrashLoopBackOff   6          7m23s
my-airflow-cluster-worker-0                     0/1     Init:CrashLoopBackOff   6          7m23s
------------------------------------------------------------------------------------------------------------

kubectl -n airflow  logs my-airflow-cluster-upgrade-db-69hng
Error from server (BadRequest): container "upgrade-db" in pod "my-airflow-cluster-upgrade-db-69hng" is waiting to start: PodInitializing
-----------------------------------------------------------------------------------------------------------------
kubectl -n airflow  logs my-airflow-cluster-scheduler-5f899966d7-cdsqk
Error from server (BadRequest): container "airflow-scheduler" in pod "my-airflow-cluster-scheduler-5f899966d7-cdsqk" is waiting to start: PodInitializing
----------------------------------------------------------------------------------------------------------------

the only one does not have logs is my-airflow-cluster-postgresql-0.

could someone help me here, why it could not start?

many thanks

**Comment by thesuperzapper** [comment]
@uxth I assume you are not directly running `helm install`?

If so, check if whatever you use to run `helm install ...` has specified the `--wait` flag, if it has, then you need to set the `helmWait` value to `true`:
https://github.com/airflow-helm/charts/blob/airflow-8.0.9/charts/airflow/values.yaml#L1-L3

**Comment by thesuperzapper** [comment]
@uxth can you give [version 8.4.0](https://github.com/airflow-helm/charts/blob/main/charts/airflow/CHANGELOG.md#840---2021-07-09) of the chart a go?
