### ISSUE TITLE
Kubernetes pods remains after the task is completed

### ISSUE THREAD

**Issue by srthok** [airflow-helm/charts#188]
**What is the bug?**
When DAG execution is completed,Pods are supposed to be terminated. But,They remains forever.
A clear description of the bug.

**What are your Helm values?**

  kubernetesPodTemplate:
        stringOverride: |-
          apiVersion: v1
          kind: Pod
          metadata:
            name: exec-pod
          spec:
            containers:
              - name: base
                image: dummy-image
                env :
                  - name: AIRFLOW__CORE__FERNET_KEY
                    value: xxxxxxxxx
                  - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
                    value:  xxxxxxxxxx
                volumeMounts:
                  - name: persistent-storage
                    mountPath: /efs
            volumes:
              - name: persistent-storage
                persistentVolumeClaim:
                  claimName: efs-storage-claim

**What is your Kubernetes Version?**:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T21:15:16Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**What is your Helm version?**:

```console
$ helm version
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.15.8"}
```

**Comment by thesuperzapper** [comment]
@srthok Is there a reason you are overriding the default `pod_template.yaml` with `airflow.kubernetesPodTemplate.stringOverride`, rather than using the default generated one?

**Comment by srthok** [comment]
@thesuperzapper Thanks much for your response. I am using AWS EFS for Dags location and to mount EFS into the container, I am overriding pod_template. I am using chart version  8.0.2.

**Comment by thesuperzapper** [comment]
@srthok can you try setting the `airflow. extraVolumeMounts` and `airflow.extraVolumes` rather than overriding with `airflow. kubernetesPodTemplate.stringOverride`?

https://github.com/airflow-helm/charts/blob/airflow-8.0.9/charts/airflow/values.yaml#L192-L204

**Comment by thesuperzapper** [comment]
@srthok where you still having this issue?
