### ISSUE TITLE
High fluctuation in resource usage, especially with webserver pods

### ISSUE THREAD

**Issue by AlexDHoffer** [airflow-helm/charts#190]
**What is the bug?**

After deploying the Airflow Helm chart, I see a high fluctuation in resource usage from some pods. Especially, the web server pod will go from as low as 3m CPU and 100 Mi to as high as 550m CPU and 1000 Mi. Attempting to place a smaller resource limit of 100m CPU/500 Mi on the webserver pod causes it to be OOM killed.

![image](https://user-images.githubusercontent.com/19369483/116431365-921e7980-a7fc-11eb-9fec-0dd887ead9ca.png)

**What are your Helm values?**

Only default values.

**What is your Kubernetes Version?**:

1.20

**What is your Helm version?**:

3.50

**Comment by thesuperzapper** [comment]
@AlexDHoffer did you ever figure out why this is happening?

**Comment by AlexDHoffer** [comment]
@thesuperzapper I didn't, but no matter what I did with any form of Airflow in Kubernetes it chewed up resources like crazy. Eventually I may return to try it out again but for now the issue is stale because I don't have time to look at it.
