### ISSUE TITLE
External Redis

### ISSUE THREAD

**Issue by manojbalaji1** [airflow-helm/charts#192]
We are planning to use external redis. AWS elasticcahe is something we are evaluating. Since we are planning to use it inside a VPC thus, a password is not required. In the current helm chart, it requires password to be available as secret. Is there a way to avoid using password?

**Comment by thesuperzapper** [comment]
@manojbalaji1 your use-case will work fine, as if `externalRedis.passwordSecret` is empty, no password will be used when connecting to the external redis instance.

I agree that we should document using an external redis, just [like we do for the metadata db](https://github.com/airflow-helm/charts/tree/main/charts/airflow#how-to-use-an-external-database-recommended)

https://github.com/airflow-helm/charts/blob/airflow-8.0.9/charts/airflow/values.yaml#L1485-L1508

**Comment by thesuperzapper** [comment]
I have raised an issue about adding this to the README: https://github.com/airflow-helm/charts/issues/194

**Comment by thesuperzapper** [comment]
Closing in preference of tracking on #194
