### ISSUE TITLE
Would you consider a way to pass in password and extra fields for connections as secrets?

### ISSUE THREAD

**Issue by tinhkyaw** [airflow-helm/charts#195]
**What is your feature request?**

Currently, the password and extra fields for initial connections which often contain sensitive credential information for the connections are added as plain text in `values.yaml`. e.g.:
```
  connections:
    - id: s3_airflow
      type: s3
      extra: |-
        {
          "aws_access_key_id": "XXXXXXXX",
          "aws_secret_access_key": "XXXXXXXX,
          "region_name": "us-west-2"
        }
```
This is a security risk for those who wish to check their `values.yaml` into git.  There used to be a way of adding those connections via a secret key with `add-connections.sh`.  Would you consider providing a way to add those sensitive information as secrets?

**What alternatives have you considered?**

I may be missing something but I do not see a way around this limitation at the moment.

**Comment by hmahmood-slalom** [comment]
@tinhkyaw we're currently requesting the same thing here: https://github.com/airflow-helm/charts/issues/183

**Comment by tinhkyaw** [comment]
Ah, I missed that.

**Comment by tinhkyaw** [comment]
Duplicate of #183
