### ISSUE TITLE
Remote logging to gcs bucket set up 

### ISSUE THREAD

**Issue by gy0ung-git** [airflow-helm/charts#203]
Hello experts, 

I have set up airflow using this chart and it works well. Now, I am trying to set up remote logging and tried to follow directions but it doesn't write to the bucket, it looks like some configuration issue, but can't figure out what's missing. I am quiet new to airflow and gke, so I would appreciate your help on the following. questions. 

1. values.yaml set up 

config:
 # remote log storage
    AIRFLOW__LOGGING__REMOTE_LOGGING: "True"
    AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER: "gs://airflow-logs"
    AIRFLOW__LOGGING__REMOTE_LOG_CONN_ID: "google_cloud_default"

connections:
   - id: google_cloud_default
      type: google_cloud_platform
      description: GCP connection
      extra: |-
        { "extra__google_cloud_platform__num_retries": "3" }

To set up google_cloud_default connection using application default credentials, do we need anything. else?

To use google_cloud_default connection, do we need to install extra pip package in advance?  If so, which ones are required for airflow 2.0.2-python 3.7?  

Thanks a lot for your help in advance.

**Comment by andormarkus** [comment]
Hi @gy0ung-git 

If you are using GCP GKE than please SSH into one of the web server pod and try list you bucket `gsutil ls`.
If you can not list any of the bucket that means your kubernetes service account does not have enough policy or you did not added kubernetes service account for airflow

**Comment by thesuperzapper** [comment]
@gy0ung-git what are you using to provide the GCP access? Are you using [GKE Workload Identity](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity)?

**Comment by gy0ung-git** [comment]
I configured GKE Workload Identity and specified the configuration as follows: 

  config:
    AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL: "60"
    AIRFLOW__CORE__PLUGINS_FOLDER: "/opt/airflow/dags/repo/plugins"
    CLOUDPROVIDER: "google"
  # remote log storage
    AIRFLOW__LOGGING__REMOTE_LOGGING: "True"
    AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER: "gs://g72-bucket/airflow-logs/"
    AIRFLOW__LOGGING__REMOTE_LOG_CONN_ID: "google_cloud_default"

  serviceAccount:
  annotations:
    iam.gke.io/gcp-service-account: "airflow-g72@sap-hcm-plt-dev.iam.gserviceaccount.com"

Question: 
1. Do we need to configure     AIRFLOW__LOGGING__REMOTE_LOG_CONN_ID: "google_cloud_default" ? 
2. To use workload identity, we should create the service account outside of the chart, is that correct? 
3. After installing the chart, I tried to check using "gcloud auth list" but the command was not available in the pods. How can I validate my set up is correct? 

Thanks a lot for your help in advance.

**Comment by thesuperzapper** [comment]
Since this issue was raised, there have been improvements to the ["How to persist airflow logs?"](https://github.com/airflow-helm/charts/tree/main/charts/airflow#how-to-persist-airflow-logs) docs, I will close this issue for now, please reopen it if you still have issues.

**Comment by juliandm** [comment]
> 

Is it expected that gsutil is installed in the pod? it is not installed in my airflow webserver pod. 

> Hi @gy0ung-git
> 
> If you are using GCP GKE than please SSH into one of the web server pod and try list you bucket `gsutil ls`. If you can not list any of the bucket that means your kubernetes service account does not have enough policy or you did not added kubernetes service account for airflow

**Comment by gy0ung-git** [comment]
> 

Hello @juliandm, thank you for your reply. After enabling service account impersonation using workload identity, I was able to make it working. Thanks.
