### ISSUE TITLE
Error: failed post-install: timed out waiting for the condition - on variable creation

### ISSUE THREAD

**Issue by demetrioi** [airflow-helm/charts#204]
Hi all, 

I'm not sure if is bug but basically are occurring only when I try to setup variables or connections

**What is the bug?**

Trying to install the helm I got the following error in my ZHS terminal:

Error: failed post-install: timed out waiting for the condition

And this one in my Azure Kubernetes:

`{
    "kind": "Event",
    "apiVersion": "v1",
    "metadata": {
        "name": "airflow-cluster-scheduler-8f4bd86f6-l285w.167f90e5b12edc28",
        "namespace": "airflow-cluster-namespace",
        "selfLink": "/api/v1/namespaces/airflow-cluster-namespace/events/airflow-cluster-scheduler-8f4bd86f6-l285w.167f90e5b12edc28",
        "uid": "790af9b7-5772-4d4b-a715-1e0d9b9b48fc",
        "resourceVersion": "233374",
        "creationTimestamp": "2021-05-16T14:01:47Z",
        "managedFields": [
            {
                "manager": "kubelet",
                "operation": "Update",
                "apiVersion": "v1",
                "time": "2021-05-16T14:01:47Z",
                "fieldsType": "FieldsV1",
                "fieldsV1": {
                    "f:count": {},
                    "f:firstTimestamp": {},
                    "f:involvedObject": {
                        "f:apiVersion": {},
                        "f:fieldPath": {},
                        "f:kind": {},
                        "f:name": {},
                        "f:namespace": {},
                        "f:resourceVersion": {},
                        "f:uid": {}
                    },
                    "f:lastTimestamp": {},
                    "f:message": {},
                    "f:reason": {},
                    "f:source": {
                        "f:component": {},
                        "f:host": {}
                    },
                    "f:type": {}
                }
            }
        ]
    },
    "involvedObject": {
        "kind": "Pod",
        "namespace": "airflow-cluster-namespace",
        "name": "airflow-cluster-scheduler-8f4bd86f6-l285w",
        "uid": "ab181e23-c77f-4ff4-802b-3355faf184f9",
        "apiVersion": "v1",
        "resourceVersion": "232325",
        "fieldPath": "spec.containers{dags-git-sync}"
    },
    "reason": "BackOff",
    "message": "Back-off restarting failed container",
    "source": {
        "component": "kubelet",
        "host": "aks-agentpool-28188663-vmss000001"
    },
    "firstTimestamp": "2021-05-16T14:01:47Z",
    "lastTimestamp": "2021-05-16T14:05:55Z",
    "count": 21,
    "type": "Warning",
    "eventTime": null,
    "reportingComponent": "",
    "reportingInstance": ""
}`

The error just happen when I try to add any variable or connection in the values file. See below.

**What are your Helm values?**

Any relevant parts of your `custom_values.yaml`

`  variables:
    - key: "environment"
      value: "prod"
`

**What is your Kubernetes Version?**:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.9", GitCommit:"6c90dbd9d6bb1ae8a4c0b0778752be06873e7c55", GitTreeState:"clean", BuildDate:"2021-03-22T23:02:49Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}```

1.19.9

**What is your Helm version?**:

```console
$ helm version
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"dirty", GoVersion:"go1.16.3"}```

**Comment by thesuperzapper** [comment]
@demetrioi If you are using `helm install --wait`, please enable the `helmWait` value:
https://github.com/airflow-helm/charts/blob/main/charts/airflow/values.yaml#L1-L3

**Comment by thesuperzapper** [comment]
@demetrioi this should have been fixed by PR: https://github.com/airflow-helm/charts/pull/266, which will be in the next release of the chart `8.4.0`, (you can follow which version has it in the [CHANGELOG](https://github.com/airflow-helm/charts/blob/main/charts/airflow/CHANGELOG.md)).

**Comment by demetrioi** [comment]
Thanks @thesuperzapper yes it's solved.

**Comment by jkryanchou** [comment]
Oh God. I try many times with `--wait` it always failed while I remove the `--wait` flag it works. I spent a lot time to figure it out what's wrong with it. Finally got the answer here.
I suggest that you'd better note the `--wait` flag could result in failed in the documentation. or else other one may meet same issue again.

**Comment by thesuperzapper** [comment]
> Oh God. I try many times with `--wait` it always failed while I remove the `--wait` flag it works. I spent a lot time to figure it out what's wrong with it. Finally got the answer here. I suggest that you'd better note the `--wait` flag could result in failed in the documentation. or else other one may meet same issue again.

@jkryanchou this is a community project, if you have an idea to improve it, please raise a PR.
