### ISSUE TITLE
Cannot get worker pod's log 

### ISSUE THREAD

**Issue by socar-grab** [airflow-helm/charts#206]
**What is your question?**
I cannot worker pod's log on the webserver.
it just show me the below error. how configurations of values.yaml should I check?
helm chart version : 8.1.0, airflow images tag : 2.0.2
Thank you in advance

*** Unable to fetch logs from worker pod tutorialprintdate.c8182c57094b4fe182e3d7c41b298099 ***
(404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Audit-Id': '7fa1fdff-c693-4d96-8e0b-a7cf032b884e', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Date': 'Tue, 18 May 2021 11:13:03 GMT', 'Content-Length': '268'})
HTTP response body: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods \\"tutorialprintdate.c8182c57094b4fe182e3d7c41b298099\\" not found","reason":"NotFound","details":{"name":"tutorialprintdate.c8182c57094b4fe182e3d7c41b298099","kind":"pods"},"code":404}\n'

**Comment by andormarkus** [comment]
Hi @socar-grab 
Are you using Kubernetes or Celery executor?
If you are using Kubernetes executer once the task is finished the pod will be terminated and the logs will be gone.

You have two choice:
1. Writing a log to Kubernetes persistent volume
2. Write logs to remote server like S3, CloudWatch logs, Elasticsearch...

[How to persist Airflow logs?](https://artifacthub.io/packages/helm/airflow-helm/airflow#how-to-persist-airflow-logs-recommended)

We are using AWS I can give more help on that ecosystem.

**Comment by socar-grab** [comment]
> Hi @socar-grab
> Are you using Kubernetes or Celery executor?
> If you are using Kubernetes executer once the task is finished the pod will be terminated and the logs will be gone.
> 
> You have two choice:
> 
> 1. Writing a log to Kubernetes persistent volume
> 2. Write logs to remote server like S3, CloudWatch logs, Elasticsearch...
> 
> [How to persist Airflow logs?](https://artifacthub.io/packages/helm/airflow-helm/airflow#how-to-persist-airflow-logs-recommended)
> 
> We are using AWS I can give more help on that ecosystem.

Thank you! I solved.

**Comment by msimak-hf** [comment]
Hello @socar-grab , how did you solve this issue?
