### ISSUE TITLE
Pools documentation on artifacthub

### ISSUE THREAD

**Issue by andormarkus** [airflow-helm/charts#207]
Hi

There is typo in pools documentation on artifacthub:

![Screenshot 2021-05-19 at 11 03 06](https://user-images.githubusercontent.com/51825189/118786208-df3cbb00-b891-11eb-816f-5041eedf973b.png)

It is referring to: 
```yaml
airflow:
  variables:
```

Correct would be
```yaml
airflow:
  pools:
```

**Comment by thesuperzapper** [comment]
@andormarkus thanks for spotting this!

The issue is actually in the main README.md: 
https://github.com/airflow-helm/charts/tree/main/charts/airflow#how-to-create-airflow-pools
