### ISSUE TITLE
Line break doesn't work in webserver log view

### ISSUE THREAD

**Issue by socar-grab** [airflow-helm/charts#209]
**What is the bug?**
![image](https://user-images.githubusercontent.com/83575607/118948957-c0265200-b993-11eb-908b-fe2443044336.png)

Line break doesn't work in Task logs
It shows just new line escape character(\n') and not show line break.

**What are your Helm values?**
airflow image tag : 2.0.1-python3.8
no custom configurations about webserver log

**What is your Kubernetes Version?**:
1.21.0

**What is your Helm version?**:
3.5.4

**Comment by DylanCuure** [comment]
I have the exact same issue. If I open the logs directly from GCS they have the right format but from the Airflow UI, no line break is shown.

**Comment by jensgrnb** [comment]
I added this and the newline problem disappeared for us:

  extraPipPackages:
    - "apache-airflow-providers-google~=3.0.0"
