### ISSUE TITLE
Installing requirements on Kubernetes workers

### ISSUE THREAD

**Issue by chris-vest** [airflow-helm/charts#21]
**What is your feature request?**

Currently `installRequirements` only applies to the web and scheduler pods, however when using the Kubernetes executor you need to pre-bake the pip dependencies in order to run your DAGs.

**What alternatives have you considered?**

1. Baking in DAGs (developer experience kind of sucks)
2. Overriding the `args` on the Kubernetes executor worker pod to first run a script to install the requirements; this would also require mounting the `requirements.txt` file - this could be done in the same way as the web and scheduler pods

**Notes**

This issue is mostly to start a discussion around this, I'm sure others are facing the same limitation. I also don't think this is an issue with the Chart as such, so am keen to find out if Airflow already has the ability to do this.

**Comment by thesuperzapper** [comment]
I can't see a way to have default pip dependancies appear in the worker pods spawned by KubernetesExecutor, (and you wouldn't want to, the whole point is that you use a container image with exactly what you need).

Airflow lets you specify the container image with `executor_config` config of BaseOperator:
```python
MyOperator(...,
    executor_config={
    "KubernetesExecutor":
        {"image": "myCustomDockerImage"}
    }
)
```

**Comment by chris-vest** [comment]
> I can't see a way to have default pip dependancies appear in the worker pods spawned by KubernetesExecutor, (and you wouldn't want to, the whole point is that you use a container image with exactly what you need).
> 
> Airflow lets you specify the container image with `executor_config` config of BaseOperator:
> 
> ```python
> MyOperator(...,
>     executor_config={
>     "KubernetesExecutor":
>         {"image": "myCustomDockerImage"}
>     }
> )
> ```

This is a good point! Thanks for this.
