### ISSUE TITLE
Support setting environment variables in variables.yaml from secrets and config maps

### ISSUE THREAD

**Issue by ihormudryy** [airflow-helm/charts#219]
I would like to request support of secrets in the environment variables set:
Currently, it's possible to set only string value to the key:
`- key: "var_1"
    value: "my_value_1"`

Nice to have:
`variables:
    - name: var_1
      valueFrom:
         secretKeyRef:
            key: var-1-secret
            name: some-secrets`

When I do it now I get error:
`Error: execution error at (airflow/templates/jobs/secret-job-scripts.yaml:255:16): each `value` in `airflow.variables` must be non-empty!`

**Comment by thesuperzapper** [comment]
@ihormudryy I have made a proposal to do something similar to this in: https://github.com/airflow-helm/charts/issues/260

I am working on implementing it now.

**Comment by thesuperzapper** [comment]
I am going to close this in preference of tracking it on: https://github.com/airflow-helm/charts/issues/260
