### ISSUE TITLE
allow using the redis for celery result_backend

### ISSUE THREAD

**Issue by enrique-ayala** [airflow-helm/charts#233]
I would like to set redis as a result_backend , however I can see that `DATABASE_CELERY_CMD` only works with db . Is there any workaround to it? 

The reason of using redis for result_backend is because there are many idle connections on postgres from workers (presumably because of db as backend), causing : 
```sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL: sorry, too many clients already```

**Comment by thesuperzapper** [comment]
This is related to https://github.com/airflow-helm/charts/issues/227 (in the sense of `sorry, too many clients already`)

But it wouldn't be too hard to implement a flag like `workers.redisForCeleryResultBackend` to allow using use the existing `redis.*` or `externalRedis.*` settings with `AIRFLOW__CELERY__RESULT_BACKEND_CMD`:

```yaml
  AIRFLOW__CELERY__RESULT_BACKEND_CMD: |-
    {{- if .Values.workers.redisForCeleryResultBackend }}
    bash -c 'eval "$REDIS_CONNECTION_CMD"'
    {{- else }}
    bash -c 'eval "$DATABASE_CELERY_CMD"'
    {{ end }}
```

@enriqueayala we can obviously do this in a minor (`8.X.0`) release of the chart ASAP, but the question is, should we make this default for the eventual major (`9.0.0`) release of the chart?

**Comment by enriqueayala** [comment]
Thanks for the reference, PgBounce should definetely help. Regarding `workers.redisForCeleryResultBackend` it would be great to have it by default for next major release.
