### ISSUE TITLE
implement pgbouncer (prevent "too many connections" errors)

### ISSUE THREAD

**Issue by thesuperzapper** [airflow-helm/charts#235]
Currently, there are issues when users have large number of tasks, leading to "too many connections" to their Postgres database:
- https://github.com/airflow-helm/charts/issues/227
- https://github.com/airflow-helm/charts/issues/233

We can reduce this load for Postgres by implementing [PgBouncer](https://www.pgbouncer.org/features.html), rather than directly having each task/worker/scheduler access the Postgres, we can relay them through a PgBouncer deployment.

_NOTE: I don't believe such pooling is nessesary for MySQL, so we can probably just leave the MySQL connection flow as is._

**Comment by javad87** [comment]
Hi @thesuperzapper;


I'm using airflow 2.3.3 with docker-compose deployment, I have 3 Dags running everyday from morning till midnight with 1, 25,25  active tasks per dag with respect to these running 3 Dags (overall 51 active tasks in airflow instance ). after running for one day I get the postgres too many connections" errors....I checked the postgres container and  "show max_connections" and it has large I guess its value is max_int number...and I changed and increased airflow.cfg parameteres related to DB and number of parallel task running....


executor = LocalExecutor
parallelism = 200

DB params:

sql_alchemy_conn = sqlite:////opt/airflow/airflow.db    
default_pool_task_slot_count = 128
sql_alchemy_pool_enabled = True
sql_alchemy_pool_size = 0
sql_alchemy_max_overflow = -1
sql_alchemy_pool_recycle = 1800
max_active_tasks_per_dag = 25
max_active_runs_per_dag = 5

what should I change to have pgbouncer manage number of connections?

tnx in advance;
Javad
