### ISSUE TITLE
document how to use airflow plugins

### ISSUE THREAD

**Issue by thesuperzapper** [airflow-helm/charts#252]
Currently, users have to figure out how to add airflow plugins to this chart, we should add a new FAQ called `How to use airflow plugins?`.

There are a few ways off the top of my head that we should include:
1. Store plugins in your DAGs repo, and use git-sync:
    - Then set `AIRFLOW__CORE__PLUGINS_FOLDER = /opt/airflow/dags/repo/PATH_TO_PLUGINS`
2. Embed them in your Airflow container image under:
    - Storing them under `/home/airflow/plugins`
3. Store them in a PVC:
    - And mount them with `airflow.extraVolumeMounts` and `airflow.extraVolumes`
    - Then set `AIRFLOW__CORE__PLUGINS_FOLDER` to the mount point.
4. Store them in Secrets/Configmaps:
    - And mount them with `airflow.extraVolumeMounts` and `airflow.extraVolumes`
    - Then set `AIRFLOW__CORE__PLUGINS_FOLDER` to the mount point.

**Comment by thesuperzapper** [comment]
Bumping for the bot, this is still a good idea.

**Comment by thesuperzapper** [comment]
Bumping for bot.

**Comment by Recio** [comment]
Just wanted to say that this helped me out a bunch, thanks @thesuperzapper 👍

**Comment by thesuperzapper** [comment]
@Recio lol, do you want to update the main readme with this information so others can find it easier than looking through the issues?

**Comment by thesuperzapper** [comment]
This issue has been resolved, we now have a slick new FAQ page called [`How to load airflow plugins?`](https://github.com/airflow-helm/charts/blob/main/charts/airflow/docs/faq/configuration/airflow-plugins.md).
