### ISSUE TITLE
Encrypt sql_alchemy_conn in airflow config file

### ISSUE THREAD

**Issue by KIRY4** [airflow-helm/charts#256]
**What is your feature request?**

Hello. If you execute following command using airflow CLI: airflow info -v
You will get following output:
airflow@airflow-web-7c8847fdf8-8gdsl:/opt/airflow$ airflow info -v

Apache Airflow
sql_alchemy_conn       | postgresql+psycopg2://airflow:PLAINTEXTPASSWORD@DB_HOST:6432/airflow
Is it possible to avoid plain text in this string? 

**What alternatives have you considered?**

https://airflow.apache.org/docs/apache-airflow/stable/howto/set-config.html - according documentation I can hide more or less this password using: 
1) set as an environment variable (AIRFLOW__CORE__SQL_ALCHEMY_CONN)
2) set as a command environment variable (AIRFLOW__CORE__SQL_ALCHEMY_CONN_CMD)

But when I'm try to use helm upgrade I'm getting following message:
Error: UPGRADE FAILED: execution error at (airflow/templates/_helpers/validate-values.tpl:61:5): Don't define `airflow.config.AIRFLOW__CORE__SQL_ALCHEMY_CONN`, it will be automatically set by the chart!

Looks like I'm not the only one who want to encrypt this password:
https://stackoverflow.com/questions/56694288/envrypt-sql-alchemy-conn-in-airflow-config-file-ansible

**Comment by thesuperzapper** [comment]
@KIRY4 the `airflow info` command will always display this connection string (including password), please note, that this chart already [AIRFLOW__CORE__SQL_ALCHEMY_CONN_CMD to set the connection string](https://github.com/airflow-helm/charts/blob/airflow-8.3.2/charts/airflow/templates/config/secret-config.yaml#L89-L90), see also [how we define DATABASE_SQLALCHEMY_CMD](https://github.com/airflow-helm/charts/blob/airflow-8.3.2/charts/airflow/templates/config/secret-config.yaml#L16-L55).

@potiuk, should we make the default behaviour of `airflow info` to XXX out the `sql_alchemy_conn` password? (I see there is a ` --anonymize` flag, but this is not default)

**Comment by thesuperzapper** [comment]
Since this is not an issue, I will close.
