### ISSUE TITLE
Add extra volume mounts on worker pods

### ISSUE THREAD

**Issue by kirancodify** [airflow-helm/charts#27]
**How do we add extra volume mounts onto worker pods**

I have to add additional volumes on to the worker pods that are spun up by Kubernetes executor. Although the comments in the values file suggest we can do this with the following configs:
```
  extraVolumeMounts:
  extraVolumes:
```
These are only working for the scheduler and the webserver pod and the worker pod doesn't have the extra volume mount when the task runs. I have the plugins required for dag run as a different volume claim and the dag fails to run as the plugins are not found. 

The config is not working as mentioned in the comments of the values.yaml file. Is there any other way to achieve this. Looking forward for any inputs.

**Comment by marcinmilewski1** [comment]
Yeah, this will be very useful

**Comment by thesuperzapper** [comment]
The `airflow.extraVolumeMounts` value only work for `CeleryExecutor`, if you want to mount volumes to task pods while using `KubernetesExecutor`, you will need to specify it for each operator. (This is desirable, as you probably dont want all your Pods mounting the same volumes).

__For example, with PythonOperator:__

```python
PythonOperator(
  ...
  executor_config={
    "KubernetesExecutor": {
      "volumes": [
        {
          "name": "my-volume",
          "persistentVolumeClaim":
            {
              "claimName": "my-existing-pvc"
            }
        }
      ],
      "volume_mounts": [
        {
          "name": "my-volume",
          "mountPath": "/usr/local/tmp"
        }
      ]
    }
  }
)
```

**Comment by kirancodify** [comment]
I was more concerned about the plugins folder. This is not being mounted onto the worker pods which is also a PV in my case. I agree your method works for individual dags. But any suggestions on plugins ?

**Comment by thesuperzapper** [comment]
@kirancodify, you could probably use the `AIRFLOW__KUBERNTES__POD_TEMPLATE_FILE` config, see here:
https://github.com/apache/airflow/blob/master/docs/apache-airflow/executor/kubernetes.rst#pod_template_file
