### ISSUE TITLE
Workaround found for: Unable to attach or mount volumes mount.nfs Connection timed out

### ISSUE THREAD

**Issue by epmccormick** [airflow-helm/charts#28]
**What is the bug?**

@thesuperzapper (Mathew Wicks) suggested I post the workaround that I found for this EFS problem I experienced setting up my PV/PVC for AirFlow. This is not an issue with AirFlow itself, it was a Persistent Volume issue that should work but did not. Please close this bug as the intention here is to be a source of documentation to anyone who might experience this same issue and would like to find a working solution.

When I specified a `path:` other than "/" in the PersistentVolume manifest, K8s failed to mount the volume to the AirFlow web and scheduler pods with this message:

```Warning  FailedMount  118s  kubelet, ip-10-4-4-44.ec2.internal  Unable to attach or mount volumes:
 unmounted volumes=[k8s-cluster-dev], unattached volumes=[scripts k8s-cluster-dev airflow-devops-test-token-7bq9s]:
 timed out waiting for the condition
 
Warning  FailedMount  109s  kubelet, ip-10-4-4-44.ec2.internal  MountVolume.SetUp failed for volume "k8s-cluster-dev-efs-airflow-devops-test" :
 mount failed: exit status 32
Mounting command: systemd-run
Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/xxxxxx-0d08-4b4f-b2e6-f97971d9dbd0/volumes/kubernetes.io~nfs/k8s-cluster-dev-efs-airflow-devops-test --scope -- mount -t nfs fs-xxxxxxxx.efs.us-x-x.amazonaws.com:/dev.q-internal.tech/airflow-devops-test /var/lib/kubelet/pods/528f6475-0d08-4b4f-b2e6-f97971d9dbd0/volumes/kubernetes.io~nfs/k8s-cluster-dev-efs-airflow-devops-test
Output: Running scope as unit run-28953.scope.
mount.nfs: Connection timed out
```

The PersistentVolume.yaml looks like this (redactions with xxxx here):

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8s-cluster-dev-efs-airflow-devops-test
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: fs-xxxxxxxx.efs.us-x-x.amazonaws.com
    path: "/some/path"
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
```

There was no error from K8s when this manifest was used (with the real server name of course) and it showed Bound, and indeed the PVC could also be Bound to it. But when AirFlow tried to mount the volume, that's when the weird nfs timeout errors occurred. Changing the `path:` on the PV to "/" fixed the issue and allowed the volume to mount to AirFlow.

**What are your Helm values?**

Any relevant parts of your `custom_values.yaml`

```airflow:
  extraVolumeMounts:
    - name: k8s-cluster-dev
      mountPath: /opt/airflow/efs
  extraVolumes:
    - name: k8s-cluster-dev
      persistentVolumeClaim:
        claimName: k8s-cluster-dev-efs-airflow-devops-test
```

**What is your Kubernetes Version?**:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.10", GitCommit:"575467a0eaf3ca1f20eb86215b3bde40a5ae617a", GitTreeState:"clean", BuildDate:"2019-12-11T12:41:00Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.15", GitCommit:"2adc8d7091e89b6e3ca8d048140618ec89b39369", GitTreeState:"clean", BuildDate:"2020-09-02T11:31:21Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**What is your Helm version?**:

```console
$ helm version
version.BuildInfo{Version:"v3.2.4", GitCommit:"0ad800ef43d3b826f31a5ad8dfbb4fe05d143688", GitTreeState:"clean", GoVersion:"go1.13.12"}
```

**Comment by thesuperzapper** [comment]
@epmccormick thanks for putting this info here!

**Comment by chuyuou** [comment]
Hello, I got this error when trying to mount an existing pv to airflow on gke:
```
Events:
  Type     Reason       Age    From                                             Message
  ----     ------       ----   ----                                             -------
  Normal   Scheduled    2m59s  default-scheduler                                Successfully assigned airflow-dev/apache-airflow-release-scheduler-89cdfdc76-66pnx to gke-airflow-default-pool-4c9482d6-8fmf
  Warning  FailedMount  56s    kubelet, gke-airflow-default-pool-4c9482d6-8fmf  MountVolume.SetUp failed for volume "nfs-airflow" : mount failed: exit status 1
Mounting command: /home/kubernetes/containerized_mounter/mounter
Mounting arguments: mount -t nfs 10.56.10.191:/ /var/lib/kubelet/pods/1bef6888-3ea9-43d6-bbb2-034a330daa73/volumes/kubernetes.io~nfs/nfs-airflow
Output: Mount failed: mount failed: exit status 32
Mounting command: chroot
Mounting arguments: [/home/kubernetes/containerized_mounter/rootfs mount -t nfs 10.56.10.191:/ /var/lib/kubelet/pods/1bef6888-3ea9-43d6-bbb2-034a330daa73/volumes/kubernetes.io~nfs/nfs-airflow]
Output: mount.nfs: Connection timed out
  Warning  FailedMount  56s  kubelet, gke-airflow-default-pool-4c9482d6-8fmf  Unable to attach or mount volumes: unmounted volumes=[logs], unattached volumes=[apache-airflow-release-scheduler-token-5zlxt config logs]: timed out waiting for the condition
```
Is it relevant with this issue?  Could find the way to work around yet.

**Comment by caxefaizan** [comment]
> Hello, I got this error when trying to mount an existing pv to airflow on gke:
> 
> ```
> Events:
>   Type     Reason       Age    From                                             Message
>   ----     ------       ----   ----                                             -------
>   Normal   Scheduled    2m59s  default-scheduler                                Successfully assigned airflow-dev/apache-airflow-release-scheduler-89cdfdc76-66pnx to gke-airflow-default-pool-4c9482d6-8fmf
>   Warning  FailedMount  56s    kubelet, gke-airflow-default-pool-4c9482d6-8fmf  MountVolume.SetUp failed for volume "nfs-airflow" : mount failed: exit status 1
> Mounting command: /home/kubernetes/containerized_mounter/mounter
> Mounting arguments: mount -t nfs 10.56.10.191:/ /var/lib/kubelet/pods/1bef6888-3ea9-43d6-bbb2-034a330daa73/volumes/kubernetes.io~nfs/nfs-airflow
> Output: Mount failed: mount failed: exit status 32
> Mounting command: chroot
> Mounting arguments: [/home/kubernetes/containerized_mounter/rootfs mount -t nfs 10.56.10.191:/ /var/lib/kubelet/pods/1bef6888-3ea9-43d6-bbb2-034a330daa73/volumes/kubernetes.io~nfs/nfs-airflow]
> Output: mount.nfs: Connection timed out
>   Warning  FailedMount  56s  kubelet, gke-airflow-default-pool-4c9482d6-8fmf  Unable to attach or mount volumes: unmounted volumes=[logs], unattached volumes=[apache-airflow-release-scheduler-token-5zlxt config logs]: timed out waiting for the condition
> ```
> 
> Is it relevant with this issue? Could find the way to work around yet.

did you find the solution. im facing the same in AWS EKS

**Comment by caxefaizan** [comment]
> 

Thats great. How did you do it?

**Comment by chuyuou** [comment]
Would it be possible for a GKE to use EFS for persistent volume? My cluster needs to be in google.

**Comment by dylac** [comment]
> > did you find the solution. im facing the same in AWS EKS, my manifest has path set as "/".
> > I am trying to use the same efs for both dags and logs persistence. It was working fine with just dag persistence. Any ideas?
> 
> Have you solved this? If not, just got EKS with dags+logs persistence on EFS working, so may try to help.

Still curious on this; dags sync fine, but as soon as I try logs most containers are in permanent backoff and retry, with no other logs as to why.

**Comment by caxefaizan** [comment]
> > > did you find the solution. im facing the same in AWS EKS, my manifest has path set as "/".
> > > I am trying to use the same efs for both dags and logs persistence. It was working fine with just dag persistence. Any ideas?
> > 
> > 
> > Have you solved this? If not, just got EKS with dags+logs persistence on EFS working, so may try to help.
> 
> Still curious on this; dags sync fine, but as soon as I try logs most containers are in permanent backoff and retry, with no other logs as to why.

Nah!! It didn't support the same EFS. So i had used two volumes separately

**Comment by jkryanchou** [comment]
> > > did you find the solution. im facing the same in AWS EKS, my manifest has path set as "/".
> > > I am trying to use the same efs for both dags and logs persistence. It was working fine with just dag persistence. Any ideas?
> > 
> > 
> > Have you solved this? If not, just got EKS with dags+logs persistence on EFS working, so may try to help.
> 
> Still curious on this; dags sync fine, but as soon as I try logs most containers are in permanent backoff and retry, with no other logs as to why.

I have met the same issue like what you mentioned above. no solution for it now. .... Terrible
