### ISSUE TITLE
Where to find the documentation of this chart ?

### ISSUE THREAD

**Issue by harvetech** [airflow-helm/charts#306]
I am new to Kubernetes and I was able to deploy Airflow via this helm chart. Everything is working smoothly as expected thanks to the creators of this chart. But now I want to pull dags and I don't want them to be pulled each time and want to store them separately in a different volume. These are the basic question to which I hope I will get an answer from the documentation. 

Where is the documentation of this chart? is it in there as comments or is it separately managed somewhere else? also where I can get the configuration of my airflow?

Best Regards
Ali

**Comment by thesuperzapper** [comment]
@harvetech all the documentation is stored in the [README](https://github.com/airflow-helm/charts/tree/main/charts/airflow),  the questions you ask are in the FAQ:
- [How to set airflow configs?](https://github.com/airflow-helm/charts/tree/main/charts/airflow#how-to-set-airflow-configs)
- [How to store DAGs?](https://github.com/airflow-helm/charts/tree/main/charts/airflow#how-to-store-dags)

**Comment by harvetech** [comment]
Thankyou @thesuperzapper
