### ISSUE TITLE
extraPipPackages config not installing package dependencies on celeryExecutor worker 

### ISSUE THREAD

**Issue by ecda909** [airflow-helm/charts#308]
**What is your question?**

I'm trying to install pip packages via the extraPipPackages config in the values manifest for the celeryExecutor worker, but I keep getting this error when trying to install pandas...
<img width="1231" alt="Screen Shot 2021-07-14 at 3 31 30 PM" src="https://user-images.githubusercontent.com/20650573/125681771-db9d0bf0-859f-409d-8ebd-4fb6abbcabfc.png">

and my values manifest config looks like this?

<img width="673" alt="Screen Shot 2021-07-14 at 3 31 52 PM" src="https://user-images.githubusercontent.com/20650573/125681833-25663749-95a2-4383-8a5a-0944c79ee7c8.png">

**Comment by thesuperzapper** [comment]
@ecda909

Where are those logs from? Are they from the `install-pip-packages` init-container or the main `worker` container?

Also, I highly recommend for larger python dependencies with C code (like numpy), that you use "Option 2" and build your own image, as [described here](https://github.com/airflow-helm/charts/tree/main/charts/airflow#option-1---use-init-containers).

**Comment by ecda909** [comment]
These are from the Airflow dag logs in the dashboard. They're also present on the worker container. I didn't look at the init-container logs, however I know they ran because the packages are installed at /opt/python/site-packages...
<img width="1394" alt="Screen Shot 2021-07-15 at 9 49 04 AM" src="https://user-images.githubusercontent.com/20650573/125799034-0ddd7c66-8c84-49c3-a753-6f5cca49ab6b.png">

**Comment by ecda909** [comment]
I don't see the instructions for how to build a separate image... I can build one, but it will take significantly more time with troubleshooting Airflow to get it to work with the image if there isn't clear instruction available on the steps that need to be taken.

**Comment by ecda909** [comment]
I go the dependencies to work. I had to manually uninstall and reinstall them from that directory and then the DAG began to run. But now I'm having an issue with my logs... The transform_script logs are supposed to be in this directory 
<img width="1105" alt="Screen Shot 2021-07-15 at 12 26 15 PM" src="https://user-images.githubusercontent.com/20650573/125823363-878f5575-77d1-4650-959e-acdc59463032.png">

But when I go into my worker pod, that directory does not exist? 
<img width="445" alt="Screen Shot 2021-07-15 at 12 27 52 PM" src="https://user-images.githubusercontent.com/20650573/125823586-a9183fa8-a709-4e90-98dc-9171b788e091.png">

Is this expected? How do I make the log data persist? This may be a separate issue...

**Comment by ecda909** [comment]
I found that the log file is being placed in the /tmp file for a limited time, but it is empty...

**Comment by thesuperzapper** [comment]
@ecda909 just to clarify, what version of the chart are you using, because `extraPipPackages` should be installed in `/home/airflow/.local/` not `/opt/python/site-packages`?
