### ISSUE TITLE
Git Sync image k8s.gcr.io/git-sync/git-sync 

### ISSUE THREAD

**Issue by harvetech** [airflow-helm/charts#309]
Dear all, 

I am trying to pull this image but this URL leads me to google cloud and that's where I have signup and pay to use this image. Do we have another image that is available on the docker hub? 

The cluster am using cannot download images from the internet. I have to download and upload in the Image repository. All Images I found on docker hub but not this one. 

repository: k8s.gcr.io/git-sync/git-sync
tag: v3.2.2

can you please guide me from where I should get the image? 

Thankyou

**Comment by thesuperzapper** [comment]
@harvetech I believe that the git-sync image ([repo here](https://github.com/kubernetes/git-sync)) is only officially available on `k8s.gcr.io/git-sync/git-sync`.

However, you could easily just `docker pull ...`, `docker tag ...`, `docker push ...` it to your own docker-hub or internal repo (from a machine with access to the internet).
