### ISSUE TITLE
helm template generates manifests without namespace

### ISSUE THREAD

**Issue by jacekn** [airflow-helm/charts#31]
**What is the bug?**

When used with `helm template` like this:
```
helm template airflow airflow-stable/airflow -f custom_values.yaml --namespace=airflow
```

The chart will generate manifests that, for the most part, don't contain `namespace:` key (`RoleBinding` is the only one I can see that will contain namespace).

This is problematic because `helm template | kubectl apply -f -` will result in a different state than `helm install` whcih can be surprising to users.

**What are your Helm values?**

This happens even without custom_values

**What is your Helm version?**:

```console
$ helm version
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}

```

**Other**

Fix for this can be to include the following in all templates:
```
namespace: {{ .Release.Namespace }}
```

**Comment by thesuperzapper** [comment]
I am inclined to agree with @bacongobbler (a core maintainer of helm) in his comment: https://github.com/helm/helm/issues/5465#issuecomment-473942223. His idea is that we shouldn't create a situation where users have to use the same namespace in `helm template` and `kubectl apply`.

The current state of this chart should allow you to use: `helm template | kubectl create --namespace foo -f -`

However, I am not 100% sure this will work properly because `{{ .Release.Namespace }}` is included in [rbac/airflow-rolebinding.yaml#L18](https://github.com/airflow-helm/charts/blob/airflow-7.14.3/charts/airflow/templates/rbac/airflow-rolebinding.yaml#L18), meaning `helm template` will reference Role objects in the `default` namespace.

I'm not sure if there is something we can do about this?

---

However, I believe you should deploy things on Kubernetes (including this chart) with a tool like [Argo-CD](https://argoproj.github.io/argo-cd/), which does not have this issue.

**Comment by jacekn** [comment]
Thanks for looking into this!

> I am inclined to agree with @bacongobbler (a core maintainer of helm) in his comment: [helm/helm#5465 (comment)](https://github.com/helm/helm/issues/5465#issuecomment-473942223). His idea is that we shouldn't create a situation where users have to use the same namespace in `helm template` and `kubectl apply`.

I agree, I think you shouldn't have to provide namespace to `kubectl apply` if you use helm. To ensure that many charts use `namespace: {{.Release.Namespace}}` in templates. This method also fixes inconsistency where state resulting from `helm install --namespace X` differs from `helm template --namespace X` output.
If you look at the issue you linked many PRs that mention it actually implemented `namespace: {{.Release.Namespace}}` method.

> The current state of this chart should allow you to use: `helm template | kubectl create --namespace foo -f -`
> 
> However, I am not 100% sure this will work properly because `{{ .Release.Namespace }}` is included in [rbac/airflow-rolebinding.yaml#L18](https://github.com/airflow-helm/charts/blob/airflow-7.14.3/charts/airflow/templates/rbac/airflow-rolebinding.yaml#L18), meaning `helm template` will reference Role objects in the `default` namespace.

Yes you're right things will break unless you explicitly use `--namespace` parameter for both helm template and kubectl apply.

> I'm not sure if there is something we can do about this?

We can fix this by including `namespace: {{.Release.Namespace}}` in all templates. This is a very simple and low risk change, many charts do exactly that.
An alternative solution used by some charts is to set namespace in the values file and include that in the templates.

If you're OK with one of the solutions I'd be happy to submit a PR.

> However, I believe you should deploy things on Kubernetes (including this chart) with a tool like [Argo-CD](https://argoproj.github.io/argo-cd/), which does not have this issue.

Yes I do use gitops tooling for deployments but some tools are still affected by this problem.

**Comment by jacekn** [comment]
This is still the case. I'd be happy to submit PR if the project is OK with using the `namespace: {{.Release.Namespace}}` workaround

**Comment by thesuperzapper** [comment]
@jacekn since the current state isn't really breaking anything, and the author of helm doesn't intend namespaces to be hard coded, I don't see a reason to change it.

Unless there is something which is broken as a result?

**Comment by jacekn** [comment]
> @jacekn since the current state isn't really breaking anything, and the author of helm doesn't intend namespaces to be hard coded, I don't see a reason to change it.
> 
> Unless there is something which is broken as a result?

The problem does not affect everyone but the chart is currently broken for some use cases.

If somebody runs `helm template --namespace mynamespace | kubectl apply` they end up with broken airflow. That's because RoleBinding will refer to the ServiceAccount in the `mynamespace` but the ServiceAccount and other resources will actually be deployed to the default namespace specified in the kubeconfig.

Those using tools like flux v1 (gitops) to apply k8s manifests have to use `helm template` with `--namespace` and then manually edit manifests to add namespace to each resource.

Impact of above is reduced usability. I understand that ideally best practices should be followed closely but in this case that reduces usability of the chart. From what I can see it's quite common for charts to include namespace in manifests. In the stable chart repo 149 out of 282 charts do that so it's certainly very common approach.
