### ISSUE TITLE
install `airflow.extraPipPackages` in sync Jobs/Deployments

### ISSUE THREAD

**Issue by ssalaues** [airflow-helm/charts#310]
**What is the bug?**
Similar to #254, certain airflow config options require additional pip packages to function properly such as Sentry. For example, if the airflow Sentry options are enabled then the `check-db` init container on the sync jobs/deployments will fail due do missing the missing `sentry_sdk` package.

**What version of the chart are you using?**:

I am using version `8.4.1`

**What is your Kubernetes Version?**:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.8-eks-96780e", GitCommit:"96780e1b30acbf0a52c38b6030d7853e575bcdf3", GitTreeState:"clean", BuildDate:"2021-03-10T21:32:29Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

**What is your Helm version?**:

```console
$ helm version
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"dirty", GoVersion:"go1.15.4"}
```

**Please copy your custom Helm values file:**

```yaml
airflow:
  config:
    AIRFLOW__SENTRY__SENTRY_ON: "true"
    AIRFLOW__SENTRY__SENTRY_DSN: https://<sentry-url>
    SENTRY_ENVIRONMENT: test-env
  executor: CeleryExecutor
  extraPipPackages:
    - "apache-airflow[sentry]"
```

**Comment by thesuperzapper** [comment]
@ssalaues while I do think you should use "Option 2" for prod, as described in "[How to install extra pip packages?](https://github.com/airflow-helm/charts/tree/main/charts/airflow#how-to-install-extra-pip-packages)", I agree that we can simply add the global `extraPipPackages` to the sync containers.

**Comment by ssalaues** [comment]
Yeah I agree `Option 2` is optimal for various reasons but seemed like an easy unlock for testing fringe airflow features
