### ISSUE TITLE
include `airflow.extraVolumeMounts` in `install-pip-packages` init-container

### ISSUE THREAD

**Issue by naturalett** [airflow-helm/charts#321]
**What is your feature request?**
Currently, it's not possible to add a custom volume to install-pip-packages.
Other init-containers such as **wait-for-db-migrations**, and **check-db** allow custom volumes based on user demands.

**What alternatives have you considered?**
Adding extraVolume to the **install-pip-packages** will give the flexibility for users to add their custom volumes to their initialize init-container.

Related PR: [init-container-with-extra-mount](https://github.com/airflow-helm/charts/pull/295)

**Comment by thesuperzapper** [comment]
As discussed in https://github.com/airflow-helm/charts/pull/295#issuecomment-896503297, this feature is no longer needed after PR https://github.com/airflow-helm/charts/pull/365
