### ISSUE TITLE
Deployment to clean namespace fails when using embedded DAGs in Docker image

### ISSUE THREAD

**Issue by MarvinSchenkel** [airflow-helm/charts#335]
**What is the bug?**

Hi,

I think I found a bug in the chart when using 'Option 3 - embedded into container image' as my DAG deployment method. Let me try to describe what is going on.

I am currently deploying Airflow 2 locally to a minikube cluster as a preparation for the migration to Airflow 2. I already migrated all the DAG code according to the Airflow guides. Whenever I deploy my release to a brand new namespace, the `airflow-local-db-xxxx` pod keeps Crashing (CrashLoopBackOff). When I connect to the container "upgrade-db" I can see it fails to load my DAGs because of errors like:
- connection.description does not exist:
```
ERROR [airflow.models.dagbag.DagBag] Failed to import: /opt/airflow/dags/my_amazing_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedColumn: column connection.description does not exist
LINE 1: ...id, connection.conn_type AS connection_conn_type, connection...
```
- variable.description does not exist:
```
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column variable.description does not exist
LINE 1: ....id AS variable_id, variable.key AS variable_key, variable.d...
                                                             ^
[SQL: SELECT variable.val AS variable_val, variable.id AS variable_id, variable.key AS variable_key, variable.description AS variable_description, variable.is_encrypted AS variable_is_encrypted 
FROM variable 
WHERE variable.key = %(key_1)s 
 LIMIT %(param_1)s]
```

My feeling is that the `airflow-local-db` pod tries to load the DAGs *before* having succesfully imported the variables and connections into the database.

To test this assumption, I did the following:
(For the sake of simplicity, I have reduced my custom Docker image to this)
```
FROM apache/airflow:2.1.1-python3.8
COPY dags /opt/airflow/dags
```

- I commented the COPY step out and tried installing the chart => I can succesfully deploy Airflow V2 to an empty namespace. This means that my environment does not contain any DAGs, but does have its connections and variables deployed. 
- Now, when I uncomment the COPY step again and re-run the installation, the installation succeeds and all my DAGs are deployed succesfully.
- When I delete my namespace again and try deploying a clean install (with dags included in my Docker image) I get the error from above again.

Any idea how to solve this? Is it absolutely necessary for the `airflow-local-db` pod to load the DAGs in order to fill the database?

**What version of the chart are you using?**:

I am using version `8.4.1`

**What is your Kubernetes Version?**:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T21:04:39Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**What is your Helm version?**:

```console
$ helm version
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}
```

**Comment by thesuperzapper** [comment]
@MarvinSchenkel I can't seem to reproduce this

Can you please provide an example python dag file which causes the `airflow-db-XXX` container to crash?

**Comment by thesuperzapper** [comment]
I also see @BastiaanRudolf and @DanojNL have liked this issue, can one of you share a python DAG file that causes the crash (when embedded into the image)?

**Comment by thesuperzapper** [comment]
@MarvinSchenkel I am interested to know if you still have this issue with [the new `8.5.0` version](https://github.com/airflow-helm/charts/blob/main/charts/airflow/CHANGELOG.md#850---2021-08-19) of the chart?

As we have removed the `upgrade-db` job, and replaced it with a Deployment called `db-migrations`.

**Comment by MarvinSchenkel** [comment]
I'm currently on holiday so I can't access my DAGs to send you an example.
I'll test the new chart when I get back next week and let you know.

Op ma 23 aug. 2021 om 02:30 schreef Mathew Wicks ***@***.***>

**Comment by MarvinSchenkel** [comment]
@thesuperzapper I think I figured out what's up. I found another error (besides the one in the OP). There is something happening because of our codebase.

We have a couple of `.py`  files that are executed by DAGs via a `BashOperator`. These `.py` files have a couple of required arguments that are parsed via `ArgumentParser`, for example:
```python
......some unrelated lines of code

# Argument parsing
parser = argparse.ArgumentParser(
    description='This script is used as a bash script within Airflow that executes the appropriate stored procedure '
                'on a DM within the Azure DWH. This stored procedure can be any procedure on the DM.')
parser.add_argument("--DM", help="The datamart (DM) we will execute the SP on.", required=True)
parser.add_argument("--SP", help="The stored procedure (SP) that will be executed.", required=True)
args = parser.parse_args()

if __name__ == '__main__':
    source_DM = args.DM
    source_SP = args.SP

    main(data_mart=source_DM, stored_procedure=source_SP)
```

It seems like the `db_migrations.py` file is actually _executing_ these Python files which results in the following error:
```
usage: db_migrations.py [-h] --DM DM --SP SP
db_migrations.py: error: the following arguments are required: --DM, --SP
```

Is there any way to avoid this error, for example excluding these files from migration since they are not DAGs?

**Comment by MarvinSchenkel** [comment]
/facepalm

Moving the `ArgumentParser` within the `main()` is _of course_ the correct solution. Rewriting most of our python files ensures we can actually deploy the latest charts without any issues. Closing this issue, sorry for the inconvenience.

Still curious as to why we were seeing the 'variable.description does not exist` error in the logs

**Comment by thesuperzapper** [comment]
@MarvinSchenkel just to check, are you not using the `.airflowignore` file to prevent airflow trying to run anything looking like a python file in your dags folder?

See the airflow docs for more info about `.airflowignore`:
https://airflow.apache.org/docs/apache-airflow/stable/concepts/dags.html#loading-dags

**Comment by MarvinSchenkel** [comment]
Awesome! I didn't know Airflow had an `.airflowignore` file. Will
definitely start using this, thanks for the tip!

**Comment by thesuperzapper** [comment]
@MarvinSchenkel I believe it only works at the ROOT of the dags folder (so you can only have one `.airflowignore` file).

**Comment by MarvinSchenkel** [comment]
Thanks! And thanks again for all your effort on this amazing chart :)
