### ISSUE TITLE
scheduler liveness probe does not exit with non-zero code on error

### ISSUE THREAD

**Issue by moriyoshi** [airflow-helm/charts#340]
**What is the bug?**
The following portions of the code for liveness check probe don't seem to work as they were intended to do:

* https://github.com/airflow-helm/charts/blob/airflow-8.4.1/charts/airflow/templates/scheduler/scheduler-deployment.yaml#L147
* https://github.com/airflow-helm/charts/blob/airflow-8.4.1/charts/airflow/templates/scheduler/scheduler-deployment.yaml#L149

Where those should have been accompanied by 'raise', which would effectively finalize the process with the status code '1'. 

**What version of the chart are you using?**:

I am seeing HEAD of master.

**Comment by thesuperzapper** [comment]
@moriyoshi thanks for raising this!

I have made PR https://github.com/airflow-helm/charts/pull/351, which should make it into the upcoming release today/tomorrow.

**Comment by moriyoshi** [comment]
Super cool! Thanks for taking care of this!
