### ISSUE TITLE
KubernetesExecutor pod_template should use `airflow.image.pullPolicy`

### ISSUE THREAD

**Issue by aprettyloner** [airflow-helm/charts#349]
## Summary
Worker pods do not have configurable `imagePullPolicy` so new packages are not picked up.

https://github.com/airflow-helm/charts/blob/703ba8e726be6eb8331cfee7251561384f86fba2/charts/airflow/files/pod_template.kubernetes-helm-yaml#L49

## Issue Encountered
Although the scheduler/web pods are pulling the most recent airflow image, the worker pods do not repull the image due to current configuration. This causes downstream errors in kubernetes tasks.

## Suggested fixes
Suggest that `{{ .Values.airflow.image.pullPolicy }}` is used instead.

I am aware of `kubernetesPodTemplate.extraPipPackages` but this is not a clean solution, as we expect the worker pods to have the same updated image that is built via CI process.

**Comment by thesuperzapper** [comment]
@aprettyloner thanks for raising this!

I have made PR https://github.com/airflow-helm/charts/pull/352, which will address this issue, it should be in the next release (today/tomorrow).
