### ISSUE TITLE
elastic remote logging

### ISSUE THREAD

**Issue by ArshiAAkhavan** [airflow-helm/charts#350]
**do we have support for elastic search remote logging?**

if so is it useful in case of kubernetsPodOperator or do i still need to use persistence volumes?

**Comment by thesuperzapper** [comment]
@ArshiAAkhavan Airflow natively supports Elasicsearch, see [apache-airflow-providers-elasticsearch](https://airflow.apache.org/docs/apache-airflow-providers-elasticsearch/stable/logging.html).

I think many users will want to know this, so I raised the issue https://github.com/airflow-helm/charts/issues/368, to add some docs about this in the "How to persist airflow logs?" section.

**Comment by thesuperzapper** [comment]
Lets move discussion to: https://github.com/airflow-helm/charts/issues/368
