### ISSUE TITLE
Problem with airflow.utils.serve_logs in Production

### ISSUE THREAD

**Issue by dktranzact** [airflow-helm/charts#369]
In prod we have the following warning message in worker logs:

```
 * Serving Flask app "airflow.utils.serve_logs" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
```

As I understand we need to set some WSGI server for airflow.utils.serve_logs flask app.
Is there a way to do this?

**Comment by thesuperzapper** [comment]
@dktranzact this is just how airflow works, you will have to raise it on the airflow issue tracker if you want it fixed.

However, this log has been here for years, so I doubt it will be changed.

**Comment by dkhome** [comment]
@thesuperzapper ok, thanks for explanation
