### ISSUE TITLE
Worker sidecar for DAG logs

### ISSUE THREAD

**Issue by kostas-rs** [airflow-helm/charts#37]
Hi, i am very new to using airflow and im trying to figure out a way to get the DAG logs from the worker pods to stdout (currently using CeleryExecutor). 

I know that it is common to use logging sidecars to extract logs from containers that do not emit logs to stdout. I am wondering if there is a way to use an extra container as a sidecar to pick up the DAG logs but only for the worker pods.

Currently i see that we have the option to use `airflow.extraContainers` but if i am not mistaken this way the container is created in all the pods, which is not ideal.

If there is currently another way (apart from configuring remote logging to S3 and elasticsearch) to get the logs in stdout, please let me know.

Thank you

**Comment by thesuperzapper** [comment]
@kostas-rs What STDOUT  are you referring to? (In the end all this stuff is happening in pods)

**Comment by kostas-rs** [comment]
@thesuperzapper im referring to these logs here: https://airflow.apache.org/docs/apache-airflow/stable/howto/write-logs.html

> The following convention is followed while naming logs: {dag_id}/{task_id}/{execution_date}/{try_number}.log

These logs look like cannot be send to STDOUT, so i am trying to pick them up using the sidecar container.
