### ISSUE TITLE
typo in `sync/_helpers/*` file names

### ISSUE THREAD

**Issue by NikolaySokolov** [airflow-helm/charts#370]
**What is the bug?**

I think the file names in https://github.com/airflow-helm/charts/tree/main/charts/airflow/templates/sync/_helpers shall be renamed, to have 'sync' as part of the name and not `snyc`. 

**What is your Helm version?**:

```
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"dirty", GoVersion:"go1.16.5"}
```

Great job with this helm chart, btw! Thanks for it.

**Comment by thesuperzapper** [comment]
@NikolaySokolov thanks for raising this, and the kind words!
