### ISSUE TITLE
Custom sidecar image for KubernetesPodOperator

### ISSUE THREAD

**Issue by macwro** [airflow-helm/charts#371]
By default image for sidecar is hardcoded to “alpine” from Docker Hub.
With current Docker Hub limitation, that makes a problem with larger scale processing.

Is there a way, to reconfigure Airflow to use sidecar image from private repository ?

I found that procedure, but somehow it does not work for me: https://hackmd.io/bhMoDP-zQgOKzBFr4MlB8g

**Comment by thesuperzapper** [comment]
@macwro thanks for raising this issue!

You can currently mount an `airflow_local_settings.py` file using `airflow.extraVolumes` and `airflow.extraVolumeMounts`, but I agree that this could be easier.

I have raised issue https://github.com/airflow-helm/charts/issues/373 to introduce some `airflow.localSettings.*` values to make generating `airflow_local_settings.py` files easier.
