### ISSUE TITLE
Make TLS secret name on Ingress optional

### ISSUE THREAD

**Issue by MarkusTeufelberger** [airflow-helm/charts#41]
See https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#ingresstls-v1-networking-k8s-io

"SecretName is the name of the secret used to terminate TLS traffic on port 443. **_Field is left optional_** to allow TLS routing based on SNI hostname alone. If the SNI host in a listener conflicts with the "Host" header field used by an IngressRule, the SNI host is used for termination and value of the Host header is used for routing."

I use an nginx-ingress controller and it supports a default certificate (https://kubernetes.github.io/ingress-nginx/user-guide/tls/#default-ssl-certificate - "The default certificate will also be used for ingress tls: sections that do not have a secretName option.") so there's no need to set this value. Currently I have to either manually modify the ingress object or duplicate the secret I want to use. This really should be optional and changing it wouldn't impact existing chart users.

**Comment by MarkusTeufelberger** [comment]
Commenting to please the robot overlords...

**Comment by thesuperzapper** [comment]
@MarkusTeufelberger do you want to raise a PR to implement this feature?

**Comment by thesuperzapper** [comment]
@MarkusTeufelberger do you still have this issue with `8.0.X` of the chart?

**Comment by MarkusTeufelberger** [comment]
I mean, https://github.com/airflow-helm/charts/blob/98dac02e793eeeaa7797a4601f9ba240f986ccec/charts/airflow/templates/webserver/webserver-ingress.yaml#L24 exists without an `if` that would remove it from the object if it isn't set, so I guess this problem still exists too.

**Comment by thesuperzapper** [comment]
Do you want to raise a PR to add that `{{- if ... }}`, and call it version `8.0.7`?

**Comment by thesuperzapper** [comment]
@MarkusTeufelberger can you confirm if this has been fixed in `8.0.7`?
