### ISSUE TITLE
how to integrate airflow dags with azure files?

### ISSUE THREAD

**Issue by gowdra01** [airflow-helm/charts#420]
I would like to know how do we integrate airflow with azure files ?
I tried to follow what's suggested here to create a PV -- https://docs.microsoft.com/en-us/azure/aks/azure-files-dynamic-pv and then changed the dags-data pvc to point at this but the pods were not loading ?

How do we work this out with azure files ? do you have an approach please advice thanks.

PS: the issue we have is azure storage class doesn't support ReadOnlyMany/ReadWriteMany access modes.

@thesuperzapper -- please suggest

**Comment by gowdra01** [comment]
I am facing this error 

```

MountVolume.SetUp failed for volume "pvc-a85214b0-3264-46a7-9d48-b2b9dcac4931" : mount failed: exit status 32 Mounting command: systemd-run Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/5231e52c-b642-4042-b808-5d954cdd17b0/volumes/kubernetes.io~azure-file/pvc-a85214b0-3264-46a7-9d48-b2b9dcac4931 --scope -- mount -t cifs -o actimeo=30,mfsymlinks,file_mode=0777,dir_mode=0777,vers=3.0,<masked> //fc0c947e33845492e8b8a07.file.core.windows.net/kubernetes-dynamic-pvc-a85214b0-3264-46a7-9d48-b2b9dcac4931 /var/lib/kubelet/pods/5231e52c-b642-4042-b808-5d954cdd17b0/volumes/kubernetes.io~azure-file/pvc-a85214b0-3264-46a7-9d48-b2b9dcac4931 Output: Running scope as unit: run-rd32e7216e4f84b5fae239474993c49e1.scope mount error(2): No such file or directory Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)

```

**Comment by thesuperzapper** [comment]
@gowdra01 I don't understand the issue you are having, please follow "Option 2a" or "Option 2b" under the ["How to store DAGs?"](https://github.com/airflow-helm/charts/tree/main/charts/airflow#how-to-store-dags) docs.

**Comment by gowdra01** [comment]
sorry I can t use those ReadOnlyMany or ReadWriteMany.. its not supported so I have to use azurefile storage class. but unfortunately I am getting the above error. although the pvc is successfully created but the scheduler are throwing the errors

**Comment by thesuperzapper** [comment]
@gowdra01 I can [see here](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes) that `AzureFile` supports `ReadOnlyMany` and `ReadWriteMany`.

Make sure your [`PersistentVolumeClaim`](https://kubernetes.io/docs/concepts/storage/dynamic-provisioning/#using-dynamic-provisioning) specifies `accessModes` to include `ReadOnlyMany`.
