### ISSUE TITLE
How to add sendgrid connection

### ISSUE THREAD

**Issue by jensgrnb** [airflow-helm/charts#432]
Hello, 

I'm trying to set up sendgrid email notifications. Airflow docs are very simple on this: https://airflow.apache.org/docs/apache-airflow/stable/howto/email-config.html

install apache-airflow[sendgrid] and this connection type will appear in the UI ready to be used along all the other default connections. 

So I went along happily adding this block to my helm values file

```
airflow:
  ...
  extraPipPackages:
    - "apache-airflow[sendgrid]~=2.1.2"
```

I'm using airflow=2.1.2 on python3.8 with version 8.5.0 of this lovely helm chart. 

However sendgrid doesn't appear in the UI as connection option as I was expecting. 

Am I missing something? I checked the web pod for installed pip packages, and sendgrid is there, but airflow doesn't seem to recognize it, or maybe doesn't look for it in the right path. 

Help me obi wan kenobi, you're my only hope.

**Comment by emartgu** [comment]
We build our own docker image on top of Airflow's official docker where we install providers separate:

```
FROM apache/airflow:2.1.4-python3.6

USER root
RUN apt-get update && \
  apt-get -y install gcc && \
  apt-get -y install g++ && \
  apt-get -y install libsasl2-dev && \
  apt-get -y install screen && \
  rm -rf /var/lib/apt/lists/*

USER airflow
RUN mkdir -p /home/airflow/.pip
COPY pip.conf /home/airflow/.pip/pip.conf

COPY airflow-providers.txt /home/airflow/
RUN pip install -r /home/airflow/airflow-providers.txt && \
  rm -f /home/airflow/airflow-providers.txt

WORKDIR ${AIRFLOW_HOME}
```

Where the airflow-providers.txt list the providers we need:
```
apache-airflow-providers-jdbc==2.0.1
apache-airflow-providers-elasticsearch==2.0.3
apache-airflow-providers-apache-hive==2.0.2
apache-airflow-providers-apache-spark==2.0.1
apache-airflow-providers-ftp==2.0.1
apache-airflow-providers-jira==2.0.1
apache-airflow-providers-sftp==2.1.1
apache-airflow-providers-ssh==2.1.1
```

I suppose you need include this provider: 
https://airflow.apache.org/docs/apache-airflow-providers-sendgrid/stable/index.html

**Comment by jensgrnb** [comment]
Hey @emartgu 

The thing is I have the relevant provider installed. I checked the running docker container. Just wondering how the airflow UI looks for these providers internally, as it still isn't recognizing it for me..

**Comment by thesuperzapper** [comment]
@jensgrnb are you sure that you haven't accidentally NOT changed your docker tag (for example, using `latest`)?

If so, you either need to set `airflow.image.pullPolicy = Always` or update your tag, as otherwise you will be using the old cached version on the Kubernetes Node.

**Comment by jensgrnb** [comment]
I opened up a question against airflows official github repo: https://github.com/apache/airflow/issues/18495#issuecomment-926639104

apparantly this package doesn't have a dedicated ui symbol... so it would never show up.

**Comment by jensgrnb** [comment]
Got it working by using the http connection type and setting 

```
os.environ['SENDGRID_MAIL_FROM'] = "for-whom-do-the-bells-tool"
os.environ['SENDGRID_MAIL_SENDER'] = "they-tool-for-thee"
```

the airflow developers have got a fix for sendgrid to get it it's own connection type in airflow@2.2.0 as far as I can tell.
