### ISSUE TITLE
Running pods get externally marked as Scheduled or None during helm upgrade

### ISSUE THREAD

**Issue by piyush-daga** [airflow-helm/charts#436]
**What is your question?**
Airflow Version: `airflow:2.1.2-python3.8` base extended with business logic code
Helm Chart Version: `8.5.2`
Executor: `KubernetesExecutor`
Platform: `AWS EKS`
Webserver and Scheduler: `2 replicas with a PDB of 50% [minAvailable.`](url)
Operators used: `Mostly BashOperators throughout the code.`

We have a CI/CD setup where we perform `helm upgrade` to inject changes to `values.yml` file or changes to the business logic code which is bundled in the image. Any running task when performing `helm upgrade` has its status externally changed, receives SIGTERM and is marked as FAILED.

Ideally, I'd hope that would not be the case as we are using HA Webserver and Scheduler with k8s executor.

Any help or documentation around the same would be greatly appreciated.

<img width="1367" alt="Screenshot 2021-09-27 at 1 23 38 PM" src="https://user-images.githubusercontent.com/9255130/134867137-519886c5-7559-459f-97cf-53d163cb6bd9.png">

**Comment by thesuperzapper** [comment]
@piyush-daga can you share your values?

I imagine that something is causing the [KubernetesExecutor `pod_template.yaml`](https://github.com/airflow-helm/charts/blob/main/charts/airflow/files/pod_template.kubernetes-helm-yaml) to change after each of your `helm upgrade`.

For example, are you changing your airflow docker image each `helm upgrade` (e.g. embedding your dags into the image)?

**Comment by piyush-daga** [comment]
Yes, I am changing my docker image after each upgrade and I am embedding my dags into my image. I was under the assumption that even if we embed dags, that running tasks should keep running? (at least when nothing changes on the dag front).

Is there any solution around the same?

**Comment by piyush-daga** [comment]
@thesuperzapper Any help or direction here would be awesome. Struggling with this issue as being a blocker for production release.

**Comment by thesuperzapper** [comment]
@piyush-daga I don't see a way to prevent the pods from restarting when the images are changed (which is probably what causes the tasks to be marked as "None", specifically the scheduler restarting).

You could try Option 1 or 2 under ["How to store dags?"](https://github.com/airflow-helm/charts/tree/main/charts/airflow#how-to-store-dags).

**Comment by thesuperzapper** [comment]
@piyush-daga I don't really understand your question, but since this issue has been open for a while, I am gonna close it.

Feel free to reopen if this is still an issue for you.
