### ISSUE TITLE
is it possible to sync 2 seperate git repos to single dag folder or 2 diffrent dag folders ?

### ISSUE THREAD

**Issue by tomahawk-pilot** [airflow-helm/charts#440]

**Comment by thesuperzapper** [comment]
@tomahawk-pilot Yes, but it's not currently documented, you can use [git submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules) with the `.gitmodules` file (it allows a single git repo to act as a "wrapper" for other repos).

We have an issue to document `.gitmodules` here: https://github.com/airflow-helm/charts/issues/434

We can probably add a new section to the docs called `"How to sync multiple DAG repos?"`, or explain it under "Option 1" of ["How to store DAGs?"](https://github.com/airflow-helm/charts/tree/main/charts/airflow#how-to-store-dags).

**Comment by thesuperzapper** [comment]
@karakanb actually looking into submodules further, when you add a submodule with `git submodule add ...` it actually creates a metadata file with the hash of the commit.

This means the submodule approach will never update the downstream repo unless you commit a new metadata file (generated by running `git submodule update` in your "wrapper" repo).

I realize this is less useful for airflow dags, and probably this means we still need to keep discussing how best to implement multiple git-sync sidecars (issue: https://github.com/airflow-helm/charts/issues/166).

_(However, in the meantime, you could run some sort of CI/CD which updates your main git repos submodules when the downstream repos change)_

**Comment by thesuperzapper** [comment]
Closing, we please move discussion on using multiple git-repos for DAGs to: https://github.com/airflow-helm/charts/issues/166
