### ISSUE TITLE
include option to set resource requests and limits for initContainers

### ISSUE THREAD

**Issue by chriskeAlerant** [airflow-helm/charts#444]
**What is your feature request?**

Currently there is no way to set exact resource requests and limits for initContainers in the values file. As I saw these parameters are not defined in the template, wihch means when there is a default value for them in the namespace, those will be applied. I work in an enterprise environment and change the default resource settings for the namespace is not so easy.

**What alternatives have you considered?**

I don't think there are other alternatives. Currently I'm using kustomize to add these values to the rendered chart.

**Comment by thesuperzapper** [comment]
@chriskeAlerant thanks for the request, I am closing this to continue the discussion on https://github.com/airflow-helm/charts/issues/242
