### ISSUE TITLE
Common Labels 

### ISSUE THREAD

**Issue by vlgorev** [airflow-helm/charts#447]
Hi,

Our organization requires some specific labels to be added to every Deployment on K8s. I understand, that's not a pressing issue, but, would you be so kind to add a "CommonLabels" section to your ".../airflow/values..yaml" that'll be translated to every "label" section of the Deployment YAMLs?

**Comment by thesuperzapper** [comment]
@vlgorev I am closing this issue so we can continue discussion on https://github.com/airflow-helm/charts/issues/466
