### ISSUE TITLE
Is it possible to have git sync not override the scheduler's dag path?

### ISSUE THREAD

**Issue by cfraleig** [airflow-helm/charts#450]
It looks like when I enable the git sync, it sets the dag path as `dags.path`+repo/dags

I have some dags updated via a cron process that writes them to a PVC. I would like to be able to have the git_sync write into that claim, under the dag path, without overriding the path the scheduler will look for dags in to fill the dag-bad.

**Comment by cfraleig** [comment]
Our dags are distributed out. I have one process that dynamically builds dags and stores the generated dags in an efs volume mount. This is where the dagbag loads up from. I also have dags, not part of that process, stored in another repo. These dags do not require the dynamic process, and so a git sync works great. I want to be able to route the sync into the same pvc under the "dags" path that already exists.

**Comment by thesuperzapper** [comment]
@cfraleig the approach you describe of dynamically generating dags, and storing them in an EFS volume doesn't require git-sync, you should just disable git-sync (`dags.gitSync.enabled`), and instead use `dags.persistence.existingClaim` to mount your EFS Volume (so all pods have the DAG python files).
