### ISSUE TITLE
Patch Airflow to use okta email address instead of okta_id as the username

### ISSUE THREAD

**Issue by piyush-daga** [airflow-helm/charts#452]
When enabling OAUTH using Okta, the username is replaced by the okta_id, which is a unique identifier to differentiate users but it makes it super difficult to understand which `exact user` is being referenced in a human friendly manner.

Examples:

<img width="1400" alt="Screenshot 2021-10-31 at 7 36 55 PM" src="https://user-images.githubusercontent.com/9255130/139587586-eb36bea8-1a55-41c4-99bd-356501b2d691.png">
^ The user-statistics page

<img width="1389" alt="Screenshot 2021-10-31 at 7 38 15 PM" src="https://user-images.githubusercontent.com/9255130/139587640-0455e95d-229d-45fb-8971-fab232233bcc.png">
^ Or the Audit Logs

If we could patch Airflow to use the `email address` or even the `username` of the email address, that would be amazing.
In the meantime, I'll be looking for solutions to patch the same, any references for that would also help.

**Comment by thesuperzapper** [comment]
@piyush-daga this is really a question for Airflow / Flask-AppBuilder, not the chart.

You will have more luck raising it on those repos.

**Comment by thesuperzapper** [comment]
@piyush-daga I will close this

Feel free to raise it on the [dpgaspar/Flask-AppBuilder](https://github.com/dpgaspar/Flask-AppBuilder) repo.

__NOTE:__ you can make a custom `@appbuilder.sm.oauth_user_info_getter` that uses something like `email` for the `uername` see the [Flask-AppBuilder - Security Docs](https://flask-appbuilder.readthedocs.io/en/latest/security.html#authentication-oauth) (down the bottom).

__FYI:__ emails are not static IDs, that is, the same user can change emails over time, that is why Flask-AppBuilder uses the `sub` claim from Okta by default
