### ISSUE TITLE
Allow users to provide extra Containers in kubernetesPodTemplate

### ISSUE THREAD

**Issue by jonashartwig** [airflow-helm/charts#455]
**What is your feature request?**

We like to mount the dag directory into the pod executor. We have our dags in S3 and use s3fs as a sidecar to mount the volume.

**What alternatives have you considered?**

We checked if there are possibilities in Airflow to use this natively, like storing logs in S3.

**Comment by thesuperzapper** [comment]
Bumping for bot, as PR https://github.com/airflow-helm/charts/pull/456 will close this issue on the `8.6.0` release.
