### ISSUE TITLE
allow setting labels on `sync` and `db-migrations` Deployments/Jobs

### ISSUE THREAD

**Issue by oleksandrkovalenko** [airflow-helm/charts#466]
## What is your feature request?

In some places it's possible to configure `labels` and `podLabels` via values.yaml. Somewhere only `podLables` are available. I'm suggesting to unify it all over the chart.

There are some examples of deployment templates which have only podLabels: `db-migrations-deployment.yaml`, `pgbouncer-deployment.yaml`, `sync-connections-deployment.yaml`

We are not able to migrate to latest chart version, because K8s we use require custom labels to be present on every deployment

**Comment by thesuperzapper** [comment]
@oleksandrkovalenko there is already the ability to set `podLabels` for those deployments:
- `airflow.dbMigrations.podLabels`
- `airflow.sync.podLabels`
- `pgbouncer.podLabels`

Or are you asking for a  "global" podLabels like `airflow.podLabels`?

**Comment by oleksandrkovalenko** [comment]
@thesuperzapper There are deployment templates in the chart. Some of them have labels and podLabels. Some only podLables. My assumption is that labels goes to deployment itself and podLabels are for pods created by this deployment. As for now I can't configure custom labels (not podLabels). I created a PR to illustrate what is missing in the templates: https://github.com/airflow-helm/charts/pull/467

**Comment by thesuperzapper** [comment]
Bumping for the bot, as https://github.com/airflow-helm/charts/pull/467 is waiting to be merged when `8.6.0` is released.
