### ISSUE TITLE
dags are entering to deadlock state and failing

### ISSUE THREAD

**Issue by gowdra01** [airflow-helm/charts#468]
Hi @thesuperzapper
can you please let me know I am seeing this below error in one of our airflow environements what could be the issue?
Dags are entering to failing state

what could be the reason?

```[2021-11-16 04:33:50,612] {dagrun.py:459} ERROR - Deadlock; marking run <DagRun yellowbrick_reports @ 2021-11-16 04:33:49.116086+00:00: manual__2021-11-16T04:33:49.116086+00:00, externally triggered: True> failed```

**Comment by thesuperzapper** [comment]
@gowdra01 I am going to need more information, but I strongly doubt its related to the chart.

You might want to google your error message, specifically the `Deadlock; marking run ` part.
