### ISSUE TITLE
airflow upgrade

### ISSUE THREAD

**Issue by saip50** [airflow-helm/charts#472]
Airflow Helm Chart (User Community): https://github.com/airflow-helm/charts/tree/main/charts/airflow

Currently, we are using Airflow Helm Chart (User Community) v8.5.2 and airflow v2.0.2 deployed in azure AKS. 
got that, airflow have released there new version v2.2.2, so can we use the same Airflow Helm Chart (User Community) v8.5.2 chart to upgrade our airflow to v2.2.2 or is there any future enhancement for the upgrade of airflow v2.2.2 in the same chart by Airflow Helm Chart (User Community) as now in this chart present current version as v2.1.0.

**Comment by thesuperzapper** [comment]
@saip50 I always recommend testing any upgrade in a dev environment, and not blindly upgrading prod.

The main airflow `v2.2.X` feature missing from `v8.5.2` is that we don't currently support [Deferrable Operators & Triggers](https://airflow.apache.org/docs/apache-airflow/stable/concepts/deferring.html).

### The issue to track adding "Deferrable Operators & Triggers" to the chart is: https://github.com/airflow-helm/charts/issues/424

**Comment by saip50** [comment]
@thesuperzapper yes, we always test upgrade in dev environment initially as a best practice.
Thanks for the update. we will be following up on the issue #424 for more updates on new chart and features.
