### ISSUE TITLE
Non `cluster.local` domains break internal DBs

### ISSUE THREAD

**Issue by JanPokorny** [airflow-helm/charts#476]
The chart currently assumes that the internal cluster domain is `cluster.local` -- see https://github.com/airflow-helm/charts/search?q=%22cluster.local%22. When the internal domain is not `cluster.local` -- such clusters sadly do exist -- the bundled PostgreSQL, PgBouncer, and Redis can't be accessed.

Proposed solution: either use a short domain for services (`serviceName.namespace` instead of `serviceName.namespace.svc.cluster.local`), or allow customizing the internal cluster domain (see for example this chart, the value `clusterDomain` -- https://artifacthub.io/packages/helm/bitnami/argo-cd).

**Comment by thesuperzapper** [comment]
@JanPokorny thanks, I agree that we should add a value like `airflow.clusterDomain`!

In fact, there is a pending PR with this very feature, take a look at PR: https://github.com/airflow-helm/charts/pull/441

---

I plan to cut a release with the currently pending PRs, but I really don't want to create an `8.6.0` release until we resolve https://github.com/airflow-helm/charts/issues/424 (for full airflow 2.2 support) and https://github.com/airflow-helm/charts/issues/412#issuecomment-974909150 (fix azure PGBouncer issues).

**Comment by thesuperzapper** [comment]
@JanPokorny sorry about the lack of response here! 

> https://drewdevault.com/2021/10/26/stalebot.htm

Those comments are interesting, and I am open to other ideas of running the repo, but also realize that I am not just using stalebot on its own, I often apply the `lifecycle/frozen` to "accepted" issues after the first time the bot triggers, and when that label is applied, the bot will never close the issue.

---

Regarding this issue itself, PR https://github.com/airflow-helm/charts/pull/441 will resolve it, but there are some other issues that need to be resolved before I can cut `8.6.0`, see the [milestone for `8.6.0`](https://github.com/airflow-helm/charts/milestone/2).

**Comment by thesuperzapper** [comment]
@JanPokorny you will be happy to know that I have changed the stalebot configs in https://github.com/airflow-helm/charts/commit/ca3947aba1bb30532f721c34ac3c5468773ee068

But also, I am getting closer to cutting `8.6.0` which will fix this issue (after an unreasonable delay... sorry).
