### ISSUE TITLE
Binding Azure Postgres Database

### ISSUE THREAD

**Issue by reyaL-dev** [airflow-helm/charts#478]
Hello everyone,

since we cannot edit the parameter for the database-connection directly anymore I can't get the Azure Postgres-DB bound to the image. I think its because the "@" sign is not parsed correctly, since it is required in 'Azure Pgsql in comparison tu regular Pgsql.
(For instance: user=mypsqladmin@sql-kube-server )
Does anyone has successfully attached a Azure postgres DB?

Best regards

**Comment by thesuperzapper** [comment]
@reyaL-dev you are correct, PGBouncer requires a special setting change to support Azure Postgress, see my comment https://github.com/airflow-helm/charts/issues/412#issuecomment-974909150.

If someone wants to make a PR that makes the changes I suggest in https://github.com/airflow-helm/charts/issues/412#issuecomment-974909150, this would be great.

I will close this issue so we can move the discussion to https://github.com/airflow-helm/charts/issues/412.
