### ISSUE TITLE
docker container tag refers to Airflow v2.2.1 but running "airflow version" in a container results in v.2.1.4

### ISSUE THREAD

**Issue by jensgrnb** [airflow-helm/charts#481]
A data engineer spotted that there seems to be a discrepancy in the reported airflow version and the docker tag we're running. 
The container specifies v.2.2.1 but running "airflow version" in a shell in any of the k8s pods results in v.2.1.4 being printed. 

I assume this is airflow not having updated their "version" package, and not us thinking we're running 2.2.1 and actually on 2.1.4...

**Comment by jensgrnb** [comment]
https://github.com/apache/airflow/issues/20168

Raised the problem at airflow, however the problem was resolved by upgrading the dependency pin we had on one of our extra pip installs, which pulled in a different version of airflow from pypi than the one defined in the docker image.

**Comment by tsaaii** [comment]
@jensgrnb I am looking for a way to add pip packages to my airflow which is installed using a helm chart. Can you explain the process? where should I add my pip commands? on the helm chart values.yaml or somewhere in the docker container?

**Comment by thesuperzapper** [comment]
> @jensgrnb I am looking for a way to add pip packages to my airflow which is installed using a helm chart. Can you explain the process? where should I add my pip commands? on the helm chart values.yaml or somewhere in the docker container?

@tsaaii see the ["How to install extra pip packages?"](https://github.com/airflow-helm/charts/tree/main/charts/airflow#how-to-install-extra-pip-packages) section in the FAQ.
