### ISSUE TITLE
Google Cloud connection not working

### ISSUE THREAD

**Issue by anyght** [airflow-helm/charts#482]
## What is the bug?

The test for new `Google Cloud` connection is not working: 
I have set my connection on the graphic interfaces and click the button test for check connection
![image](https://user-images.githubusercontent.com/59748997/145865080-25de1ec4-2e13-4212-94c6-0d103ad60652.png)

![image](https://user-images.githubusercontent.com/59748997/145865264-24b269be-d969-4389-852c-ff3115f52168.png)

## What version of the chart are you using?

Chart version : airflow-8.5.2
APP version : 2.1.2  

## What version of Kubernetes are you using?

```console
######## PASTE `kubectl version` BELOW ########
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.10-gke.1600", GitCommit:"ef8e9f64449d73f9824ff5838cea80e21ec6c127", GitTreeState:"clean", BuildDate:"2021-09-06T09:24:20Z", GoVersion:"go1.15.15b5", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.22) and server (1.20) exceeds the supported minor version skew of +/-1
######## PASTE `kubectl version` ABOVE ########
```

## What version of Helm are you using?

```console
######## PASTE `helm version` BELOW ########
version.BuildInfo{Version:"v3.7.0", GitCommit:"eeac83883cb4014fe60267ec6373570374ce770b", GitTreeState:"clean", GoVersion:"go1.16.8"}
######## PASTE `helm version` ABOVE ########
```

**Comment by thesuperzapper** [comment]
@anyght can you clarify how this is related to the chart?

**Comment by anyght** [comment]
I don't know if it is a problem with the chart or it is a problem of docker images (i didn't change the default images), I ask there because I used this chart. May be someone known what is happened?

**Comment by thesuperzapper** [comment]
I really don't have enough information to help you, but this is probably an issue to ask on the Airflow Slack.
