### ISSUE TITLE
Git-sync won't work on AzureDevOps

### ISSUE THREAD

**Issue by pgvirtuoso** [airflow-helm/charts#483]
## What is your feature request?

I would like the chart to work git-sync with Azure devOps repos.

## What alternatives have you considered?

Alternatively, the chart could allow editing git command. With the actual config I get the following error:

gmartinez@LT-0742:/mnt/c/Users/giovanni.martinez/kcftech/kubernetes-manifests-old/11_databases/airflow/stage01$ kubectl -n airflow logs -f airflow-scheduler-7c46d47bcf-8f6nd -c git-sync-init
INFO: detected pid 1, running init handler
I1213 21:32:25.308936      12 main.go:495]  "level"=0 "msg"="starting up"  "args"=["/git-sync"] "pid"=12
I1213 21:32:25.309037      12 main.go:784]  "level"=0 "msg"="cloning repo"  "origin"="ssh://git@ssh.dev.azure.com:v3/kcftech/SmartDiagnostics/airflow-dags" "path"="/git"
E1213 21:32:25.324620      12 main.go:168]  "msg"="too many failures, aborting" "error"="Run(git clone --no-checkout -b main --depth 1 ssh://git@ssh.dev.azure.com:v3/***/***/airflow-dags /git): exit status 128: { stdout: \"\", stderr: \"Cloning into '/git'...\\nfatal: Could not read from remote repository.\\n\\nPlease make sure you have the correct access rights\\nand the repository exists.\\n\" }"  "failCount"=0

**Comment by thesuperzapper** [comment]
@pgvirtuoso what are you asking?

It looks like the error is that you have not given the required SSH Key or HTTP Password/Token.

Take a look at "Option 1a" and "Option 1b" under ["How to store DAGs?"](https://github.com/airflow-helm/charts/tree/main/charts/airflow#how-to-store-dags) for examples of how to use them.

**Comment by pgvirtuoso** [comment]
Sorry, my mistake. I had to replace ssh://git@ssh.dev.azure.com:v3/****/****/airflow-dags with ssh://git@ssh.dev.azure.com/v3/****/****/airflow-dags
