### ISSUE TITLE
support Microsoft SQL Server as a database backend 

### ISSUE THREAD

**Issue by Jakal1337** [airflow-helm/charts#487]
## What is your feature request?
Using mssql as backend database for airflow deployments.
Since it's available for airflow v2.2.0 and newer.
https://airflow.apache.org/docs/apache-airflow/2.2.0/howto/set-up-database.html

## The tests already made
Tried to add as external DB in values.yaml, but it looks like the db connection string is not correctly parsed.
```
Traceback (most recent call last):
  File "/home/airflow/.local/bin/airflow", line 5, in <module>
    from airflow.__main__ import main
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/__init__.py", line 46, in <module>
    settings.initialize()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/settings.py", line 486, in initialize
    configure_orm()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/settings.py", line 224, in configure_orm
    engine = create_engine(SQL_ALCHEMY_CONN, connect_args=connect_args, **engine_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/__init__.py", line 525, in create_engine
    return strategy.create(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 54, in create
    u = url.make_url(name_or_url)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/url.py", line 229, in make_url
    return _parse_rfc1738_args(name_or_url)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/url.py", line 291, in _parse_rfc1738_args
    "Could not parse rfc1738 URL from string '%s'" % name
sqlalchemy.exc.ArgumentError: Could not parse rfc1738 URL from string
```

```
###################################
# Database - PostgreSQL Chart
# - https://github.com/helm/charts/tree/master/stable/postgresql
###################################
postgresql:
  ## if the `stable/postgresql` chart is used
  ## NOTE:
  ## - set to `false` if using an external database
  enabled: false

###################################
# Database - External Database
# - these configs are only used when `postgresql.enabled` is false
###################################
externalDatabase:
  ## the type of external database: {mysql,postgres}
  #
  type: mssql

  ## the host of the external database
  ##
  host: databasehost.fqdn

  ## the port of the external database
  ##
  port: 56599

  ## the database/scheme to use within the the external database
  ##
  database: DB_Airflow

  ## the user of the external database
  ##
  user: airflow

  ## the name of a pre-created secret containing the external database password
  ##
  passwordSecret: "mssqlsecret"

  ## the key within `externalDatabase.passwordSecret` containing the password string
  ##
  passwordSecretKey: "password"

  ## the connection properties for external database, e.g. "?sslmode=require"
  properties: ""
```

**Comment by thesuperzapper** [comment]
@Jakal1337 I don't have a Microsoft SQL database to test this with.

If you want to contribute this feature, you will need to add a `mssql` as a valid value for `externalDatabase.type`, which will require:
1. You to add `mssql` as a valid value for `externalDatabase.type` in [`./_helpers/validate-values.tpl`](https://github.com/airflow-helm/charts/blob/main/charts/airflow/templates/_helpers/validate-values.tpl#L168-L170)
2. You to update the generation code for `DATABASE_SQLALCHEMY_CMD ` and `DATABASE_CELERY_CMD ` in [`./config/secret-config-envs.yaml`](https://github.com/airflow-helm/charts/blob/main/charts/airflow/templates/config/secret-config-envs.yaml#L48-L64) to support `mssql`.

**Comment by Jakal1337** [comment]
@thesuperzapper It works thank you !

In [_helpers/validate-values.tp](
https://github.com/airflow-helm/charts/blob/main/charts/airflow/templates/_helpers/validate-values.tpl#L168-L170)  it looks like this:
{code}
    {{- if not (has .Values.externalDatabase.type (list "mysql" "postgres" "mssql")) }}
    {{ required "The `externalDatabase.type` must be one of: [mysql, postgres, mssql]!" nil }}
    {{- end }}
{code}

In [/config/secret-config-envs.yaml](https://github.com/airflow-helm/charts/blob/main/charts/airflow/templates/config/secret-config-envs.yaml#L48-L64) it looks like this:
{code}
  DATABASE_SQLALCHEMY_CMD: {{ `echo -n "mysql+mysqldb://$(eval $DATABASE_USER_CMD):$(eval $DATABASE_PASSWORD_CMD)@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_DB}${DATABASE_PROPERTIES}"` | b64enc | quote }}
  {{- else if eq "mssql" .Values.externalDatabase.type }}
  ## Added MSSQL Support
  DATABASE_SQLALCHEMY_CMD: {{ `echo -n "mssql+pyodbc://$(eval $DATABASE_USER_CMD):$(eval $DATABASE_PASSWORD_CMD)@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_DB}${DATABASE_PROPERTIES}"` | b64enc | quote }}
  {{- end }}

..........

  DATABASE_CELERY_CMD: {{ `echo -n "db+mysql://$(eval $DATABASE_USER_CMD):$(eval $DATABASE_PASSWORD_CMD)@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_DB}${DATABASE_PROPERTIES}"` | b64enc | quote }}
  {{- else if eq "mssql" .Values.externalDatabase.type }}
  ## Added MSSQL Support
  DATABASE_CELERY_CMD: {{ `echo -n "db+mssql+pyodbc://$(eval $DATABASE_USER_CMD):$(eval $DATABASE_PASSWORD_CMD)@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_DB}${DATABASE_PROPERTIES}"` | b64enc | quote }}
  {{- end }}
{code}

In [/values.yaml](https://github.com/airflow-helm/charts/blob/df99a33e3278de9f6935e747e8317794966ed979/charts/airflow/values.yaml#L1603) add the ODBC driver support and database settings.
{code}
  ## the type of external database: {mysql,postgres}
  ##
  type: mssql
.....
  ## the connection properties for external database, e.g. "?sslmode=require"
  properties: "?driver=ODBC+Driver+17+for+SQL+Server"
{code}

Deploy and verify logs from sidecar container check-db.

Debugging in container: 
{code}
isql -v -k "DRIVER={ODBC Driver 17 for SQL Server};SERVER=tcp:<database-server>,<port>\<database>;UID=<db-user>;PWD=<password>"
{code}
Also make sure ODBC driver is configured correctly in container.

**Comment by thesuperzapper** [comment]
@Jakal1337 I am gonna reopen this, as @kodefish has raised a PR to implement this, but it has not been merged yet: 
- https://github.com/airflow-helm/charts/pull/507/files

**Comment by Jakal1337** [comment]
@thesuperzapper guess this can be closed: https://airflow.apache.org/docs/apache-airflow/2.9.0/release_notes.html#support-for-microsoft-sql-server-for-airflow-meta-database-has-been-removed-36514

**Comment by thesuperzapper** [comment]
@Jakal1337  that's a bit sad, but I do understand why Airflow decided to do this, as its already a lot of work supporting MySQL and Postgres.
