### ISSUE TITLE
How to install pip packages on airflow image/helm chart?

### ISSUE THREAD

**Issue by tsaaii** [airflow-helm/charts#491]
## What is your question?
I looked at issues here and it looks like there are 3 ways to add pip packages to dockerfile or helm chart.

1. adding it to dockerfile and building the image and then use helm chart on it to install airflow.

```
FROM apache/airflow:latest
USER root
RUN pip install "package1" "package2" "package3" 
```

2. adding them to helm chart values.yaml file under extraPipPackages

```
executor: "KubernetesExecutor"
images:
  airflow:
    repository: "local/airflow"
    tag: "latest"
    extraPipPackages:
      - "Package1==1.3" 
      - "package2==2.0" 
```

3. adding a command under webserver in values.yaml file 
```
webserver:
   command: ["pip install package1 && pip install package2"]
```

I tried all the 3, while no method gives an error, i don't see my pip packages( this is supposed to show snowflake operator in airflow)

docker logs while building image shows that these packages are being installed but I don't see them when I look in the container

`docker exec container_id pip list` doesn't show my packages which were installed earlier.

What is the right way of installing pip packages?

My kubectl version is

$ kubectl version
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:16:20Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:42:41Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
```
My helm chart version is 

`version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.16.9"}`

**Comment by piyush-daga** [comment]
I have used methods 1 and 2 and could see and use installed packages.
1. Did you try with some other packages as a test?
2. Can you paste your `values.yml` file for further inspection?

**Comment by tsaaii** [comment]
Hi @piyush-daga, Thanks for your response. 
Method 1 works for me now.

**Comment by piyush-daga** [comment]
Hey @tsaaii could you tell what was the problem before?

**Comment by tsaaii** [comment]
I noticed that when i add pip packages as ROOT user on dockerfile, it doesn't install them. I couldn't find them on kubernetes pods.
I had to change user to airflow
```
FROM apache/airflow:latest
USER root
RUN pip install "package1" "package2" "package3" 
```

**Comment by piyush-daga** [comment]
Ohh yeah, we also had to ensure that any folders that airflow had to write to, should be created using the airflow user or running chown on them.
