### ISSUE TITLE
Release old chart versions 

### ISSUE THREAD

**Issue by billcrook** [airflow-helm/charts#5]
Thanks for getting this up and running guys. Would it be possible to release old versions of the charts? I'm sure there are some users out there (myself included) who aren't ready to perform chart or airflow version upgrades. Additionally, some of us are still running on the docker-puckel image and upgrading the chart would force a change in base image which is significant. Yes, I know we need to get off of the old version ;) Thanks again!

**Comment by thesuperzapper** [comment]
@billcrook while it might be possible, I am not sure its worth the effort

You will still be able to install old versions (before `7.14.0`), using the archive repo: `https://charts.helm.sh/stable`,

```bash
helm repo add stable https://charts.helm.sh/stable
helm repo update
```
However, be aware that repo __will never__ receive any new versions, all future development will be done in this repository.

**Comment by billcrook** [comment]
OK, that is good news. I suppose I was misinterpreting the [deprecation notice](https://github.com/helm/charts#deprecation-timeline) in [helm/charts](https://github.com/helm/charts).

> Nov 13, 2020 | At 1 year, support for this project will formally end, at which point the stable and incubator chart repos will be marked obsolete. At that time these chart repos **will likely be garbage collected and no longer available**. This git repository will remain as an archive.

The wording makes it sound like there will be no archive available after the 13th.

**Comment by billcrook** [comment]
I forgot about one thing - requirements.yaml. If using an old chart version, the redis/pg dependencies will still point to the deprecated url https://kubernetes-charts.storage.googleapis.com/.

So, someone would have to update all the versions to point to the new archive url. Sigh.

**Comment by thesuperzapper** [comment]
@billcrook chart versions are atomic, so you will not be able to change them after they are released

However, as of helm `3.4.0`, it will automatically detect `https://kubernetes-charts.storage.googleapis.com/` and replace it with `https://charts.helm.sh/stable`, so old versions should work correctly.

**Comment by billcrook** [comment]
I'm still on helm 2 so, SOL for me. I think my best bet is to either upgrade to helm 3 or fork and update the old chart, package it and configure a local helm repository.

Thanks for the info, this has been very helpful.
