### ISSUE TITLE
GitHub/Lab OAUTH breaking dashboard and now showing as button on login page

### ISSUE THREAD

**Issue by hkvia** [airflow-helm/charts#509]
### Checks

- [X] I have checked for [existing issues](https://github.com/airflow-helm/charts/issues).
- [X] I have looked through the [FAQ](https://github.com/airflow-helm/charts/tree/main/charts/airflow#faq---airflow).

### Question

I have overwrite for webserver_config as show on docs to use OAUTH with github or gitlab and when I log into the dashboard it directly tries to authenticate with the provider, I don't even get to see the dashboard and logic options?

**Comment by thesuperzapper** [comment]
@hkvia the issue will be that you have `AUTH_USER_REGISTRATION_ROLE` set to `"Public"` (which gives no access), but you have not provided any `AUTH_ROLES_MAPPING` to give the `"Viewer"`, `"User"` or `"Admin"` role from a `group`.

If simply being logged into the OAUTH should give access to the Airflow UI (for your security situation), then update `AUTH_USER_REGISTRATION_ROLE` to `"Viewer"`, `"User"` or `"Admin"`.

We should update the  ["How to authenticate airflow users with LDAP/OAUTH?"](https://github.com/airflow-helm/charts/tree/main/charts/airflow#how-to-authenticate-airflow-users-with-ldapoauth) docs to explain `AUTH_USER_REGISTRATION_ROLE`  needs to be set to `"Admin"` if `AUTH_ROLES_MAPPING` is not used.

**Comment by hkvia** [comment]
Is there another way to do this authentication, seems like flask-appbuilder has bugs with open issues that fixes them but no one bothers merging them. Is this literally the only way this can be done?

**Comment by hkvia** [comment]
@thesuperzapper  Thanks for that I've updated my settings. However I think what really fixed it is updating flask-appbuilder to 3.4.3 now Airflow dashboard is showing with button for a given auth method
