### ISSUE TITLE
Multi-Attach error for volume for pods.

### ISSUE THREAD

**Issue by rg2609** [airflow-helm/charts#51]
**What is the bug?**

I am trying to add the PVC for dags, so I added the relevant values for PVC in custom_value.yaml. 
I Created PVC before installing the helm and the following is the PVC code:
```bash
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-dag-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
```
**Error:**
` Multi-Attach error for volume "pvc-de5cae93-d519-4479-b24a-587083ffc642" Volume is already used by pod(s) airflow-chart-scheduler-75964ffbf4-drszp`

**What are your Helm values?**

Any relevant parts of your `custom_values.yaml`
  ```bash
dags:
  ## configs for the dags PVC
  ##
    persistence:
      ## if a persistent volume is mounted at `dags.path`
      ##
      enabled: true

      ## the name of an existing PVC to use
      ##
      existingClaim: "airflow-dag-pvc"
```

**What is your Kubernetes Version?**:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.15-gke.4901", GitCommit:"7ed5ddc0e67cb68296994f0b754cec45450d6a64", GitTreeState:"clean", BuildDate:"2020-11-06T18:22:22Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
```

**What is your Helm version?**:

```console
$ helm version
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

**Comment by thesuperzapper** [comment]
@rg2609 as stated [in the README](https://github.com/airflow-helm/charts/tree/main/charts/airflow#option-2a---persistentvolume) you must use a PVC which supports `accessMode = ReadWriteMany`, you are attempting to use one with `accessMode = ReadWriteOnce`.

**Comment by MPParsley** [comment]
> @rg2609 as stated [in the README](https://github.com/airflow-helm/charts/tree/main/charts/airflow#option-2a---persistentvolume) you must use a PVC which supports `accessMode = ReadWriteMany`, you are attempting to use one with `accessMode = ReadWriteOnce`.

Ran into the same issue on OpenShift, fixed by setting accessMode = ReadWriteMany:
````
dags:
  persistence:
    enabled: true
    accessMode: ReadWriteMany
```

@thesuperzapper, the documentation may have changed as I only see "ReadWriteOnce" mentioned?
