### ISSUE TITLE
specify externalDatabase username from Secret (improves PostgresOperator support)

### ISSUE THREAD

**Issue by aodj** [airflow-helm/charts#511]
### Checks

- [X] I have checked for [existing issues](https://github.com/airflow-helm/charts/issues).

### Motivation

For anyone using the [PostgresOperator](https://opensource.zalando.com/postgres-operator/) it's not possible to use the credentials that the operator creates for the `externalDatabase` connection.

The operator creates secrets that represent user accounts and they contain two keys: `username` and `password`. With the design of the `externalDatabase` block it's no problem to reference the secret and reference the password value, but the same is not true for the username, since it is required to be hardcoded into the Airflow chart.

### Implementation

Allow the setting of two new settings, `externalDatabase.userSecret` and `externalDatabase.userSecretKey` that allow the use of usernames stored in a secret.

The use of the `externalDatabase.user` would have priority over the secret reference, but would allow the chart to work against a well known Kubernetes operator.

### Are you willing & able to help?

- [X] I am able to submit a PR!
- [X] I can help test the feature!

**Comment by thesuperzapper** [comment]
@aodj this is a good idea, I am happy if you raise a PR to add these values.
