### ISSUE TITLE
git-sync side-car init container failed to fetch dags from private Git repository

### ISSUE THREAD

**Issue by saip50** [airflow-helm/charts#518]
### Checks

- [X] I have checked for [existing issues](https://github.com/airflow-helm/charts/issues).
- [X] This report is about the [user-community Airflow Helm Chart](https://github.com/airflow-helm/charts/tree/main/charts/airflow).

### Chart Version

8.5.3

### Kubernetes Version

```shell
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:41:28Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"windows/amd64"}

Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-18T19:30:35Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
```

### Helm Version

```shell
version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.16.9"}
```

### Description

we have deployed airflow v2.1.4 in AKS. 
currently, we had migrated our airflow repo to GitHub private repo.
we made changes mentioned in the document **https://github.com/airflow-helm/charts/tree/main/charts/airflow**
for git-sync side-car container using SSH auth. 
but we are getting error as mentioned below in **git-sync init container** as its not able to clone our **/dags** repo popping out issue as "**permission denied**" which in turn throwing exception as "**context deadline exceeded**".

we have created secrets using the command: kubectl create secret generic <secert_name> --from-file=id_rsa=<private_key_path> --from-file=known_hosts=<known_hosts_path> --from-file=id_rsa.pub=<public_key_host>
Also, we have added our public key in GitHub airflow repo->settings->deploy keys.

### Relevant Logs

```shell
-> outpout of kubectl logs -f airflow-scheduler-pod -c dags-git-clone
INFO: detected pid 1, running init handler
I0208 13:06:15.255709      12 main.go:430]  "level"=0 "msg"="starting up"  "args"=["/git-sync"] "pid"=12
I0208 13:06:15.255962      12 main.go:694]  "level"=0 "msg"="cloning repo"  "origin"="git@github.com:ey-org/brdf-airflow.git" "path"="/dags"
E0208 13:08:24.672681      12 main.go:455]  "msg"="too many failures, aborting" "error"="Run(git clone --no-checkout -b development --depth 1 git@github.com:ey-org/brdf-airflow.git /dags): context deadline exceeded: { stdout: \"\", stderr: \"Cloning into '/dags'...\\n\" }"  "failCount"=0
------------------------------------------------------------------------------------
-> output of kubectl describe pod airflow-scheduler-pod
 Normal   Pulling    14m (x5 over 20m)     kubelet            Pulling image "k8s.gcr.io/git-sync/git-sync:v3.2.2"
  Warning  BackOff    4m44s (x41 over 18m)  kubelet            Back-off restarting failed container
---------------------------------------------------------------------------------------
-> output of kubectl describe pod airflow-web-pod
 Warning  Unhealthy  23m                   kubelet            Liveness probe failed: Get "http://10.0.8.12:8080/health": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  Warning  BackOff    2m13s (x59 over 21m)  kubelet            Back-off restarting failed container
```

**Comment by saip50** [comment]
> ### Checks
> * [x]  I have checked for [existing issues](https://github.com/airflow-helm/charts/issues).
> * [x]  This report is about the [user-community Airflow Helm Chart](https://github.com/airflow-helm/charts/tree/main/charts/airflow).
> 
> ### Chart Version
> 8.5.3
> 
> ### Kubernetes Version
> ```shell
> Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:41:28Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"windows/amd64"}
> 
> Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-18T19:30:35Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
> ```
> 
> ### Helm Version
> ```shell
> version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.16.9"}
> ```
> 
> ### Description
> we have deployed airflow v2.1.4 in AKS. currently, we had migrated our airflow repo to GitHub private repo. we made changes mentioned in the document **https://github.com/airflow-helm/charts/tree/main/charts/airflow** for git-sync side-car container using SSH auth. but we are getting error as mentioned below in **git-sync init container** as its not able to clone our **/dags** repo popping out issue as "**permission denied**" which in turn throwing exception as "**context deadline exceeded**".
> 
> we have created secrets using the command: kubectl create secret generic <secert_name> --from-file=id_rsa=<private_key_path> --from-file=known_hosts=<known_hosts_path> --from-file=id_rsa.pub=<public_key_host> Also, we have added our public key in GitHub airflow repo->settings->deploy keys.
> 
> ### Relevant Logs
> ```shell
> -> outpout of kubectl logs -f airflow-scheduler-pod -c dags-git-clone
> INFO: detected pid 1, running init handler
> I0208 13:06:15.255709      12 main.go:430]  "level"=0 "msg"="starting up"  "args"=["/git-sync"] "pid"=12
> I0208 13:06:15.255962      12 main.go:694]  "level"=0 "msg"="cloning repo"  "origin"="git@github.com:ey-org/brdf-airflow.git" "path"="/dags"
> E0208 13:08:24.672681      12 main.go:455]  "msg"="too many failures, aborting" "error"="Run(git clone --no-checkout -b development --depth 1 git@github.com:ey-org/brdf-airflow.git /dags): context deadline exceeded: { stdout: \"\", stderr: \"Cloning into '/dags'...\\n\" }"  "failCount"=0
> ------------------------------------------------------------------------------------
> -> output of kubectl describe pod airflow-scheduler-pod
>  Normal   Pulling    14m (x5 over 20m)     kubelet            Pulling image "k8s.gcr.io/git-sync/git-sync:v3.2.2"
>   Warning  BackOff    4m44s (x41 over 18m)  kubelet            Back-off restarting failed container
> ---------------------------------------------------------------------------------------
> -> output of kubectl describe pod airflow-web-pod
>  Warning  Unhealthy  23m                   kubelet            Liveness probe failed: Get "http://10.0.8.12:8080/health": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
>   Warning  BackOff    2m13s (x59 over 21m)  kubelet            Back-off restarting failed container
> ```
> 
> ### Custom Helm Values
> _No response_

**Comment by thesuperzapper** [comment]
@saip50 can you verify that `git clone` runs correctly when using the same SSH keys on your laptop (or in an `ubuntu` docker container if your laptop already has the required git auth)?

**Comment by saip50** [comment]
@thesuperzapper yes I am able to clone using same SSH Keys with git clone.
And also my git-sync side car configs as below:

configs:
AIRFLOW__SCHEDULER__SCHEDULER_HEALTH_CHECK_THRESHOLD: "600"
AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL: "60"

gitSync:
  
    enabled: true
    image:
      repository: k8s.gcr.io/git-sync/git-sync
      tag: v3.2.2
      pullPolicy: Always
      uid: 65533
      gid: 65533
    resources: {}
    repo: "git@github.com:ey-org/brdf-airflow.git"
    repoSubPath: ""
    branch: development
    revision: HEAD
    depth: 1
    syncWait: 60
    syncTimeout: 120
    httpSecret: ""
    httpSecretUsernameKey: username
    httpSecretPasswordKey: password
    sshSecret: repo-creds
    sshSecretKey: id_rsa
    sshKnownHosts: |-
      github.com ssh-rsa xxxx
    maxFailures: 0
-------------------------------------------------------------------------------------    
also the readiness and liveness probes as follows:
 ## configs for the **scheduler Pods' liveness probe**
  ## - `periodSeconds` x `failureThreshold` = max seconds a scheduler can be unhealthy
  ##
  livenessProbe:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 30
    timeoutSeconds: 60
    failureThreshold: 5

## configs for the **web Pods' readiness probe**
  ##
  readinessProbe:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6

  ## configs for the **web Pods' liveness probe**
  ##
  livenessProbe:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6

**Comment by thesuperzapper** [comment]
@saip50 can you use `kubectl get --namespace xxxxx secret/secret-key-name -o yaml` and then base64 decode the `id_rsa` key, and make sure this is exactly the same as your key you verified locally?

**Comment by saip50** [comment]
@thesuperzapper I verified doing the same and key is same key which I am using to clone locally, and I was able to clone too.

But inside the container getting issue as in attached image. please help.
<img width="947" alt="Screenshot_2" src="https://user-images.githubusercontent.com/89022002/153159913-c18a39ae-7e37-49dc-8061-a3d25f953eac.png">

**Comment by saip50** [comment]
@thesuperzapper can you please help us with the issue?
we tried all possible ways following the document https://github.com/airflow-helm/charts/tree/main/charts/airflow.
but nothing seems to be worked out.

**Comment by thesuperzapper** [comment]
@saip50 can you try updating the `dags.gitSync.image.tag` to `v3.4.0`, I have a feeling that https://github.com/kubernetes/git-sync/pull/473 (which was included in `v3.4.0`) will fix your issue.

If it works, can you report back?

**Comment by saip50** [comment]
@thesuperzapper may be this is the issue.
![image](https://user-images.githubusercontent.com/89022002/153363524-987296d2-8003-485c-9eb0-b361c0258d9b.png)

how can i change this ownership to airflow user from root because I am not able to change ownership as I am running as airflow user and not able to change to root user.

**Comment by thesuperzapper** [comment]
@saip50 the `dags` folder is owned by root because it is an `emptyDir` volume mounted by Kubernetes (hence why https://github.com/kubernetes/git-sync/pull/473 should fix your issue). 

But yea, if you manually clear that `dags` folder (or just delete the Pod), it should fix whatever corruption there is in the `dags` folder.

---

I assume you mean the `helm upgrade` returns `UPGRADE FAILED: timed out waiting for the condition`, check that the Pods are actually using the `v3.4.0` container.

**Comment by saip50** [comment]
@thesuperzapper we are able to deploy airflow without enabling git-sync side car which doesn't have any dags. but if we are using git-sync side car then deployment is unsuccessful facing same permission issue as mentioned above.
git-sync image tag: v3.4.0
airflow image tag: v2.1.0

**Comment by saip50** [comment]
@thesuperzapper after using git-sync v3.4.0 the pods are not initialising its stated as "##[error]Error: UPGRADE FAILED: timed out waiting for the condition". all other pods are waiting for git-sync to initialise so scheduler and db-migrations pods are failing. please look into the live logs attached. 

any solution for this?
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/89022002/155658535-c0523a8e-175f-4062-9d8a-144e34b28ff3.png)

**Comment by thesuperzapper** [comment]
@saip50 can you `kubectl describe` one of the Pods with git-sync?

Are the `dags-git-clone` init-containers succeeding, or are they failing also?

If any of the containers within any of the pods are succeeding to run, can you try kubectl exec` into a bash shell and see if your dags are there?

**Comment by saip50** [comment]
@thesuperzapper currently only pgbouncer pod is running. all other pods are crashing off at initialization stage itself.

dags-git-clone init-containers are not succeeding because of that all others containers are in waiting for podinitialization.

currently, only pgbouncer pod us running and doing kubectl exec inside that found there are no dags present.

attached kubectl describe of one of pods.
[describe.txt](https://github.com/airflow-helm/charts/files/8140099/describe.txt)

**Comment by saip50** [comment]
@thesuperzapper can you please provide the way in which we can move forward w.r.t the issue.

**Comment by saip50** [comment]
@thesuperzapper @hmike96 any follow up for the git-sync issue. the container is not initializing at all. we also tried making a custom init container to run until git-sync container starts.

**Comment by lskrajny** [comment]
Have the same problem:

plwa10020:misc kubectl logs airflow-worker-0  dags-git-sync
INFO: detected pid 1, running init handler
I0307 16:58:59.555320      14 main.go:430]  "level"=0 "msg"="starting up"  "args"=["/git-sync"] "pid"=14
I0307 16:58:59.555392      14 main.go:694]  "level"=0 "msg"="cloning repo"  "origin"="ssh://git@git.int.kn/ltic/dags.git" "path"="/dags"
E0307 17:01:09.681790      14 main.go:455]  "msg"="too many failures, aborting" "error"="Run(git clone --no-checkout -b master --depth 1 ssh://git@git.int.kn/ltic/dags.git /dags): context deadline exceeded: { stdout: \"\", stderr: \"Cloning into '/dags'...\\n\" }"  "failCount"=0

**Comment by thesuperzapper** [comment]
@saip50 @lskrajny it's probably caused by a simple timeout during git-clone then, try increasing `dags.gitSync.syncTimeout` from `120` to something way higher like `300` (which is 5 minutes).

__WARNING:__ if your repos are taking multiple minutes to sync, you will have a bad time if you are using the airflow KubernetesExecutor, as this will make literally every task will take minutes to run (as each task needs to clone the whole dags repo into its Pod before the task can run).

----

If that doesn't work, please also try the newer git-sync image [v3.5.0](https://github.com/kubernetes/git-sync/releases/tag/v3.5.0) by setting `dags.gitSync.image.tag` to `v3.5.0`.

**Comment by saip50** [comment]
resolved. thank you!
