### ISSUE TITLE
Webserver initial user creation in secret

### ISSUE THREAD

**Issue by vjvel** [airflow-helm/charts#536]
### Checks

- [X] I have checked for [existing issues](https://github.com/airflow-helm/charts/issues).

### Motivation

can you please let me know if there is any option to pass secretname for the creating the initial user for the webserver deployment in airflow,

currently i can see the option to pass clear text in values file.

### Are you willing & able to help?

- [x] I am able to submit a PR!
- [ ] I can help test the feature!

**Comment by thesuperzapper** [comment]
@vjvel yes! 

You can use the `airflow.usersTemplates` value, please see the ["How to create airflow users?"](https://github.com/airflow-helm/charts/tree/main/charts/airflow#how-to-create-airflow-users) FAQ.
