### ISSUE TITLE
Airflow Webserver Replicas

### ISSUE THREAD

**Issue by aashishadhh** [airflow-helm/charts#542]
### Checks

- [X] I have checked for [existing issues](https://github.com/airflow-helm/charts/issues).
- [X] I have looked through the [FAQ](https://github.com/airflow-helm/charts/tree/main/charts/airflow#faq---airflow).

### Question

I would like to understand why the number of airflow webserver pods is always 1 even if we set the `web.replicas` = `3`

**Comment by thesuperzapper** [comment]
@aashishadhh this is because the correct value is `web.replicas` not `webserver.replicas`.

**Comment by aashishadhh** [comment]
Oops mistake on the thread.
I have been using web.replicas = 3 and the issue is same.
Went through the previous issues, tried adding a static web server key and still the number of web server pod running is 1.
But when i edited the deployment using kubectl edit airflow-webserver then updated the replicas to 2 then two pods for webserver started running

**Comment by thesuperzapper** [comment]
@aashishadhh I just tested, and multiple replicas is working fine.

Can you show your `values.yaml`?

**Comment by aashishadhh** [comment]
@thesuperzapper the recent one that i tested.

helm upgrade --install airflow apache-airflow/airflow --namespace airflowtest2 -f ./test.yaml --debug

test.yaml file:

```
defaultAirflowTag: "2.2.2"
airflowVersion: "2.2.2"
executor: KubernetesExecutor
web:
  replicas: 2
```
_kubectl get deployments -n airflowtest2_

```
NAME                READY   UP-TO-DATE   AVAILABLE   AGE
airflow-scheduler   1/1     1            1           3h5m
airflow-statsd      1/1     1            1           3h5m
airflow-triggerer   1/1     1            1           3h5m
airflow-webserver   1/1     1            1           3h5m
```

**Comment by thesuperzapper** [comment]
@aashishadhh you are installing the "official" chart (which lives in the `apache/airflow` GitHub repo), this repo is for the "user-community" chart.
