### ISSUE TITLE
Command error with Airflow v2

### ISSUE THREAD

**Issue by cventr-agilelab** [airflow-helm/charts#55]
**What is the bug?**

Running airflow-helm with airflow 2 throws the following error.

```
airflow command error: argument GROUP_OR_COMMAND: `airflow worker` command, has been removed, please use `airflow celery worker`, see help above.
```

I think the problem lies in here: https://github.com/airflow-helm/charts/blob/7c46d8785ecd33e30110f2a0d3cdc3faabf1a7d1/charts/airflow/templates/worker/worker-statefulset.yaml#L228

**What are your Helm values?**

```
image:
    repository: apache/airflow
    tag: 2.0.0-python3.6
```

**What is your Kubernetes Version?**:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.12-eks-7684af", GitCommit:"7684af4ac41370dd109ac13817023cb8063e3d45", GitTreeState:"clean", BuildDate:"2020-10-20T22:57:40Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**What is your Helm version?**:

```console
$ helm version
WARNING: "kubernetes-charts.storage.googleapis.com" is deprecated for "stable" and will be deleted Nov. 13, 2020.
WARNING: You should switch to "https://charts.helm.sh/stable" via:
WARNING: helm repo add "stable" "https://charts.helm.sh/stable" --force-update
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"clean", GoVersion:"go1.14.13"}
```

**Comment by thesuperzapper** [comment]
Please see https://github.com/airflow-helm/charts/issues/58 to track progress on the Airflow 2.0 support.

**Comment by dandumit** [comment]
how was this fixed ?  I have deployed this image on docker- synology and it stops imediately. how could I fix it ?

**Comment by thesuperzapper** [comment]
@dandumit this issue was for the [Airflow Helm Chart (User-Community)](https://github.com/airflow-helm/charts/tree/main/charts/airflow), which deploys onto Kubernetes, not Docker.

If you ARE using the `Airflow Helm Chart (User-Community)`, please just use the [latest version of the chart](https://github.com/airflow-helm/charts/blob/main/charts/airflow/CHANGELOG.md), as this will work with Airflow 2.X.
