### ISSUE TITLE
Is there support for hybrid CeleryKubernetes Executor ?

### ISSUE THREAD

**Issue by t0il3ts0ap** [airflow-helm/charts#59]
**What is your question?**
Is there support for hybrid [CeleryKubernetes Executor ](https://airflow.apache.org/docs/apache-airflow/stable/executor/celery_kubernetes.html) ?

According to comments in helm chart:

```
  ## the airflow executor type to use
  ##
  ## NOTE:
  ## - this should be `CeleryExecutor` or `KubernetesExecutor`
  ## - if set to `KubernetesExecutor`:
  ##   - ensure that `workers.enabled` is `false`
  ##   - ensure that `flower.enabled` is `false`
  ##   - ensure that `redis.enabled` is `false`
  ##   - ensure that K8S configs are set in `airflow.config`
  ##   - we set these configs automatically:
  ##     - `AIRFLOW__KUBERNETES__NAMESPACE`
  ##     - `AIRFLOW__KUBERNETES__WORKER_SERVICE_ACCOUNT_NAME`
  ##     - `AIRFLOW__KUBERNETES__ENV_FROM_CONFIGMAP_REF`
  ##
  executor: CeleryExecutor
```

**Comment by t0il3ts0ap** [comment]
After checking airflow code/documentation it seems, CeleryKubernetes Executor is available from airflow 2.0

**Comment by thesuperzapper** [comment]
We should discuss this more in the Airflow 2.0 thread: https://github.com/airflow-helm/charts/issues/58

**Comment by thesuperzapper** [comment]
@t0il3ts0ap the `CeleryKubernetesExecutor` is natively supported after version `8.0.0` of the chart.

If you encounter any specific issues, feel free to raise a new issue.
