### ISSUE TITLE
upgrading from stable/airflow

### ISSUE THREAD

**Issue by mikys-next-insurance** [airflow-helm/charts#6]
I have an existing Airflow installation on our Kubernetes cluster.
Can I upgrade it to the new chart without uninstallaing & reinstalling?

**Comment by thesuperzapper** [comment]
@mikys-next-insurance Yes, just follow the [usage guide](https://github.com/airflow-helm/charts/tree/main/charts/airflow#usage) and everything should work properly (installing over an existing install), as helm is only used to generate YAML, and the YAML hasn't changed.

NOTE: I have only tested this with Helm 3.

**Comment by mikys-next-insurance** [comment]
@thesuperzapper , I don't see anything on installing over an existing install in the usage guide. Can you please elaborate?

**Comment by thesuperzapper** [comment]
@mikys-next-insurance, what I mean, is that you literally don't have to do anything (if you are using Helm 3).

You just run these commands to do an upgrade, (as if you were using the old stable repo):
```
helm repo add airflow-stable https://airflow-helm.github.io/charts
helm repo update

helm upgrade \
  [RELEASE_NAME] \
  airflow-stable/airflow \
  --version [VERSION] \
  --namespace [NAMESPACE] \
  --values ./custom-values.yaml
```

__WARNING:__ ensure you check [UPGRADE.md](https://github.com/airflow-helm/charts/blob/main/charts/airflow/UPGRADE.md) for any breaking changes (the version numbers are the same as the old chart)
