### ISSUE TITLE
[GitSync and GitClone] Use shallow clone and single branch

### ISSUE THREAD

**Issue by povode** [airflow-helm/charts#60]
**What is your feature request?**

For the Git Sync and Git Clone it would be helpful to use shallow clone (only clone the blobs and not the entire history) this goes with the single branch option.
https://git-scm.com/docs/shallow
https://git-scm.com/docs/git-clone#Documentation/git-clone.txt---depthltdepthgt

**What alternatives have you considered?**
Moving DAGs out of the monorepo into a separate repository.

**Comment by povode** [comment]
Hello @gsemet  and @thesuperzapper thank you for your effort, this helm chart has been very useful.

I have a simple change that would be very helpful in my use case. We have a massive monorepo and syncing all the history doesn't make much sense.

**Comment by povode** [comment]
completely forgot about this one, sorry for the delay I'll try to finish it this week.

**Comment by thesuperzapper** [comment]
This is now the default behaviour after version `8.0.0` of the chart, you can customise it with the `dags.gitSync.depth` value.
