### ISSUE TITLE
The worker_log_server_port option in [celery] has been moved to the worker_log_server_port option in [logging]

### ISSUE THREAD

**Issue by artful88533** [airflow-helm/charts#604]
### Checks

- [X] I have checked for [existing issues](https://github.com/airflow-helm/charts/issues).
- [X] This report is about the [`User-Community Airflow Helm Chart`](https://github.com/airflow-helm/charts/tree/main/charts/airflow).

### Chart Version

8.6.0

### Kubernetes Version

```shell
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7", GitCommit:"132a687512d7fb058d0f5890f07d4121b3f0a2e2", GitTreeState:"clean", BuildDate:"2021-05-12T12:40:09Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7", GitCommit:"132a687512d7fb058d0f5890f07d4121b3f0a2e2", GitTreeState:"clean", BuildDate:"2021-05-12T12:32:49Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
```

### Helm Version

```shell
version.BuildInfo{Version:"v3.6.2", GitCommit:"ee407bdf364942bcb8e8c665f82e15aa28009b71", GitTreeState:"dirty", GoVersion:"go1.16.5"}
```

### Description

Hello!
I've got warning
`WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/configuration.py:357 DeprecationWarning: The worker_log_server_port option in [celery] has been moved to the worker_log_server_port option in [logging] - the old setting has been used, but please update your config.`

Could you move worker_log_server_port from [celery] to [logging], please
`AIRFLOW__CELERY__WORKER_LOG_SERVER_PORT > AIRFLOW__LOGGING__WORKER_LOG_SERVER_PORT`
https://github.com/airflow-helm/charts/blob/airflow-8.6.0/charts/airflow/templates/config/secret-config-envs.yaml#L164

https://airflow.apache.org/docs/apache-airflow/2.3.1/release_notes.html#airflow-2-2-0-2021-10-11

Thank you!

**Comment by thesuperzapper** [comment]
@artful88533 thanks for raising this! 

I actually made this fix in a branch, but forgot to make the PR to `main`, lol!

Find the PR here https://github.com/airflow-helm/charts/pull/608, which will be part of chart version `8.6.1`.

**Comment by thesuperzapper** [comment]
@artful88533 the long-belated `8.6.1` is now out, and includes this fix!
