### ISSUE TITLE
unable to fetch logs from airflow console

### ISSUE THREAD

**Issue by saip50** [airflow-helm/charts#613]
### Checks

- [X] I have checked for [existing issues](https://github.com/airflow-helm/charts/issues).
- [X] This report is about the [`User-Community Airflow Helm Chart`](https://github.com/airflow-helm/charts/tree/main/charts/airflow).

### Chart Version

8.6.0

### Kubernetes Version

```shell
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:41:28Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"ba58f86b00f6b0f0b7694a75464aa7806f8bf6fc", GitTreeState:"clean", BuildDate:"2022-03-30T23:40:46Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
```

### Helm Version

```shell
version.BuildInfo{Version:"v3.7.1", GitCommit:"1d11fcb5d3f3bf00dbe6fe31b8412839a96b3dc4", GitTreeState:"clean", GoVersion:"go1.16.9"}
```

### Description

upgraded airflow version from 2.0.1 to 2.2.5. After upgrading, we aren't able to fetch logs from airflow console.
we were able to configure remote logging but need an solution to fetch logs in UI.
airflow image: 2.2.5-python3.8

![image](https://user-images.githubusercontent.com/89022002/174771749-b862e47c-9466-4ca4-bed8-fa637b3f7fef.png)

**Comment by saip50** [comment]
@thesuperzapper only for the failed dags we aren't able to see logs.
Also, we are using KubernetesExecutor.

**Comment by thesuperzapper** [comment]
@saip50 can you see the logs of tasks that are "running"?

---

The problem with logs in KubernetsExecutor is that if the Pod suddenly fails (for example, crashes from lack of memory), it will never upload its logs to the remote provider.

To keep logs in these cases, you can [mount a PVC to all the pods](https://github.com/airflow-helm/charts/blob/main/charts/airflow/docs/faq/monitoring/log-persistence.md#option-1---persistent-volume-claim), but this has some drawbacks:
- it requires a `ReadWriteMany` StorageClass
- all the tasks will mount and write to the same volume (potentially overloading it in LARGE-scale cases)

**Comment by saip50** [comment]
@thesuperzapper double checked, we aren't able to see logs of any running/failed/success tasks.
Any solution for getting logs in console instead mounting a PVC? 

Also,  two things on PVC's:
1. can we mount azure file storage to logs and tasks or only blob storage is supported.
2.  use case: we have azure file storage containing large data's and we need to access those from airflow. how do we integrate file storage to airflow?

**Comment by saip50** [comment]
> @thesuperzapper double checked, we aren't able to see logs of any running/failed/success tasks. Any solution for getting logs in console instead mounting a PVC?
> 
> Also, need to confirm two things on PVC's:
> 
> 1. can we mount azure file storage to logs and tasks or only blob storage is supported.
> 2. use case: we have azure file storage containing large data's and we need to access those from airflow. how do we integrate file storage to airflow?

@thesuperzapper any solution on the above query also please clarify on the above points
