### ISSUE TITLE
Airflow keycloak sso logins failed

### ISSUE THREAD

**Issue by rg2609** [airflow-helm/charts#623]
### Checks

- [ ] I have checked for [existing issues](https://github.com/airflow-helm/charts/issues).
- [x] This report is about the [`User-Community Airflow Helm Chart`](https://github.com/airflow-helm/charts/tree/main/charts/airflow).

### Chart Version

version: 7.16.0

### Kubernetes Version

```shell
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"clean", BuildDate:"2022-06-15T14:22:29Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.9", GitCommit:"3396beebcd97ed3b01f57127fba1b8565b311acb", GitTreeState:"clean", BuildDate:"2022-06-04T17:58:54Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
```

### Helm Version

```shell
version.BuildInfo{Version:"v3.9.0", GitCommit:"7ceeda6c585217a19a1131663d8cd1f7d641b2a7", GitTreeState:"clean", GoVersion:"go1.17.5"}
```

### Description

Trying to set up the Keycloak SSO login with airflow but It's giving an error `ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get issuer certificate (_ssl.c:1131)`

**Comment by thesuperzapper** [comment]
@rg2609 we will need more information to help, can you please share (sanitized) versions of your `webserver_config.py`?
