### ISSUE TITLE
Unable to see the logs in airflow UI

### ISSUE THREAD

**Issue by lovenishgoyal** [airflow-helm/charts#626]
### Checks

- [X] I have checked for [existing issues](https://github.com/airflow-helm/charts/issues).
- [X] This report is about the [`User-Community Airflow Helm Chart`](https://github.com/airflow-helm/charts/tree/main/charts/airflow).

### Chart Version

2.2.3

### Kubernetes Version

```shell
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.16-eks-de875a99", GitCommit:"de875a995f7da9bbc6c47660b3cccf622e8ae60f", GitTreeState:"clean", BuildDate:"2022-05-11T23:16:06Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```

### Helm Version

```shell
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"dirty", GoVersion:"go1.16.6"}
```

### Description

After upgrading airflow 2.1.1 to 2.2.3, we started seeing issue while seeing the tasks logs on UI. 

we have tried with  the config to set "web server secret key" in values.yml 

webserverSecretKey: "134b0d88-041e-11"

`*** Log file does not exist: /opt/airflow/logs/lovenish_sample2/mid/2022-07-15T09:31:29.163998+00:00/1.log
*** Fetching from: http://airflow-worker-0.airflow-worker.airflow.svc.cluster.local:8793/log/lovenish_sample2/mid/2022-07-15T09:31:29.163998+00:00/1.log
*** !!!! Please make sure that all your Airflow components (e.g. schedulers, webservers and workers) have the same 'secret_key' configured in 'webserver' section !!!!!
****** See more at https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#secret-key
****** Failed to fetch log file from worker. 403 Client Error: FORBIDDEN for url: http://airflow-worker-0.airflow-worker.airflow.svc.cluster.local:8793/log/lovenish_sample2/mid/2022-07-15T09:31:29.163998+00:00/1.log
For more information check: https://httpstatuses.com/403`

**Comment by vedprakash0505** [comment]
facing the same issue

**Comment by lovenishgoyal** [comment]
@vbehar @Alien2150 @desaintmartin can you plz help

**Comment by lovenishgoyal** [comment]
@thesuperzapper can you help us?

**Comment by thesuperzapper** [comment]
> @thesuperzapper can you help us?

@lovenishgoyal what version of the chart are you using (NOTE: this is different from the version of airflow).

Can you also provide any `custom-values.yaml` you have set (remove sensitive values)?

**Comment by thesuperzapper** [comment]
@lovenishgoyal @vedprakash0505 I bet I know the problem, are you using the `airflow.webserverSecretKey` value, or `airflow.extraEnv` ([see options here](https://github.com/airflow-helm/charts/blob/main/charts/airflow/docs/faq/security/set-webserver-secret-key.md))?

Because, if you are using `airflow.extraEnv`, and your Secret has been updated, you will need to __manually restart all the Airflow Pods__ because environment variable changes are only picked up on Pod restarts. 

___NOTE:__ with `airflow.webserverSecretKey`, we actually force a restart of all the pods if you change it, so this won't be the problem if you are using that value._

**Comment by lovenishgoyal** [comment]
We are using airflow.webserverSecretKey value, and tried restarting all components but no luck.

I will share the custom values in some time.

**Comment by lovenishgoyal** [comment]
`fullnameOverride: ""

nameOverride: ""

uid: 50000
gid: 0

airflowHome: /opt/airflow

defaultAirflowRepository: apache/airflow

defaultAirflowTag: "2.2.2"

airflowVersion: "2.2.2"

images:
  airflow:
    repository: XXXXXXXX.dkr.ecr.ap-south-1.amazonaws.com/dp-airflow
    tag: v11
    pullPolicy: IfNotPresent
  pod_template:
    repository: ~
    tag: ~
    pullPolicy: IfNotPresent
  flower:
    repository: ~
    tag: ~
    pullPolicy: IfNotPresent
  statsd:
    repository: apache/airflow
    tag: airflow-statsd-exporter-2021.04.28-v0.17.0
    pullPolicy: IfNotPresent
  redis:
    repository: redis
    tag: 6-buster
    pullPolicy: IfNotPresent
  pgbouncer:
    repository: apache/airflow
    tag: airflow-pgbouncer-2021.04.28-1.14.0
    pullPolicy: IfNotPresent
  pgbouncerExporter:
    repository: apache/airflow
    tag: airflow-pgbouncer-exporter-2021.04.28-0.5.0
    pullPolicy: IfNotPresent
  gitSync:
    repository: k8s.gcr.io/git-sync/git-sync
    tag: v3.3.0
    pullPolicy: IfNotPresent

nodeSelector:
  "topology.kubernetes.io/zone" : "ap-south-1a"
  "kubernetes.io/hostname" : "ip-XXXXXXXXX.ap-south-1.compute.internal"
affinity: { }
tolerations: [ ]

labels: { }

ingress:
  enabled: true

  web:
    annotations:
      kubernetes.io/ingress.class: nginx-internal

    path: "/"

    host: "dp-airflow-server.corp.XXXXXX.com"

    tls:
      enabled: false
      secretName: ""

    precedingPaths: [ ]

    succeedingPaths: [ ]

  flower:
    annotations:
      kubernetes.io/ingress.class: nginx-internal

    path: "/"

    host: "dp-airflow-flower.corp.XXXXXXX.com"

    tls:
      enabled: false
      secretName: ""

    precedingPaths: [ ]

    succeedingPaths: [ ]

networkPolicies:
  enabled: false

airflowPodAnnotations: { }

airflowConfigAnnotations: { }

airflowLocalSettings: ~

rbac:
  create: true

executor: "CeleryExecutor"

allowPodLaunching: true

env: [ ]

secret: [ ]

extraSecrets: { }

extraConfigMaps: { }


extraEnvFrom: ~

data:
  metadataSecretName: ~
  resultBackendSecretName: ~
  brokerUrlSecretName: ~

  metadataConnection:
    user: airflow
    pass: V_Airflow_1235
    protocol: postgresql
    host: airflow.XXXXXXXXXXX.ap-south-1.rds.amazonaws.com
    port: 5432
    db: airflow
    sslmode: disable
  resultBackendConnection: ~
  brokerUrl: redis://airflow.XXXXXXX.ng.XXXX.aps1.cache.amazonaws.com:6379/

fernetKey: ~
fernetKeySecretName: airflow-fernet-custom-key
webserverSecretKey: "134b0d88-041e-11"


kerberos:
  enabled: false
  ccacheMountPath: /var/kerberos-ccache
  ccacheFileName: cache
  configPath: /etc/krb5.conf
  keytabPath: /etc/airflow.keytab
  principal: airflow@FOO.COM
  reinitFrequency: 3600
  config: |

    [logging]
    default : "FILE:{{ template "airflow_logs_no_quote" . }}/kerberos_libs.log"
    kdc : "FILE:{{ template "airflow_logs_no_quote" . }}/kerberos_kdc.log"
    admin_server : "FILE:{{ template "airflow_logs_no_quote" . }}/kadmind.log"

    [libdefaults]
    default_realm : FOO.COM
    ticket_lifetime : 10h
    renew_lifetime : 7d
    forwardable : true

    [realms]
    FOO.COM : {
      kdc : kdc-server.foo.com
      admin_server : admin_server.foo.com
    }

workers:
  replicas: 2

  command: ~
  args:
    - "bash"
    - "-c"
    - |-
      exec \
      airflow {{ semverCompare ">=2.0.0" .Values.airflowVersion | ternary "celery worker" "worker" }}

  updateStrategy: ~
  strategy:
    rollingUpdate:
      maxSurge: "100%"
      maxUnavailable: "50%"

  serviceAccount:
    create: true
    name: ~
    annotations: { }

  keda:
    enabled: false
    namespaceLabels: { }
    pollingInterval: 5
    cooldownPeriod: 30
    minReplicaCount: 0
    maxReplicaCount: 10

  persistence:
    enabled: true
    size: 10Gi
    storageClassName:
    fixPermissions: true

  kerberosSidecar:
    enabled: false
    resources: { }

  resources: { }

  terminationGracePeriodSeconds: 600

  safeToEvict: true

  extraContainers: [ ]
  extraInitContainers: [ ]

  extraVolumes: [ ]
  extraVolumeMounts: [ ]

  nodeSelector:
    "topology.kubernetes.io/zone" : "ap-south-1a"
    "kubernetes.io/hostname" : "ip-xxxxxxxx.ap-south-1.compute.internal"
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchLabels:
                component: worker
            topologyKey: "kubernetes.io/hostname"
  tolerations: [ ]
  hostAliases: [ ]

  logGroomerSidecar:
    command: ~
    args: [ "bash", "/clean-logs" ]
    resources: { }

scheduler:
  livenessProbe:
    initialDelaySeconds: 10
    timeoutSeconds: 5
    failureThreshold: 10
    periodSeconds: 30
  replicas: 1

  command: ~
  args: [ "bash", "-c", "exec airflow scheduler" ]

  updateStrategy: ~
  strategy: ~

  serviceAccount:
    create: true
    name: ~

    annotations: { }

  podDisruptionBudget:
    enabled: false

    config:
      maxUnavailable: 1

  resources: { }

  safeToEvict: true

  extraContainers: [ ]
  extraInitContainers: []

  extraVolumes: [ ]
  extraVolumeMounts: [ ]

  nodeSelector:
    "topology.kubernetes.io/zone" : "ap-south-1a"
    "kubernetes.io/hostname" : "ip-xxxxxxxxx.ap-south-1.compute.internal"
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchLabels:
                component: scheduler
            topologyKey: "kubernetes.io/hostname"
  tolerations: [ ]

  logGroomerSidecar:
    enabled: true
    command: ~
    args: [ "bash", "/clean-logs" ]
    resources: { }
createUserJob:
  annotations: { }
  jobAnnotations: { }

  serviceAccount:
    create: true
    name: ~

    annotations: { }

  nodeSelector: { }
  affinity: { }
  tolerations: [ ]

migrateDatabaseJob:
  annotations: { }
  jobAnnotations: { }

  serviceAccount:
    create: true
    name: ~

    annotations: { }

  nodeSelector: { }
  affinity: { }
  tolerations: [ ]

webserver:
  allowPodLogReading: true
  livenessProbe:
    initialDelaySeconds: 15
    timeoutSeconds: 30
    failureThreshold: 20
    periodSeconds: 5

  readinessProbe:
    initialDelaySeconds: 15
    timeoutSeconds: 30
    failureThreshold: 20
    periodSeconds: 5

  replicas: 1

  command: ~
  args: [ "bash", "-c", "exec airflow webserver" ]

  serviceAccount:
    create: true
    name: ~

    annotations: { }

  strategy: ~

  extraNetworkPolicies: []
  networkPolicy:
    ingress:
      from: []
      ports:
        - port: airflow-ui

  resources: { }

  defaultUser:
    enabled: true
    role: Admin
    username: admin
    email: lovenish@xxxxxx.com
    firstName: lovenish
    lastName: goyal
    password: xxxxxxxx

  extraContainers: [ ]
  extraInitContainers: [ ]

  extraVolumes: [ ]
  extraVolumeMounts: [ ]

  webserverConfig: ~



  service:
    type: ClusterIP
    annotations: {}
    ports:
      - name: airflow-ui
        port: "{{ .Values.ports.airflowUI }}"
    loadBalancerIP: ~

  nodeSelector:
    "topology.kubernetes.io/zone" : "ap-south-1a"
    "kubernetes.io/hostname" : "ip-xxxxxx.ap-south-1.compute.internal"
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchLabels:
                component: webserver
            topologyKey: "kubernetes.io/hostname"
  tolerations: [ ]

flower:
  enabled: true

  command: ~
  args:
    - "bash"
    - "-c"
    - |-
      exec \
      airflow {{ semverCompare ">=2.0.0" .Values.airflowVersion | ternary "celery flower" "flower" }}

  extraNetworkPolicies: []
  networkPolicy:
    ingress:
      from: []
      ports:
        - port: flower-ui

  resources: {}

  serviceAccount:
    create: true
    name: ~

    annotations: { }

  secretName: ~

  username: ~
  password: ~

  service:
    type: ClusterIP
    annotations: {}
    ports:
      - name: flower-ui
        port: "{{ .Values.ports.flowerUI }}"
    loadBalancerIP: ~

  extraContainers: []
  extraVolumes: []

  nodeSelector:
    "topology.kubernetes.io/zone" : "ap-south-1a"
    "kubernetes.io/hostname" : "ip-xxxxxx.ap-south-1.compute.internal"
  affinity: { }
  tolerations: [ ]

statsd:
  enabled: true

  serviceAccount:
    create: true
    name: ~

    annotations: { }

  extraNetworkPolicies: [ ]
  resources: { }

  service:
    extraAnnotations: { }

  nodeSelector:
    "topology.kubernetes.io/zone" : "ap-south-1a"
    "kubernetes.io/hostname" : "ip-xxxxxxx.ap-south-1.compute.internal"
  affinity: { }
  tolerations: [ ]

  extraMappings: [ ]

  uid: 65534

pgbouncer:
  enabled: false

  serviceAccount:
    create: true
    name: ~

    annotations: { }

  extraNetworkPolicies: [ ]

  metadataPoolSize: 10
  resultBackendPoolSize: 5

  maxClientConn: 100

  configSecretName: ~

  podDisruptionBudget:
    enabled: false

    config:
      maxUnavailable: 1

  resources: { }

  service:
    extraAnnotations: { }

  verbose: 0
  logDisconnections: 0
  logConnections: 0

  sslmode: "prefer"
  ciphers: "normal"

  ssl:
    ca: ~
    cert: ~
    key: ~

  extraIniMetadata: ~
  extraIniResultBackend: ~
  extraIni: ~

  nodeSelector: { }
  affinity: { }
  tolerations: [ ]

  uid: 65534

  metricsExporterSidecar:
    resources: { }

redis:
  enabled: false
  terminationGracePeriodSeconds: 600

  serviceAccount:
    create: true
    name: ~

    annotations: { }

  persistence:
    enabled: true
    size: 1Gi
    storageClassName:

  resources: { }

  passwordSecretName: ~

  password: ~

  safeToEvict: true

  nodeSelector: { }
  affinity: { }
  tolerations: [ ]

externalRedis:
  host: "airflow.xxxxx.ng.xxxx.aps1.cache.amazonaws.com"
  port: 6379
  databaseNumber: 15

registry:
  secretName: ~

  connection: { }

elasticsearch:
  enabled: false
  secretName: ~
  connection: { }

ports:
  flowerUI: 5555
  airflowUI: 8080
  workerLogs: 8793
  redisDB: 6379
  statsdIngest: 9125
  statsdScrape: 9102
  pgbouncer: 6543
  pgbouncerScrape: 9127

quotas: { }

limits: [ ]

cleanup:
  enabled: false
  schedule: "*/15 * * * *"

  nodeSelector: { }
  affinity: { }
  tolerations: [ ]

  serviceAccount:
    create: true
    name: ~

    annotations: { }

postgresql:
  enabled: false

externalDatabase:
  type: postgres
  host: airflow.xxxxxxx.ap-south-1.xxxx.amazonaws.com
  port: 5432
  database: airflow
  user: airflow
  passwordSecret: airflow-postgres
  passwordSecretKey: postgresql-password

config:
  core:
    dags_folder: '{{ include "airflow_dags" . }}'
    load_examples: 'False'
    executor: '{{ .Values.executor }}'
    colored_console_log: 'False'
    remote_logging: '{{- ternary "True" "False" .Values.elasticsearch.enabled }}'
    enable_xcom_pickling: True
  api:
    auth_backend: airflow.api.auth.backend.deny_all
  logging:
    remote_logging: '{{- ternary "True" "False" .Values.elasticsearch.enabled }}'
    colored_console_log: 'False'
  metrics:
    statsd_on: '{{ ternary "True" "False" .Values.statsd.enabled }}'
    statsd_port: 9125
    statsd_prefix: airflow
    statsd_host: '{{ printf "%s-statsd" .Release.Name }}'
  webserver:
    enable_proxy_fix: 'True'
    expose_config: False
    rbac: 'True'
    baseUrl: "https://dp-xxxxx-server.corp.xxxxx.com/"
    authenticate: 'True'
    filter_by_owner: 'True'
    auth_backend: "airflow.contrib.auth.backends.google_auth"
  google:
    client_id: "xxxxxxxx.googleusercontent.com"
    client_secret: "xxxxx"
    oauth_callback_route: "/oauth2callback"
    domain: "xxxxxxxx"
  email:
    email_backend : airflow.utils.email.send_email_smtp
  smtp:
    smtp_host : email-smtp.ap-south-1.amazonaws.com
    smtp_starttls : True
    smtp_ssl : False
    smtp_user : xxxxxxx
    smtp_password : xxx+xxx
    smtp_port : 25
    smtp_mail_from : airflow@xxxxxx.com
  celery:
    worker_concurrency: 16
  scheduler:
    statsd_on: '{{ ternary "True" "False" .Values.statsd.enabled }}'
    statsd_port: 9125
    statsd_prefix: airflow
    statsd_host: '{{ printf "%s-statsd" .Release.Name }}'
    run_duration: 41460
  elasticsearch:
    json_format: 'True'
    log_id_template: "{dag_id}_{task_id}_{execution_date}_{try_number}"
  elasticsearch_configs:
    max_retries: 3
    timeout: 30
    retry_timeout: 'True'
  kerberos:
    keytab: '{{ .Values.kerberos.keytabPath }}'
    reinit_frequency: '{{ .Values.kerberos.reinitFrequency }}'
    principal: '{{ .Values.kerberos.principal }}'
    ccache: '{{ .Values.kerberos.ccacheMountPath }}/{{ .Values.kerberos.ccacheFileName }}'
  kubernetes:
    namespace: '{{ .Release.Namespace }}'
    airflow_configmap: '{{ include "airflow_config" . }}'
    airflow_local_settings_configmap: '{{ include "airflow_config" . }}'
    pod_template_file: '{{ include "airflow_pod_template_file" . }}/pod_template_file.yaml'
    worker_container_repository: '{{ .Values.images.airflow.repository | default .Values.defaultAirflowRepository }}'
    worker_container_tag: '{{ .Values.images.airflow.tag | default .Values.defaultAirflowTag }}'
    multi_namespace_mode: '{{ if .Values.multiNamespaceMode }}True{{ else }}False{{ end }}'

multiNamespaceMode: false

podTemplate: ~

dags:
  persistence:
    enabled: true
    size: 10Gi
    accessMode: ReadWriteOnce
    existingClaim:
  gitSync:
    enabled: true

    repo: https://gitlab.xxxxxxx.in/dna/airflow-dags.git
    branch: master
    rev: HEAD
    depth: 1
    maxFailures: 10
    subPath: ""
    credentialsSecret: airflow-git-credentials
    wait: 60
    containerName: git-sync
    uid: 65533
    extraVolumeMounts: [ ]
    env: [ ]
    resources: { }

logs:
  persistence:
    enabled: false
    size: 10Gi
    storageClassName:
    existingClaim:
airflow:
  extraPipPackages:
    - "airflow-exporter~=1.4.1"
    - "torch~=1.8.0"
    - "apache-airflow[statsd]"`

**Comment by lovenishgoyal** [comment]
@thesuperzapper plz find the details

**Comment by thesuperzapper** [comment]
@lovenishgoyal I believe you are actually using the "official" chart (found in the `apache/airflow` repo), not the "user-community" one from this `airflow-helm/charts` repo.

The values structures of these charts are different, can you confirm which one you are installing?

NOTE: if you want to use the official one, please raise any issues in their issue tracker.

**Comment by lovenishgoyal** [comment]
Sure, Let me check with them
