### ISSUE TITLE
Add option to specify private pip repository

### ISSUE THREAD

**Issue by vavasilev** [airflow-helm/charts#65]
We have a private pip repository, bu it is not possible to configure extraPipPackages from it.

**Comment by jbgerth** [comment]
Hey @vavasilev, 
I had the same issue. The functionality is already there. Try adding the `PIP_INDEX_URL` or `PIP_EXTRA_INDEX_URL` to your custom helm values under `airflow.config`. That way it is available as a environment variable in the containers and Python will check there as well. 
Alternatively, you could extend the Dockerfile and add the env var there. 

Check the pip docs for more information -> https://docs.readthedocs.io/en/stable/guides/private-python-packages.html#from-a-repository-manager-other-than-pypi

**Comment by vavasilev** [comment]
Thanks a lot!
