### ISSUE TITLE
Support Airflow Version 2.4

### ISSUE THREAD

**Issue by ABombino** [airflow-helm/charts#658]
### Checks

- [X] I have checked for [existing issues](https://github.com/airflow-helm/charts/issues).
- [X] This report is about the [`User-Community Airflow Helm Chart`](https://github.com/airflow-helm/charts/tree/main/charts/airflow).

### Motivation

- Since Airflow it has been released in version 2.4 could be good to have support for this version
- Being update with the changes and with the latest features

### Are you willing & able to help?

- [ ] I am able to submit a PR!
- [ ] I can help test the feature!

**Comment by thesuperzapper** [comment]
@ABombino is there a specific feature missing or an issue you are having with chart version `8.6.1` and airflow 2.4?

FYI, this is also being discussed in https://github.com/airflow-helm/charts/discussions/652#discussioncomment-3892838, and no issues have been reported. If no one finds problems in the next few days, we can probably update the ["supported versions"](https://github.com/airflow-helm/charts/tree/main/charts/airflow#airflow-version-support) table to indicate that airflow 2.4 is supported by chart `8.6.1`.

**Comment by thesuperzapper** [comment]
@ABombino you can just change the [image tag](https://github.com/airflow-helm/charts/blob/420eae29c454f6e7e6a7837706ca2e6c0fe792b8/charts/airflow/sample-values-CeleryExecutor.yaml#L8-L12), for more information, see the docs about ["Set Airflow Version"](https://github.com/airflow-helm/charts/blob/main/charts/airflow/docs/faq/configuration/airflow-version.md).

**Comment by ABombino** [comment]
@thesuperzapper indeed I have deployed arflow with version 2.4.1 and everything is working as expected. Thank you so much for the support. However I think that, as you mentioned above, it could be nice to update the update the ["supported versions](https://github.com/airflow-helm/charts/tree/main/charts/airflow#airflow-version-support)" .
Cheers.

**Comment by thesuperzapper** [comment]
@ABombino thanks for the update, I have updated the ["Airflow Version Support"](https://github.com/airflow-helm/charts/tree/main/charts/airflow#airflow-version-support) table to indicate that chart version 8.6.1+ supports Airflow 2.4.
