### ISSUE TITLE
support to airflow 2.4 

### ISSUE THREAD

**Issue by yossisht9876** [airflow-helm/charts#666]
### Checks

- [X] I have checked for [existing issues](https://github.com/airflow-helm/charts/issues).
- [X] This report is about the [`User-Community Airflow Helm Chart`](https://github.com/airflow-helm/charts/tree/main/charts/airflow).

### Motivation

https://airflow.apache.org/blog/airflow-2.4.0/

New Features and bug fix

### Are you willing & able to help?

- [ ] I am able to submit a PR!
- [X] I can help test the feature!

**Comment by thesuperzapper** [comment]
@yossisht9876 chart version `8.6.1` already supports Airflow `2.4` as far as I know (see the [support matrix](https://github.com/airflow-helm/charts/tree/main/charts/airflow#airflow-version-support)).

Are you having a specific issue?

**Comment by yossisht9876** [comment]
hi @thesuperzapper 
i tried to deploy 2.4.0-python3.8 and 2.4.3-python3.8 with no luck

```ImportError: cannot import name 'escape' from 'jinja2' (/home/airflow/.local/lib/python3.8/site-packages/jinja2/__init__.py)```

**Comment by thesuperzapper** [comment]
@yossisht9876 are you still having an issue?

If so, please provide any custom values.

**Comment by yossisht9876** [comment]
@thesuperzapper still have the same issue
im upgrading packages according to the error log but its never end...
what do you mean by "please provide any custom values" ? config values ?
thanks

**Comment by thesuperzapper** [comment]
> @thesuperzapper still have the same issue im upgrading packages according to the error log but its never end... what do you mean by "please provide any custom values" ? config values ? thanks

I mean your `custom-values.yaml` that sets any non-default helm values.

**Comment by thesuperzapper** [comment]
> @thesuperzapper still have the same issue im upgrading packages according to the error log but its never end... what do you mean by "please provide any custom values" ? config values ? thanks

@yossisht9876 I mean your `custom-values.yaml` that sets any non-default helm values.

**Comment by yossisht9876** [comment]
we dont use custom-value.yaml file
  
  we have for example config values that we added :
  
  ` AIRFLOW__EMAIL__EMAIL_BACKEND: "airflow_mailgunxxxxxxxxail_mailgun" 
    AIRFLOW__EMAIL__EMAIL_CONN_ID: "mailgun_default"
    AIRFLOW__SMTP__SMTP_STARTTLS: "True"
    AIRFLOW__MAILGUN__DOMAIN_NAME: "haxxx.co"
    AIRFLOW__MAILGUN__API_PASSWORD: "key-xxxxxxxxxxx
    AIRFLOW__API__AUTH_BACKEND: "airflow.api.auth.backend.basic_auth"`
    
    
    and :
     `connectionsTemplates:
    DdsdsdsdKS_TOKEN:
      kind: secret
      name: ddsdsdsen
      key: token
    ADsddsdsdsdsORD:
      kind: secret
      name: adddsdsdsdspassword
      key: AdssdsdSSWORD`
      
      
      or extra env :
      
      `extraEnv:
    - name: AIRFLOW__CORE__FERNET_KEY
      valueFrom:
        secretKeyRef:
          name: accccct-key
          key: FERNET_KEY
    - name: LcccccNV
      value: "dev"
    - name: AIRFLOW__SCHEDULER__MAX_DAGRUNS_PER_LOOP_TO_SCHEDULE
      value: "60"
    - name: AIRFLOW__CORE__MAX_ACTIVE_RUNS_PER_DAG
      value: "48"
    - name: AIRFLOW__METRICS__STATSD_DATADOG_ENABLED
      value: "true"
    - name: AIRFLOW__METRICS__STATSD_ON
      value: "True"
    - name: AIRFLOW__METRICS__STATSD_PORT
      value: "8125"
    - name: AIRFLOW__METRICS__STATSD_PREFIX
      value: airflow
    - name: AIRFLOW__METRICS__STATSD_HOST
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP`

**Comment by yossisht9876** [comment]
@thesuperzapper 
i removed some pip packages from my requirements file and everything is working now

thanks
