### ISSUE TITLE
Add suppport for linkerd

### ISSUE THREAD

**Issue by uwebartels** [airflow-helm/charts#670]
### Checks

- [X] I have checked for [existing issues](https://github.com/airflow-helm/charts/issues).
- [X] This report is about the [`User-Community Airflow Helm Chart`](https://github.com/airflow-helm/charts/tree/main/charts/airflow).

### Motivation

I need to integrate our airflow installation with linkerd2 for getting inter-pod communication encrypted.

### Implementation

I see that many pods use an init container wait-for-airflow-migrations. This is doing a postgres call. as postgres is not supported by linkerd as it is not http protocol, the init container is failing with this error:
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) connection to server at "airflow-pgbouncer.dev" (172.20.65.252), port 6543 failed: Connection refused

If the init container could do an http call to check for airflow-migration I think it would solve the error popping up.

Best...
Uwe

### Are you willing & able to help?

- [ ] I am able to submit a PR!
- [ ] I can help test the feature!

**Comment by thesuperzapper** [comment]
@uwebartels have you solved your issue?

If not, can you give more details?
