### ISSUE TITLE
Support renamed Kubernetes configuration in Airflow 2.5.0

### ISSUE THREAD

**Issue by emartgu** [airflow-helm/charts#677]
### Checks

- [X] I have checked for [existing issues](https://github.com/airflow-helm/charts/issues).
- [X] This report is about the [`User-Community Airflow Helm Chart`](https://github.com/airflow-helm/charts/tree/main/charts/airflow).

### Motivation

Airflow config section `kubernetes` renamed to `kubernetes_executor` in 2.5.0:
https://airflow.apache.org/docs/apache-airflow/stable/release_notes.html#airflow-config-section-kubernetes-renamed-to-kubernetes-executor-26873

This is causing warnings for now and might not work for later versions.

### Implementation

Introducing an if statement to pick the correct env variable names based on Airflow version in this section:
https://github.com/airflow-helm/charts/blob/2268f2416a580cbd3db2050160a29226913473ca/charts/airflow/templates/config/secret-config-envs.yaml#L182

Example (with introduced `airflow.version` value): 
```
  {{- if semverCompare "<2.5" .Values.airflow.version }}
    {{- if not .Values.airflow.config.AIRFLOW__KUBERNETES__NAMESPACE }}
  AIRFLOW__KUBERNETES__NAMESPACE: {{ .Release.Namespace | toString | b64enc | quote }}
    {{- end }}
  {{- else -}}
    {{- if not .Values.airflow.config.AIRFLOW__KUBERNETES_EXECUTOR__NAMESPACE }}
  AIRFLOW__KUBERNETES_EXECUTOR__NAMESPACE: {{ .Release.Namespace | toString | b64enc | quote }}
    {{- end }}
  {{- end }}
```

### Are you willing & able to help?

- [X] I am able to submit a PR!
- [ ] I can help test the feature!

**Comment by thesuperzapper** [comment]
@emartgu I want to avoid the need to explicitly set an `airflow.version` value, we can probably do something similar to what we did for [`logging.worker_log_server_port` replacing `celery.worker_log_server_port` in airflow 2.2.0](https://github.com/airflow-helm/charts/blob/airflow-8.6.1/charts/airflow/templates/config/secret-config-envs.yaml#L174-L176), and just include both configs.

This should suppress the warning logs, and future-proof us in case they remove the old one.
