### ISSUE TITLE
Git syn ref doesn't work for tags and sha1

### ISSUE THREAD

**Issue by symeneses** [airflow-helm/charts#69]
Hi all,
I have been using this chart for a while, so thanks for the good work.
 Seeing the notes in the [values.yaml](
https://github.com/airflow-helm/charts/blob/2885b3da4f4211b94e4a435e1269b6a5914921f2/charts/airflow/values.yaml#L960), it's possible to configure `ref` with tags and commits. However, testing it's only working with branches.  

With sha1:
- The clone doesn't work as `git clone $REPO -b $REF $DIR` doesn't work with a commit https://github.com/airflow-helm/charts/blob/2885b3da4f4211b94e4a435e1269b6a5914921f2/charts/airflow/templates/config/configmap-scripts-git.yaml#L37

With a tag:
- Cloning the repo works 
- git-sync is not working because of `git reset --hard origin/$REF` https://github.com/airflow-helm/charts/blob/2885b3da4f4211b94e4a435e1269b6a5914921f2/charts/airflow/templates/config/configmap-scripts-git.yaml#L73

Do you have any example of how to specify a commit or tag for the git-sync? 

  * PS: With the K8s executor, the env variable `AIRFLOW__KUBERNETES__GIT_SYNC_REV`can be used to set a revision but this will apply only for workers.

**Comment by thesuperzapper** [comment]
@symeneses it seems you are correct, (that docstring for `ref` is probably just from an old version of the chart).

I think we should support this feature, if you want you can raise a PR which fixes the git-sync script, you can find the code here:
https://github.com/airflow-helm/charts/blob/main/charts/airflow/templates/config/configmap-scripts-git.yaml

**Comment by thesuperzapper** [comment]
@symeneses this issue has been fixed in version `8.0.0` of the chart with the new `dags.gitSync.*` values.
