### ISSUE TITLE
Airflow 2.0 support for Kubernetes Executor pod_template_file 

### ISSUE THREAD

**Issue by darsi-an** [airflow-helm/charts#70]
**What is your feature request?**

Pod template files need to be supported in airflow 2.0 for Kubernetes Executor. This definitely needs to be discussed further to get a good idea on configs, and how we should go about supporting this feature.

**Comment by thesuperzapper** [comment]
I am working on this in the 8.0.0 release of the chart (which will be the first to officially support Airflow 2.0)
