### ISSUE TITLE
git-sync image url uses deprecated registry

### ISSUE THREAD

**Issue by simon-weber** [airflow-helm/charts#704]
### Checks

- [X] I have checked for [existing issues](https://github.com/airflow-helm/charts/issues).
- [X] This report is about the [`User-Community Airflow Helm Chart`](https://github.com/airflow-helm/charts/tree/main/charts/airflow).

### Chart Version

8.6.1

### Kubernetes Version

```shell
N/A
```

### Helm Version

```shell
N/A
```

### Description

The [k8s.gcr.io repo will be frozen next month](https://kubernetes.io/blog/2023/02/06/k8s-gcr-io-freeze-announcement/). While looking at image urls in a cluster I maintain I noticed that [the git-sync image in this chart still points to the deprecated repo](https://github.com/airflow-helm/charts/blob/afcbe796e7e2d979abcb172f7ebe011ab55ce44c/charts/airflow/values.yaml#L1313).

Everything will continue to work when the repo is frozen afaik, but future versions of git-sync will only be available from the new repository: https://github.com/kubernetes/git-sync/releases.

**Comment by thesuperzapper** [comment]
@simon-weber thanks, I will be updating the default image used in the release of `8.7.0` I make today/tomorrow.
