### ISSUE TITLE
[stable/airflow] KubernetesExecutor - Task pods entrypoint extraPipPackages/installRequirements

### ISSUE THREAD

**Issue by migueltp** [airflow-helm/charts#71]
**Describe the bug**

We are using KubernetesExecutor and tried to install additional pip packages in task pods, by using either `dags.installRequirements` and/or `airflow.extraPipPackages`, without success.

**Version of Helm and Kubernetes:**

Helm: 3.4.2
Kubernetes: 1.17.14

**Which chart:**

stable/airflow:7.14.0

**What happened:**

We added dependencies to `airflow.extraPipPackages` and installed the chart, but task pods didn't install those packages. We have also tried the approach described by @alexbegg at [this issue](https://github.com/helm/charts/issues/22656) - using `dags.installRequirements` and `dags.initContainer` but it only seems to affect celery workers. During our tests, we were not able to install packages from requirements.txt at our git repo's root in task pods spawned by the K8sExecutor.

We ended up extending the base image with dependencies.

**What you expected to happen:**

The template on which task pods are created should inherit from these parameters, just as data.install-requirements.sh does for celery workers. 

Documentation could be more explicit on how these parameters work for K8sExecutor - task pods template.

**How to reproduce it (as minimally and precisely as possible):**

Most relevant ones:

- add a requirements.txt at a git repo's root with a unique dependency you can later check on.
- Set values in custom-values.yaml:

 -- "airflow.executor: KubernetesExecutor"
 
 -- "workers.enabled: false"
 
 -- "dags.installRequirements: true"
 
 -- "dags.gitSync.enabled: true"
 
 -- "dags.initContainer.enabled: true"
 
- Make a long running task so that you can comfortably attach to the task pod and inspect installed libraries for your step 1 dependency.

**Anything else we need to know:**

Closing a [duplicate issue](https://github.com/helm/charts/issues/24464) I created at the legacy repo.

**Comment by thesuperzapper** [comment]
This feature has been implemented in version `8.0.0` of the chart with the `airflow.kubernetesPodTemplate.extraPipPackages` value, although I would caution against using it until we have removed the need for pip-install to run every time a pod starts (unless you are installing very small packages).

**Comment by harvetech** [comment]
@thesuperzapper I tried to use `airflow.kubernetesPodTemplate.extraPipPackages` but still pods were not installed with those specific pip packages. I also tried to specifically add required in scheduler, worker, and webserver but still, packages were not installed. Any solution except extending the official image ?

**Comment by thesuperzapper** [comment]
@harvetech what version of the chart are you using?

And can you share your values?

Possibly raise a new issue for this.
