### ISSUE TITLE
Liveness probes don't work for airflow 2.6.0

### ISSUE THREAD

**Issue by DavidSpek** [airflow-helm/charts#737]
### Checks

- [X] I have checked for [existing issues](https://github.com/airflow-helm/charts/issues).
- [X] This report is about the [`User-Community Airflow Helm Chart`](https://github.com/airflow-helm/charts/tree/main/charts/airflow).

### Chart Version

8.7.0

### Kubernetes Version

```shell
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.2", GitCommit:"fc04e732bb3e7198d2fa44efa5457c7c6f8c0f5b", GitTreeState:"clean", BuildDate:"2023-02-22T13:32:21Z", GoVersion:"go1.20.1", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.16-eks-48e63af", GitCommit:"e6332a8a3feb9e0fe3db851878f88cb73d49dd7a", GitTreeState:"clean", BuildDate:"2023-01-24T19:18:15Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
```

### Helm Version

```shell
version.BuildInfo{Version:"v3.11.1", GitCommit:"293b50c65d4d56187cd4e2f390f0ada46b4c4737", GitTreeState:"clean", GoVersion:"go1.19.5"}
```

### Description

The liveness probes for the scheduler and triggerer don't work with Airflow 2.6.0 due to change https://github.com/apache/airflow/pull/30302. This changes the package names that need to be imported. The probes need to be changed similar to the code in https://github.com/apache/airflow/blob/2f247a2ba2fb7c9f1fe71567a80f0063e21a5f55/airflow/utils/scheduler_health.py.

**Comment by thesuperzapper** [comment]
@DavidSpek this issue has been fixed in [version `8.7.1` of the chart](https://github.com/airflow-helm/charts/blob/main/charts/airflow/CHANGELOG.md#871---2023-05-13).
