### ISSUE TITLE
Enabling gitsync and PVC should work

### ISSUE THREAD

**Issue by ekdeveloper** [airflow-helm/charts#741]
### Checks

- [X] I have checked for [existing issues](https://github.com/airflow-helm/charts/issues).
- [x] This report is about the [`User-Community Airflow Helm Chart`](https://github.com/airflow-helm/charts/tree/main/charts/airflow).

### Chart Version

8.7.0

### Kubernetes Version

```shell
NA
```

### Helm Version

```shell
8.7.0
```

### Description

airflow doc says the both gitsync and pvc can be enabled
https://airflow.apache.org/docs/helm-chart/stable/manage-dags-files.html#mounting-dags-using-git-sync-sidecar-with-persistence-enabled

https://github.com/apache/airflow/blob/97215822f90cac274e92e642fcd724cc940fe0eb/chart/templates/dag-processor/dag-processor-deployment.yaml#L135

however there is a validation check to prevent this
https://github.com/airflow-helm/charts/blob/f5c2f0cd617982c642789cf66fdef48453f84e67/charts/airflow/templates/_helpers/validate-values.tpl#LL122C1-L122C1

**Comment by thesuperzapper** [comment]
@ekdeveloper the docs you are referencing are for a different helm chart. This helm chart (the User-Community one) is planning to implement support for having both git-sync and PVC persistence soon (see https://github.com/airflow-helm/charts/issues/283), but this change has not yet been merged, hence the values-validation which prevents it for now.
