### ISSUE TITLE
pgBouncer fails to start when I deploy on Openshift

### ISSUE THREAD

**Issue by robkuehl** [airflow-helm/charts#750]
### Checks

- [X] I have checked for [existing issues](https://github.com/airflow-helm/charts/issues).
- [X] This report is about the [`User-Community Airflow Helm Chart`](https://github.com/airflow-helm/charts/tree/main/charts/airflow).

### Chart Version

8.7.1

### Kubernetes Version

```shell
Client Version: v1.26.1
Server Version: v1.23.12+7566c4d
```

### Helm Version

```shell
version.BuildInfo{Version:"v3.11.1", GitCommit:"293b50c65d4d56187cd4e2f390f0ada46b4c4737", GitTreeState:"clean", GoVersion:"go1.19.5"}
```

### Description

I am tryining to deploy Airflow into Azure Red Hat Openshift (ARO). The deployment works when I disable pgbouncer.
When I add pgbouncer, it fails for the pgbouncer container.

### Relevant Logs

```shell
mkdir: can't create directory '/home/pgbouncer/generated-certs': Permission denied
/home/pgbouncer/config/gen_self_signed_cert.sh: line 16: openssl: not found
chmod: /home/pgbouncer/generated-certs/client.key: No such file or directory
Successfully generated self-signed certificate: /home/pgbouncer/generated-certs/client.crt
Successfully generated self-signed certificate key: /home/pgbouncer/generated-certs/client.key
/home/pgbouncer/config/gen_auth_file.sh: line 18: can't create /home/pgbouncer/users.txt: Permission denied
Successfully generated auth_file: /home/pgbouncer/users.txt
2023-06-19 09:56:22.418 UTC [7] ERROR could not open auth_file /home/pgbouncer/users.txt: No such file or directory
2023-06-19 09:56:22.421 UTC [7] ERROR TLS setup failed: failed to load certificate file "/home/pgbouncer/generated-certs/client.crt": No such file or directory
2023-06-19 09:56:22.421 UTC [7] FATAL TLS setup failed
```

### Custom Helm Values

```yaml
pgbouncer:
  ## if the pgbouncer Deployment is created
  ## [FAQ] https://github.com/airflow-helm/charts/blob/main/charts/airflow/docs/faq/database/pgbouncer.md
  enabled: true

  ## configs for the pgbouncer container image
  ##
  image:
    repository: ghcr.io/airflow-helm/pgbouncer
    tag: 1.17.0-patch.0
    pullPolicy: IfNotPresent
    uid: 1000710002
    gid: 1001

  ## resource requests/limits for the pgbouncer Pods
  ## [SPEC] https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#resourcerequirements-v1-core
  resources: {}

  ## sets pgbouncer config: `auth_type`
  authType: scram-sha-256

  serverSSL:
    ## sets pgbouncer config: `server_tls_sslmode`
    mode: verify-full

    # ## sets pgbouncer config: `server_tls_ciphers`
    # ciphers: normal

    ## sets pgbouncer config: `server_tls_ca_file`
    caFile:
      existingSecret: "postgres-tls-secret"
      existingSecretKey: root.crt
```

**Comment by buffaloDeveloper** [comment]
Seeing the same issue.  How did you resolve this?


Logs from
pgbouncer
in
airflow-cluster-pgbouncer-7cbfcf8464-ntjqf
/home/pgbouncer/config/gen_self_signed_cert.sh: line 16: openssl: not found
chmod: /home/pgbouncer/generated-certs/client.key: No such file or directory
Successfully generated self-signed certificate: /home/pgbouncer/generated-certs/client.crt
Successfully generated self-signed certificate key: /home/pgbouncer/generated-certs/client.key
Successfully generated auth_file: /home/pgbouncer/users.txt
2024-01-02 16:44:48.772 UTC [7] ERROR TLS setup failed: failed to load certificate file "/home/pgbouncer/generated-certs/client.crt": No such file or directory
2024-01-02 16:44:48.772 UTC [7] FATAL TLS setup failed

**Comment by fvbrandt** [comment]
Having the same issue on an enterprise hosted OpenShift.
I assume the root cause is that the pgbouncer imagefile creates user/group 1001:1001 and uses that users HOME directory which has permissions `drwxr-sr-x`, so only *that* user can create files there. So it doesn't help if we set `pgbouncer.image.gid` to 1001, we would actually need `uid: 1001`.
But for OpenShift to my understanding the usual setup forces you to use users in a specified range of UIDs, like the `uid: 1000710002` that OP are using.
That seems to make the pgbouncer image unusable for OpenShift setups where uid 1001 is not allowed. @thesuperzapper I read somewhere that you also run airflow on OpenShift. Would you have any input for us on how one should set this up ideally?
