### ISSUE TITLE
Pods accumulate lots of RAM

### ISSUE THREAD

**Issue by robkuehl** [airflow-helm/charts#758]
### Checks

- [X] I have checked for [existing issues](https://github.com/airflow-helm/charts/issues).
- [X] This report is about the [`User-Community Airflow Helm Chart`](https://github.com/airflow-helm/charts/tree/main/charts/airflow).

### Chart Version

8.7.1

### Kubernetes Version

```shell
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"8f94681cd294aa8cfd3407b8191f6c70214973a4", GitTreeState:"clean", BuildDate:"2023-01-18T15:51:24Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"darwin/arm64"}

Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.12+7566c4d", GitCommit:"22147459669562208c3082141eece03824c0a417", GitTreeState:"clean", BuildDate:"2022-10-24T10:40:54Z", GoVersion:"go1.17.12", Compiler:"gc", Platform:"linux/amd64"}
```

### Helm Version

```shell
version.BuildInfo{Version:"v3.11.1", GitCommit:"293b50c65d4d56187cd4e2f390f0ada46b4c4737", GitTreeState:"clean", GoVersion:"go1.19.5"}
```

### Description

The Pods accumulate a lot of RAM quickly. Is this behavior normal?
![Screenshot 2023-07-06 101415](https://github.com/airflow-helm/charts/assets/43447411/c9296bcc-000f-4205-a0cd-50b1881b453c)

**Comment by thesuperzapper** [comment]
@robkuehl this is not typical, so you might want to check if any of your dag definitions have a memory leak (note, I am talking about the python definitions, not the dags themselves).

Or if you have a custom airflow image, anything you have changed in it could be the cause.

Its also possible that you have found a bug in airflow itself, which version are you using?
