### ISSUE TITLE
[rfc] configmap/crd based DAGs

### ISSUE THREAD

**Issue by kervel** [airflow-helm/charts#79]
**What is your feature request?**

Hello, when deploying dags from different sources it would be nice to leave a stable airflow installation untouched, and by having every source have its own gitrepo. In addition to this, it would be nice to use tools like skaffold during development to hot-deploy or even live edit code (without committing every time you make a change).

Therefore, another way of putting DAGs and requirements would be nice: putting different DAGs in configmaps and whenever a configmap changes, the files are updated automatically. I now do this using flant/shell-operator and the python hook script. Then tools like skaffold could take care of deploying the configmaps for ergonomic development.

https://gist.github.com/kervel/c557f888ffe202f738753c2218766999

I put this as a request for comments to see if others considered something similar, and how other teams manage the situation where you have one airflow instance that runs multiple (not necessarily related) DAGs.

**What alternatives have you considered?**

* git sync with a central gitrepo where everybody sends PRs to to deploy stuff.
* using skaffold to live sync the DAGs when editing them directly using the airflow helm chart.

**Comment by thesuperzapper** [comment]
@kervel this is an interesting idea, but what are you needing from the chart?

**Comment by kervel** [comment]
i don't know, was more of an open question. it could become a new method for deploying DAGs as part of the chart (but i wonder if you fancy the method with the shell-operator and the RWX volume which some would consider quick&dirty, wonder if there could be other approaches). in that case we could try to pack our changes as a PR.

or maybe its just an idea that has no place here, in which case i'm fine with closing the issue off course.
