### ISSUE TITLE
How to provide several secrets to secretsMap?

### ISSUE THREAD

**Issue by KIRY4** [airflow-helm/charts#80]
**What is your question?**

Hello. How to provide several secrets to secretsMap to mount into web pod?

If I provide one (secretsMap: "secret1"). Everything works fine. But how to provide 2nd one? I tried several options and usually get something like that..

Error: UPGRADE FAILED: YAML parse error on airflow/templates/webserver/webserver-deployment.yaml: error converting YAML to JSON: yaml: line 104: did not find expected key

**Comment by thesuperzapper** [comment]
After version `8.0.0` of the chart we have removed all `secretMap` values, and now only have `extraVolumeMounts` and `extraVolumes`.

You can see an example for workers here: 
https://github.com/airflow-helm/charts/tree/main/charts/airflow#how-to-mount-secretsconfigmaps-as-files-on-workers
