### ISSUE TITLE
Feature - add dask executor support

### ISSUE THREAD

**Issue by cherusk** [airflow-helm/charts#815]
### Checks

- [X] I have checked for [existing issues](https://github.com/airflow-helm/charts/issues).
- [X] This report is about the [`User-Community Airflow Helm Chart`](https://github.com/airflow-helm/charts/tree/main/charts/airflow).

### Motivation

I would like to use this chart as part of an step in the efforts of operationalizing [godon](https://github.com/cherusk/godon) stack.

I find dask executor is a great option, in my mind even superior to the other executors. In other words I do not want to use the othe executors for various reasons.

### Implementation

As several executor "backends" are already supported by this chart, taking up dask executor should not be too great of a lifting.

### Are you willing & able to help?

- [X] I am able to submit a PR!
- [X] I can help test the feature!

**Comment by thesuperzapper** [comment]
@cherusk Are you interested in contributing to this feature, or are you only able to test?

**Comment by cherusk** [comment]
@thesuperzapper I've perused the code an I think I can mostly implement this myself.

Viably I will need supervision/advice beyond a PR review how to approach it best.

I'll file a PR soonish ...

**Comment by thesuperzapper** [comment]
@cherusk it looks like the upstream project has decided to stop supporting `DaskExecutor`:

- https://github.com/apache/airflow/pull/35965

:(

**Comment by cherusk** [comment]
@thesuperzapper that's only part of the truth. They stopped maintaining/updating it themselves, but it will still work with future versions.

Please see https://github.com/apache/airflow/pull/35965#issuecomment-1882890410

I don't see this to be reason enough to close the PR right away.
