### ISSUE TITLE
Add TZ option

### ISSUE THREAD

**Issue by achovelon** [airflow-helm/charts#817]
### Checks

- [X] I have checked for [existing issues](https://github.com/airflow-helm/charts/issues).
- [X] This report is about the [`User-Community Airflow Helm Chart`](https://github.com/airflow-helm/charts/tree/main/charts/airflow).

### Motivation

Hello,
I would like to have the option to choose my default TZ for airflow scheduler.
On the chart it's fixed to etc/UTC : https://github.com/airflow-helm/charts/blob/main/charts/airflow/templates/config/secret-config-envs.yaml#L15
Do you think it's a good idea to variabilize this option? Or to just remove it from this secret so we could configure it using the "config" section.
Thanks for your help here.
BR,

### Implementation

If we could remove line 15 : https://github.com/airflow-helm/charts/blob/main/charts/airflow/templates/config/secret-config-envs.yaml#L15
Or add vars here.

### Are you willing & able to help?

- [X] I am able to submit a PR!
- [X] I can help test the feature!

**Comment by thesuperzapper** [comment]
I highly recommend using `UTC` as your timezone, this is in line with Airflow's official recommendations.

Note, this will not stop you creating DAG schedules in any timezone you like:

- https://airflow.apache.org/docs/apache-airflow/stable/authoring-and-scheduling/timezone.html#time-zone-aware-dags
