### ISSUE TITLE
Cannot connect to postgresql embedded because postgres password failed

### ISSUE THREAD

**Issue by docodeid** [airflow-helm/charts#823]
### Checks

- [X] I have checked for [existing issues](https://github.com/airflow-helm/charts/issues).
- [X] This report is about the [`User-Community Airflow Helm Chart`](https://github.com/airflow-helm/charts/tree/main/charts/airflow).

### Chart Version

8.8.0

### Kubernetes Version

```shell
Client Version: version.Info{Major:"1", Minor:"27+", GitVersion:"v1.27.9-dispatcher", GitCommit:"8b508a33aafcd3ba51641b6b2ef203adbdd9de1e", GitTreeState:"clean", BuildDate:"2023-12-21T23:22:51Z", GoVersion:"go1.20.12", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.7-gke.1121000", GitCommit:"4daab1fd78c0b9aba478a19b363ab4a25bdadd79", GitTreeState:"clean", BuildDate:"2023-11-06T09:24:38Z", GoVersion:"go1.20.10 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
```

### Helm Version

```shell
version.BuildInfo{Version:"v3.14.0", GitCommit:"3fc9f4b2638e76f26739cd77c7017139be81d0ea", GitTreeState:"clean", GoVersion:"go1.21.6"}
```

### Description

i was trying to deploy into GKE but just only pod postgresql and redis-master is running well and other is Init:CrashLoopBackOff,
when i chek in log the message is 
[2409] FATAL:  password authentication failed for user "postgres"

the status of pods like in picture
<img width="834" alt="image" src="https://github.com/airflow-helm/charts/assets/122348336/b6d5dfb3-ad1e-4eb1-ab90-898234e117cd">

**Comment by thesuperzapper** [comment]
@docodeid perhaps just delete the Postgres deployment and its PVC to clear it out (assuming you don't need the data on it). It probably has some kind of corruption.

**Comment by docodeid** [comment]
@thesuperzapper resolved by default password of postgres user is 'postgres'
