### ISSUE TITLE
Show connections and variables in the UI when using secrets backend

### ISSUE THREAD

**Issue by ketozhang** [airflow-helm/charts#873]
### Checks

- [X] I have checked for [existing issues](https://github.com/airflow-helm/charts/issues).
- [X] This report is about the [`User-Community Airflow Helm Chart`](https://github.com/airflow-helm/charts/tree/main/charts/airflow).

### Motivation

The [documentation says](https://airflow.apache.org/docs/apache-airflow/2.9.2/security/secrets/secrets-backend/index.html)...
> The Airflow UI only shows connections and variables stored in the Metadata DB and not via any other method. If you use an alternative secrets backend, check inside your backend to view the values of your variables and connections.

As an admin, this information is easy to forget and easy to panic when you see an empty list of connections in the UI and `airflow connections list` (same for variables).

### Implementation

No implementation in mind. Willing to contribute if there are ideas on how to get started on this.

### Are you willing & able to help?

- [X] I am able to submit a PR!
- [X] I can help test the feature!

**Comment by thesuperzapper** [comment]
@ketozhang as this is a request about airflow itself, please raise an issue on the `apache/airflow` GitHub repo, not the helm chart repo.

**Comment by ketozhang** [comment]
Whoops I didn't realize which repo I was in. Sorry for the silliness!
