### ISSUE TITLE
extraEnv values are not templated, but docs suggest they are

### ISSUE THREAD

**Issue by jessebye** [airflow-helm/charts#879]
### Checks

- [X] I have checked for [existing issues](https://github.com/airflow-helm/charts/issues).
- [X] This report is about the [`User-Community Airflow Helm Chart`](https://github.com/airflow-helm/charts/tree/main/charts/airflow).

### Chart Version

8.9.0

### Kubernetes Version

```shell
Client Version: v1.30.3
Server Version: v1.29.6-eks-db838b0
```

### Helm Version

```shell
version.BuildInfo{Version:"v3.15.4", GitCommit:"fa9efb07d9d8debbb4306d72af76a383895aa8c4", GitTreeState:"clean", GoVersion:"go1.22.6"}
```

### Description

The [chart documentation](https://airflow.apache.org/docs/helm-chart/stable/adding-connections-and-variables.html#variables) suggests that `extraEnv` values will be templated:

> You can also utilize extraEnv and extraEnvFrom if you need the name or value to be templated.

However, those values do not get templated.

**Comment by thesuperzapper** [comment]
You are linking to the docs of a different chart.

However, I am open to allowing templating in the `airflow.extraEnv` values in this chart, I see that you have raised a PR to add this functionality, lets discuss it more there:

- https://github.com/airflow-helm/charts/pull/874

**Comment by thesuperzapper** [comment]
@jessebye You are linking to the docs of a different chart.

However, I am open to allowing templating in the `airflow.extraEnv` values in this chart, I see that you have raised a PR to add this functionality, lets discuss it more there:

- https://github.com/airflow-helm/charts/pull/874

**Comment by jessebye** [comment]
@thesuperzapper oops, sorry about that - got the two mixed up. Yes let's discuss in the PR and I'll close this issue out 😄  thank you!
