### ISSUE TITLE
Upgrade failure for Airflow 2.10.2

### ISSUE THREAD

**Issue by Amar1404** [airflow-helm/charts#889]
### Checks

- [X] I have checked for [existing issues](https://github.com/airflow-helm/charts/issues).
- [X] This report is about the [`User-Community Airflow Helm Chart`](https://github.com/airflow-helm/charts/tree/main/charts/airflow).

### Chart Version

8.9.0

### Kubernetes Version

```shell
v1.29.7
```

### Helm Version

```shell
v3.0.0
```

### Description

UPGRADE FAILED: parse error at (airflow/templates/sync/_helpers/sync_pools.tpl:100): function "dig" not defined

**Comment by thesuperzapper** [comment]
@Amar1404 update your helm version if you are actually using 3.0.0, that is extremely old, and probably missing many functions.

**Comment by Amar1404** [comment]
@thesuperzapper - This is working now thanks
