### ISSUE TITLE
Support PersistentVolumeClaim retention feature

### ISSUE THREAD

**Issue by Setsushin** [airflow-helm/charts#892]
### Checks

- [X] I have checked for [existing issues](https://github.com/airflow-helm/charts/issues).
- [X] This report is about the [`User-Community Airflow Helm Chart`](https://github.com/airflow-helm/charts/tree/main/charts/airflow).

### Motivation

Sometimes we need extra workers for large tasks, but these tasks don't occur very often.
We prefer not to keep workers on standby all the time, as this helps reduce costs.

### Implementation

Ref: https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#persistentvolumeclaim-retention

Add `.spec.persistentVolumeClaimRetentionPolicy` property to the [template file](https://github.com/airflow-helm/charts/blob/main/charts/airflow/templates/worker/worker-statefulset.yaml).

### Are you willing & able to help?

- [ ] I am able to submit a PR!
- [X] I can help test the feature!

**Comment by thesuperzapper** [comment]
@Setsushin we don't currently mount any PVCs on the worker StatefulSet by default.

Are you mounting one for some reason, and if so, can you confirm what you use this PVC for?

**Comment by Setsushin** [comment]
@thesuperzapper 

Sorry, this is my misunderstanding. I found that the chart I used is not the community version but [the official version](https://github.com/apache/airflow/tree/main/chart). The official version defaults to using PVC and supports the configuration of`persistentVolumeClaimRetentionPolicy`.

Thanks for the reply and have a good day.
