### ISSUE TITLE
Add RBAC "get" and "list" permissions from  the resource "pod/status"

### ISSUE THREAD

**Issue by rafaelkonrath** [airflow-helm/charts#93]
**What is your feature request?**
We'd like Airflow has access to the resource  "pod/status"  and permission to use these Verbs "get/list", with that Airflow can log status events such as OOMKilled in the log. This helps to analyse the root cause of some K8S pod failed, and not only show in the log the generic message: "Pod returned a failure: failed", but the real pod failed status.

Thank you

**Comment by thesuperzapper** [comment]
Can you give an example how how airflow will use the new RBAC verbs?

That is, is this something you do in your task code, like with `KubernetesPodOperator()` and `log_events_on_failure=True`?

**Comment by thesuperzapper** [comment]
@rafaelkonrath can you clarify if the `pod/status` verb is used by airflow itself, or just your Kuberetes operators?
