### ISSUE TITLE
Chart needs to be updated for airflow 2.0

### ISSUE THREAD

**Issue by samudurand** [airflow-helm/charts#95]
**What is the bug?**

Airflow 2.0 has some different commands. The result is that the scheduler is failing.

According to this issue https://github.com/airflow-helm/charts/issues/66 , the solution is to replace 2 lines in the scheduler helm template:

```
...
&& airflow variables -i /home/airflow/variables-pools/variables.json \
...
&& airflow pools -i /home/airflow/variables-pools/pools.json \
...
```

By 

```
...
&& airflow variables import /home/airflow/variables-pools/variables.json \
...
&& airflow pools import /home/airflow/variables-pools/pools.json \
...
```

I could do a PR to that effect, if that helps ?

**Comment by thesuperzapper** [comment]
Lol, please wait a couple of hours, see the issue here: https://github.com/airflow-helm/charts/issues/58

**Comment by samudurand** [comment]
Lucky me !!
